package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:16:06Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: Bahyph.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class Bahyph extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return false; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "Bahyph"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "Bahyph License"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "COPYRIGHT NOTICE   \n"
        + "\n"
        + "These patterns and the generating sh script are Copyright (c) GMV 1991  \n"
        + "\n"
        + "These patterns were developed for internal GMV use and are made public in the ho"
        + "pe that they will benefit others. Also, spreading these patterns throughout the "
        + "Spanish-language TeX community is expected to provide back-benefits to GMV in th"
        + "at it can help keeping GMV in the mainstream of spanish users. \n"
        + "\n"
        + "However, this is given for free and WITHOUT ANY WARRANTY. Under no circumstances"
        + " can Julio Sanchez, GMV, Jos'e A. Ma~nas or any agents or representatives thereo"
        + "f be held responsible for any errors in this software nor for any damages derive"
        + "d from its use, even in case any of the above has been notified of the possibili"
        + "ty of such damages. If any such situation arises, you responsible for repair. Us"
        + "e of this software is an explicit  acceptance of these conditions.   \n"
        + "\n"
        + "You can use this software for any purpose. You cannot delete this  copyright not"
        + "ice. If you change this software, you must include comments explaining who, when"
        + " and why. You are kindly requested to send any changes to tex@gmv.es. If you cha"
        + "nge the generating script, you must include code in it such that any output is c"
        + "learly labeled as generated by a modified script.   Despite the lack of warranty"
        + ", we would like to hear about any problem you find. Please report problems to te"
        + "x@gmv.es.   \n"
        + "\n"
        + "END OF COPYRIGHT NOTICE\n"
; // the license text
    }
 
    
}
