package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:16:09Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: BitTorrent_1_0.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class BitTorrent_1_0 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return false; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "BitTorrent-1.0"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "BitTorrent Open Source License v1.0"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "BitTorrent Open Source License\n"
        + " \n"
        + "Version 1.0\n"
        + " \n"
        + "This BitTorrent Open Source License (the \"License\") applies to the BitTorrent cl"
        + "ient and related software products as well as any updates or maintenance release"
        + "s of that software (\"BitTorrent Products\") that are distributed by BitTorrent, I"
        + "nc. (\"Licensor\").  Any BitTorrent Product licensed pursuant to this License is a"
        + " Licensed Product. Licensed Product, in its entirety, is protected by U.S. copyr"
        + "ight law.  This License identifies the terms under which you may use, copy, dist"
        + "ribute or modify Licensed Product. \n"
        + " \n"
        + "Preamble\n"
        + " \n"
        + "This Preamble is intended to describe, in plain English, the nature and scope of"
        + " this License.  However, this Preamble is not a part of this license.  The legal"
        + " effect of this License is dependent only upon the terms of the License and not "
        + "this Preamble.\n"
        + " \n"
        + "This License complies with the Open Source Definition and is derived from the Ja"
        + "bber Open Source License 1.0 (the \"JOSL\"), which has been approved by Open Sourc"
        + "e Initiative. Sections 4(c) and 4(f)(iii) from the JOSL have been dropped.\n"
        + " \n"
        + "This License provides that:\n"
        + " \n"
        + "1. You may use, sell or give away the Licensed Product, alone or as a component "
        + "of an aggregate software distribution containing programs from several different"
        + " sources.  No royalty or other fee is required.\n"
        + " \n"
        + "2. Both Source Code and executable versions of the Licensed Product, including M"
        + "odifications made by previous Contributors, are available for your use.  (The te"
        + "rms \"Licensed Product,\" \"Modifications,\" \"Contributors\" and \"Source Code\" are de"
        + "fined in the License.)\n"
        + " \n"
        + "3. You are allowed to make Modifications to the Licensed Product, and you can cr"
        + "eate Derivative Works from it. (The term \"Derivative Works\" is defined in the Li"
        + "cense.)\n"
        + " \n"
        + "4. By accepting the Licensed Product under the provisions of this License, you a"
        + "gree that any Modifications you make to the Licensed Product and then distribute"
        + " are governed by the provisions of this License.  In particular, you must make t"
        + "he Source Code of your Modifications available to others.\n"
        + " \n"
        + "5. You may use the Licensed Product for any purpose, but the Licensor is not pro"
        + "viding you any warranty whatsoever, nor is the Licensor accepting any liability "
        + "in the event that the Licensed Product doesn't work properly or causes you any i"
        + "njury or damages.\n"
        + " \n"
        + "6. If you sublicense the Licensed Product or Derivative Works, you may charge fe"
        + "es for warranty or support, or for accepting indemnity or liability obligations "
        + "to your customers.  You cannot charge for the Source Code.\n"
        + " \n"
        + "7. If you assert any patent claims against the Licensor relating to the Licensed"
        + " Product, or if you breach any terms of the License, your rights to the Licensed"
        + " Product under this License automatically terminate.\n"
        + " \n"
        + "You may use this License to distribute your own Derivative Works, in which case "
        + "the provisions of this License will apply to your Derivative Works just as they "
        + "do to the original Licensed Product.\n"
        + " \n"
        + "Alternatively, you may distribute your Derivative Works under any other OSI-appr"
        + "oved Open Source license, or under a proprietary license of your choice.  If you"
        + " use any license other than this License, however, you must continue to fulfill "
        + "the requirements of this License (including the provisions relating to publishin"
        + "g the Source Code) for those portions of your Derivative Works that consist of t"
        + "he Licensed Product, including the files containing Modifications.\n"
        + " \n"
        + "New versions of this License may be published from time to time.  You may choose"
        + " to  continue to use the license terms in this version of the License or those f"
        + "rom the new version.  However, only the Licensor has the right to change the Lic"
        + "ense terms as they apply to the Licensed Product. \n"
        + " \n"
        + "This License relies on precise definitions for certain terms.  Those terms are d"
        + "efined when they are first used, and the definitions are repeated for your conve"
        + "nience in a Glossary at the end of the License.\n"
        + " \n"
        + " \n"
        + "License Terms\n"
        + " \n"
        + "1. Grant of License From Licensor.  Licensor hereby grants you a world-wide, roy"
        + "alty-free, non-exclusive license, subject to third party intellectual property c"
        + "laims, to do the following:\n"
        + "     a. Use, reproduce, modify, display, perform, sublicense and distribute any "
        + "Modifications created by such Contributor or portions thereof, in both Source Co"
        + "de or as an executable program, either on an unmodified basis or as part of Deri"
        + "vative Works.\n"
        + "     b. Under claims of patents now or hereafter owned or controlled by Contribu"
        + "tor, to make, use, sell, offer for sale, have made, and/or otherwise dispose of "
        + "Modifications or portions thereof, but solely to the extent that any such claim "
        + "is necessary to enable you to make, use, sell, offer for sale, have made, and/or"
        + " otherwise dispose of Modifications or portions thereof or Derivative Works ther"
        + "eof.\n"
        + " \n"
        + "2. Grant of License to Modifications From Contributor. \"Modifications\" means any"
        + " additions to or deletions from the substance or structure of (i) a file contain"
        + "ing Licensed Product, or (ii) any new file that contains any part of Licensed Pr"
        + "oduct. Hereinafter in this License, the term \"Licensed Product\" shall include al"
        + "l previous Modifications that you receive from any Contributor. By application o"
        + "f the provisions in Section 4(a) below, each person or entity who created or con"
        + "tributed to the creation of, and distributed, a Modification (a \"Contributor\") h"
        + "ereby grants you a world-wide, royalty-free, non-exclusive license, subject to t"
        + "hird party intellectual property claims, to do the following:\n"
        + "     1. Use, reproduce, modify, display, perform, sublicense and distribute any "
        + "Modifications created by such Contributor or portions thereof, in both Source Co"
        + "de or as an executable program, either on an unmodified basis or as part of Deri"
        + "vative Works.\n"
        + "     2. Under claims of patents now or hereafter owned or controlled by Contribu"
        + "tor, to make, use, sell, offer for sale, have made, and/or otherwise dispose of "
        + "Modifications or portions thereof, but solely to the extent that any such claim "
        + "is necessary to enable you to make, use, sell, offer for sale, have made, and/or"
        + " otherwise dispose of Modifications or portions thereof or Derivative Works ther"
        + "eof. \n"
        + " \n"
        + "3. Exclusions From License Grant.  Nothing in this License shall be deemed to gr"
        + "ant any rights to trademarks, copyrights, patents, trade secrets or any other in"
        + "tellectual property of Licensor or any Contributor except as expressly stated he"
        + "rein. No patent license is granted separate from the Licensed Product, for code "
        + "that you delete from the Licensed Product, or for combinations of the Licensed P"
        + "roduct with other software or hardware.  No right is granted to the trademarks o"
        + "f Licensor or any Contributor even if such marks are included in the Licensed Pr"
        + "oduct. Nothing in this License shall be interpreted to prohibit Licensor from li"
        + "censing under different terms from this License any code that Licensor otherwise"
        + " would have a right to license.\n"
        + " \n"
        + "4. Your Obligations Regarding Distribution. \n"
        + "     a. Application of This License to Your Modifications.  As an express condit"
        + "ion for your use of the Licensed Product, you hereby agree that any Modification"
        + "s that you create or to which you contribute, and which you distribute, are gove"
        + "rned by the terms of this License including, without limitation, Section 2.  Any"
        + " Modifications that you create or to which you contribute may be distributed onl"
        + "y under the terms of this License or a future version of this License released u"
        + "nder Section 7.  You must include a copy of this License with every copy of the "
        + "Modifications you distribute.  You agree not to offer or impose any terms on any"
        + " Source Code or executable version of the Licensed Product or Modifications that"
        + " alter or restrict the applicable version of this License or the recipients' rig"
        + "hts hereunder. However, you may include an additional document offering the addi"
        + "tional rights described in Section 4(d).\n"
        + "\n"
        + "     b. Availability of Source Code.  You must make available, under the terms o"
        + "f this License, the Source Code of the Licensed Product and any Modifications th"
        + "at you distribute, either on the same media as you distribute any executable or "
        + "other form of the Licensed Product, or via a mechanism generally accepted in the"
        + " software development community for the electronic transfer of data (an \"Electro"
        + "nic Distribution Mechanism\").  The Source Code for any version of Licensed Produ"
        + "ct or Modifications that you distribute must remain available for at least twelv"
        + "e (12) months after the date it initially became available, or at least six (6) "
        + "months after a subsequent version of said Licensed Product or Modifications has "
        + "been made available.  You are responsible for ensuring that the Source Code\n"
        + "version remains available even if the Electronic Distribution Mechanism is maint"
        + "ained by a third party.\n"
        + "\n"
        + "     c. Intellectual Property Matters.  \n"
        + "          i. Third Party Claims.  If you have knowledge that a license to a thir"
        + "d party's intellectual property right is required to exercise the rights granted"
        + " by this License, you must include a text file with the Source Code distribution"
        + " titled \"LEGAL\" that describes the claim and the party making the claim in\n"
        + "sufficient detail that a recipient will know whom to contact.  If you obtain suc"
        + "h knowledge after you make any Modifications available as described in Section 4"
        + "(b), you shall promptly modify the LEGAL file in all copies you make available t"
        + "hereafter and shall take other steps (such as notifying appropriate mailing list"
        + "s or newsgroups) reasonably calculated to inform those who received the Licensed"
        + " Product from you that new knowledge has been obtained.\n"
        + "          ii. Contributor APIs.  If your Modifications include an application pr"
        + "ogramming interface (\"API\") and you have knowledge of patent licenses that are r"
        + "easonably necessary to implement that API, you must also include this informatio"
        + "n in the LEGAL file.\n"
        + "          iii. Representations.  You represent that, except as disclosed pursuan"
        + "t to 4(c)(i) above, you believe that any Modifications you distribute are your o"
        + "riginal creations and that you have sufficient rights to grant the rights convey"
        + "ed by this License.\n"
        + "\n"
        + "     d. Required Notices.  You must duplicate this License in any documentation "
        + "you provide along with the Source Code of any Modifications you create or to whi"
        + "ch you contribute, and which you distribute, wherever you describe recipients' r"
        + "ights relating to Licensed Product.  You must duplicate the notice contained in "
        + "Exhibit A (the \"Notice\") in each file of the Source Code of any copy you distrib"
        + "ute of the Licensed Product. If you created a Modification, you may add your nam"
        + "e as a Contributor to the Notice.  If it is not possible to put the Notice in a "
        + "particular Source Code file due to its structure, then you must include such Not"
        + "ice in a location (such as a relevant directory file) where a user would be like"
        + "ly to look for such a notice.  You may choose to offer, and charge a fee for, wa"
        + "rranty, support, indemnity or liability obligations to one or more recipients of"
        + " Licensed Product. However, you may do so only on your own behalf, and not on be"
        + "half of the Licensor or any Contributor.  You must make it clear that any such w"
        + "arranty, support, indemnity or liability obligation is offered by you alone, and"
        + " you hereby agree to indemnify the Licensor and every Contributor for any liabil"
        + "ity incurred by the Licensor or such Contributor as a result of warranty, suppor"
        + "t, indemnity or liability terms you offer.\n"
        + " \n"
        + "     e. Distribution of Executable Versions.  You may distribute Licensed Produc"
        + "t as an executable program under a license of your choice that may contain terms"
        + " different from this License provided (i) you have satisfied the requirements of"
        + " Sections 4(a) through 4(d) for that distribution, (ii) you include a conspicuou"
        + "s notice in the\n"
        + "executable version, related documentation and collateral materials stating that "
        + "the Source Code version of the Licensed Product is available under the terms of "
        + "this License, including a description of how and where you have fulfilled the ob"
        + "ligations of Section 4(b), and (iii) you make it clear that any terms that diffe"
        + "r from this License are offered by you alone, not by Licensor or any Contributor"
        + ".  You hereby agree to indemnify the Licensor and every Contributor for any liab"
        + "ility incurred by Licensor or such Contributor as a result of any terms you offe"
        + "r. \n"
        + " \n"
        + "     f. Distribution of Derivative Works.  You may create Derivative Works (e.g."
        + ", combinations of some or all of the Licensed Product with other code) and distr"
        + "ibute the Derivative Works as products under any other license you select, with "
        + "the proviso that the requirements of this License are fulfilled for those portio"
        + "ns of the Derivative Works that consist of the Licensed Product or any Modificat"
        + "ions thereto. \n"
        + " \n"
        + "5. Inability to Comply Due to Statute or Regulation.  If it is impossible for yo"
        + "u to comply with any of the terms of this License with respect to some or all of"
        + " the Licensed Product due to statute, judicial order, or regulation, then you mu"
        + "st (i) comply with the terms of this License to the maximum extent possible, (ii"
        + ") cite the statute or regulation that prohibits you from adhering to the License"
        + ", and (iii) describe the limitations and the code they affect. Such description "
        + "must be included in the LEGAL file described in Section 4(d), and must be includ"
        + "ed with all distributions of the Source Code.  Except to the extent prohibited b"
        + "y statute or regulation, such description must be sufficiently detailed for a re"
        + "cipient of ordinary skill at computer programming to be able to understand it. \n"
        + "\n"
        + "6. Application of This License.  This License applies to code to which Licensor "
        + "or Contributor has attached the Notice in Exhibit A, which is incorporated herei"
        + "n by this reference. \n"
        + " \n"
        + "7. Versions of This License.\n"
        + "     a. New Versions.  Licensor may publish from time to time revised and/or new"
        + " versions of the License. \n"
        + "\n"
        + "     b. Effect of New Versions.  Once Licensed Product has been published under "
        + "a particular version of the License, you may always continue to use it under the"
        + " terms of that version.  You may also choose to use such Licensed Product under "
        + "the terms of any subsequent version of the License published by Licensor.  No on"
        + "e other than Licensor has the right to modify the terms applicable to Licensed P"
        + "roduct created under this License.\n"
        + "\n"
        + "     c. Derivative Works of this License.  If you create or use a modified versi"
        + "on of this License, which you may do only in order to apply it to software that "
        + "is not already a Licensed Product under this License, you must rename your licen"
        + "se so that it is not confusingly similar to this License, and must make it clear"
        + " that your license contains terms that differ from this License.  In so naming y"
        + "our license, you may not use any trademark of Licensor or any Contributor.\n"
        + " \n"
        + "8. Disclaimer of Warranty.  LICENSED PRODUCT IS PROVIDED UNDER THIS LICENSE ON A"
        + "N AS IS BASIS, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDIN"
        + "G, WITHOUT LIMITATION, WARRANTIES THAT THE LICENSED PRODUCT IS FREE OF DEFECTS, "
        + "MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS"
        + " TO THE QUALITY AND PERFORMANCE OF THE LICENSED PRODUCT IS WITH YOU.  SHOULD LIC"
        + "ENSED PRODUCT PROVE DEFECTIVE IN ANY RESPECT, YOU (AND NOT THE LICENSOR OR ANY O"
        + "THER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR CORRECTI"
        + "ON.  THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. "
        + "NO USE OF LICENSED PRODUCT IS AUTHORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.\n"
        + " \n"
        + "9. Termination. \n"
        + "     a. Automatic Termination Upon Breach.  This license and the rights granted "
        + "hereunder will terminate automatically if you fail to comply with the terms here"
        + "in and fail to cure such breach within thirty (30) days of becoming aware of the"
        + " breach.  All sublicenses to the Licensed Product that are properly granted shal"
        + "l survive any termination of this license.  Provisions that, by their nature, mu"
        + "st remain in effect beyond the termination of this License, shall survive.\n"
        + " \n"
        + "     b. Termination Upon Assertion of Patent Infringement.  If you initiate liti"
        + "gation by asserting a patent infringement claim (excluding declaratory judgment "
        + "actions) against Licensor or a Contributor (Licensor or Contributor against whom"
        + " you file such an action is referred to herein as Respondent) alleging that Lice"
        + "nsed Product directly or indirectly infringes any patent, then any and all right"
        + "s granted by such Respondent to you under Sections 1 or 2 of this License shall "
        + "terminate prospectively upon sixty (60) days notice from Respondent (the \"Notice"
        + " Period\") unless within that Notice Period you either agree in writing (i) to pa"
        + "y Respondent a mutually agreeable reasonably royalty for your past or future use"
        + " of Licensed Product made by such Respondent, or (ii) withdraw your litigation c"
        + "laim with respect to Licensed Product against such Respondent.  If within said N"
        + "otice Period a reasonable royalty and payment arrangement are not mutually agree"
        + "d upon in writing by the parties or the litigation claim is not withdrawn, the r"
        + "ights granted by Licensor to you under Sections 1 and 2 automatically terminate "
        + "at the expiration of said Notice Period.\n"
        + " \n"
        + "     c. Reasonable Value of This License.  If you assert a patent infringement c"
        + "laim against Respondent alleging that Licensed Product directly or indirectly in"
        + "fringes any patent where such claim is resolved (such as by license or settlemen"
        + "t) prior to the initiation of patent infringement litigation, then the reasonabl"
        + "e value of the licenses\n"
        + "granted by said Respondent under Sections 1 and 2 shall be taken into account in"
        + " determining the amount or value of any payment or license.\n"
        + " \n"
        + "     d. No Retroactive Effect of Termination.  In the event of termination under"
        + " Sections 9(a) or 9(b) above, all end user license agreements (excluding license"
        + "s to distributors and resellers) that have been validly granted by you or any di"
        + "stributor hereunder prior to termination shall survive termination.\n"
        + " \n"
        + "10.  Limitation of Liability.  UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY,"
        + " WHETHER TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE, SHALL THE LICENSOR"
        + ", ANY CONTRIBUTOR, OR ANY DISTRIBUTOR OF LICENSED PRODUCT, OR ANY SUPPLIER OF AN"
        + "Y OF SUCH PARTIES, BE LIABLE TO ANY PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL"
        + ", OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAG"
        + "ES FOR LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY "
        + "AND ALL OTHER COMMERCIAL DAMAGES OR LOSSES, EVEN IF SUCH PARTY SHALL HAVE BEEN I"
        + "NFORMED OF THE POSSIBILITY OF SUCH DAMAGES.  THIS LIMITATION OF LIABILITY SHALL "
        + "NOT APPLY TO LIABILITY FOR DEATH OR PERSONAL INJURY\n"
        + "RESULTING FROM SUCH PARTYS NEGLIGENCE TO THE EXTENT APPLICABLE LAW PROHIBITS SUC"
        + "H LIMITATION.  SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF IN"
        + "CIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS EXCLUSION AND LIMITATION MAY NOT APPL"
        + "Y TO YOU. \n"
        + " \n"
        + "11.  Responsibility for Claims.  As between Licensor and Contributors, each part"
        + "y is responsible for claims and damages arising, directly or indirectly, out of "
        + "its utilization of rights under this License.  You agree to work with Licensor a"
        + "nd Contributors to distribute such responsibility on an equitable basis.  Nothin"
        + "g herein is intended or\n"
        + "shall be deemed to constitute any admission of liability.\n"
        + " \n"
        + "12.  U.S. Government End Users.  The Licensed Product is a commercial item, as t"
        + "hat term is defined in 48 C.F.R. 2.101 (Oct. 1995), consisting of commercial com"
        + "puter software and commercial computer software documentation, as such terms are"
        + " used in 48 C.F.R. 12.212 (Sept. 1995).  Consistent with 48 C.F.R. 12.212 and 48"
        + " C.F.R. 227.7202-1 through\n"
        + "227.7202-4 (June 1995), all U.S. Government End Users acquire Licensed Product w"
        + "ith only those rights set forth herein.\n"
        + " \n"
        + "13.  Miscellaneous.  This License represents the complete agreement concerning t"
        + "he subject matter hereof.  If any provision of this License is held to be unenfo"
        + "rceable, such provision shall be reformed only to the extent necessary to make i"
        + "t enforceable.  This License shall be governed by California law provisions (exc"
        + "ept to the extent applicable\n"
        + "law, if any, provides otherwise), excluding its conflict-of-law provisions.  You"
        + " expressly agree that any litigation relating to this license shall be subject t"
        + "o the jurisdiction of the Federal Courts of the Northern District of California "
        + "or the Superior Court of the County of Santa Clara, California (as appropriate),"
        + " with venue lying in Santa Clara County, California, with the losing party respo"
        + "nsible for costs including, without limitation, court costs and reasonable attor"
        + "neys fees and expenses.  The application of the United Nations Convention on Con"
        + "tracts for the International Sale of Goods is expressly excluded.  You and Licen"
        + "sor expressly waive any rights to a jury trial in any litigation concerning Lice"
        + "nsed Product or this License.  Any law or regulation that provides that the lang"
        + "uage of a contract shall be construed against the drafter shall not apply to thi"
        + "s License.\n"
        + " \n"
        + "14.  Definition of You in This License. You throughout this License, whether in "
        + "upper or lower case, means an individual or a legal entity exercising rights und"
        + "er, and complying with all of the terms of, this License or a future version of "
        + "this License issued under Section 7.  For legal entities, you includes any entit"
        + "y that controls, is\n"
        + "controlled by, or is under common control with you.  For purposes of this defini"
        + "tion, control means (i) the power, direct or indirect, to cause the direction or"
        + " management of such entity, whether by contract or otherwise, or (ii) ownership "
        + "of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ow"
        + "nership of such entity.\n"
        + " \n"
        + "15.  Glossary.  All defined terms in this License that are used in more than one"
        + " Section of this License are repeated here, in alphabetical order, for the conve"
        + "nience of the reader.  The Section of this License in which each defined term is"
        + " first used is shown in parentheses. \n"
        + " \n"
        + "Contributor:  Each person or entity who created or contributed to the creation o"
        + "f, and distributed, a Modification. (See Section 2)\n"
        + " \n"
        + "Derivative Works: That term as used in this License is defined under U.S. copyri"
        + "ght law.  (See Section 1(b))\n"
        + " \n"
        + "License:  This BitTorrent Open Source License.  (See first paragraph of License)\n"
        + " \n"
        + "Licensed Product:  Any BitTorrent Product licensed pursuant to this License.  Th"
        + "e term \"Licensed Product\" includes all previous Modifications from any Contribut"
        + "or that you receive.  (See first paragraph of License and Section 2)\n"
        + " \n"
        + "Licensor:  BitTorrent, Inc.  (See first paragraph of License)\n"
        + " \n"
        + "Modifications:  Any additions to or deletions from the substance or structure of"
        + " (i) a file containing Licensed Product, or (ii) any new file that contains any "
        + "part of Licensed Product.  (See Section 2)\n"
        + " \n"
        + "Notice:  The notice contained in Exhibit A.  (See Section 4(e))\n"
        + " \n"
        + "Source Code: The preferred form for making modifications to the Licensed Product"
        + ", including all modules contained therein, plus any associated interface definit"
        + "ion files, scripts used to control compilation and installation of an executable"
        + " program, or a list of differential comparisons against the Source Code of the L"
        + "icensed Product.  (See\n"
        + "Section 1(a))\n"
        + " \n"
        + "You:  This term is defined in Section 14 of this License.\n"
        + " \n"
        + " \n"
        + "EXHIBIT A\n"
        + " \n"
        + "The Notice below must appear in each file of the Source Code of any copy you dis"
        + "tribute of the Licensed Product or any hereto.  Contributors to any Modification"
        + "s may add their own copyright notices to identify their own contributions.\n"
        + " \n"
        + "License:\n"
        + " \n"
        + "The contents of this file are subject to the BitTorrent Open Source License Vers"
        + "ion 1.0 (the License).  You may not copy or use this file, in either source code"
        + " or executable form, except in compliance with the License.  You may obtain a co"
        + "py of the License at http://www.bittorrent.com/license/.\n"
        + " \n"
        + "Software distributed under the License is distributed on an AS IS basis, WITHOUT"
        + " WARRANTY OF ANY KIND, either express or implied.  See the License for the speci"
        + "fic language governing rights and limitations under the License.\n"
        + " \n"
; // the license text
    }
 
    
}
