package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:16:54Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: CUA_OPL_1_0.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class CUA_OPL_1_0 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return true; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "CUA-OPL-1.0"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "CUA Office Public License v1.0"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "CUA Office Public License Version 1.0\n"
        + "\n"
        + "1. Definitions.\n"
        + "\n"
        + "1.0.1. \"Commercial Use\" means distribution or otherwise making the Covered Code "
        + "available to a third party.\n"
        + "\n"
        + "1.1. \"Contributor\" means each entity that creates or contributes to the creation"
        + " of Modifications.\n"
        + "\n"
        + "1.2. \"Contributor Version\" means the combination of the Original Code, prior Mod"
        + "ifications used by a Contributor, and the Modifications made by that particular "
        + "Contributor.\n"
        + "\n"
        + "1.3. \"Covered Code\" means the Original Code or Modifications or the combination "
        + "of the Original Code and Modifications, in each case including portions thereof.\n"
        + "\n"
        + "1.4. \"Electronic Distribution Mechanism\" means a mechanism generally accepted in"
        + " the software development community for the electronic transfer of data.\n"
        + "\n"
        + "1.5. \"Executable\" means Covered Code in any form other than Source Code.\n"
        + "\n"
        + "1.6. \"Initial Developer\" means the individual or entity identified as the Initia"
        + "l Developer in the Source Code notice required by Exhibit A.\n"
        + "\n"
        + "1.7. \"Larger Work\" means a work which combines Covered Code or portions thereof "
        + "with code not governed by the terms of this License.\n"
        + "\n"
        + "1.8. \"License\" means this document.\n"
        + "\n"
        + "1.8.1. \"Licensable\" means having the right to grant, to the maximum extent possi"
        + "ble, whether at the time of the initial grant or subsequently acquired, any and "
        + "all of the rights conveyed herein.\n"
        + "\n"
        + "1.9. \"Modifications\" means any addition to or deletion from the substance or str"
        + "ucture of either the Original Code or any previous Modifications. When Covered C"
        + "ode is released as a series of files, a Modification is:\n"
        + "\n"
        + "     A. Any addition to or deletion from the contents of a file containing Origi"
        + "nal Code or previous Modifications.\n"
        + "\n"
        + "     B. Any new file that contains any part of the Original Code or previous Mod"
        + "ifications.\n"
        + "\n"
        + "1.10. \"Original Code\" means Source Code of computer software code which is descr"
        + "ibed in the Source Code notice required by Exhibit A as Original Code, and which"
        + ", at the time of its release under this License is not already Covered Code gove"
        + "rned by this License.\n"
        + "\n"
        + "1.10.1. \"Patent Claims\" means any patent claim(s), now owned or hereafter acquir"
        + "ed, including without limitation, method, process, and apparatus claims, in any "
        + "patent Licensable by grantor.\n"
        + "\n"
        + "1.11. \"Source Code\" means the preferred form of the Covered Code for making modi"
        + "fications to it, including all modules it contains, plus any associated interfac"
        + "e definition files, scripts used to control compilation and installation of an E"
        + "xecutable, or source code differential comparisons against either the Original C"
        + "ode or another well known, available Covered Code of the Contributor's choice. T"
        + "he Source Code can be in a compressed or archival form, provided the appropriate"
        + " decompression or de-archiving software is widely available for no charge.\n"
        + "\n"
        + "1.12. \"You\" (or \"Your\") means an individual or a legal entity exercising rights "
        + "under, and complying with all of the terms of, this License or a future version "
        + "of this License issued under Section 6.1. For legal entities, \"You\" includes any"
        + " entity which controls, is controlled by, or is under common control with You. F"
        + "or purposes of this definition, \"control\" means (a) the power, direct or indirec"
        + "t, to cause the direction or management of such entity, whether by contract or o"
        + "therwise, or (b) ownership of more than fifty percent (50%) of the outstanding s"
        + "hares or beneficial ownership of such entity.\n"
        + "\n"
        + "2. Source Code License.\n"
        + "\n"
        + "2.1. The Initial Developer Grant. The Initial Developer hereby grants You a worl"
        + "d-wide, royalty-free, non-exclusive license, subject to third party intellectual"
        + " property claims:\n"
        + "\n"
        + "     (a) under intellectual property rights (other than patent or trademark) Lic"
        + "ensable by Initial Developer to use, reproduce, modify, display, perform, sublic"
        + "ense and distribute the Original Code (or portions thereof) with or without Modi"
        + "fications, and/or as part of a Larger Work; and\n"
        + "\n"
        + "     (b) under Patents Claims infringed by the making, using or selling of Origi"
        + "nal Code, to make, have made, use, practice, sell, and offer for sale, and/or ot"
        + "herwise dispose of the Original Code (or portions thereof).\n"
        + "\n"
        + "     (c) the licenses granted in this Section 2.1(a) and (b) are effective on th"
        + "e date Initial Developer first distributes Original Code under the terms of this"
        + " License.\n"
        + "\n"
        + "     (d) Notwithstanding Section 2.1(b) above, no patent license is granted: 1) "
        + "for code that You delete from the Original Code; 2) separate from the Original C"
        + "ode; or 3) for infringements caused by: i) the modification of the Original Code"
        + " or ii) the combination of the Original Code with other software or devices.\n"
        + "\n"
        + "2.2. Contributor Grant. Subject to third party intellectual property claims, eac"
        + "h Contributor hereby grants You a world-wide, royalty-free, non-exclusive licens"
        + "e\n"
        + "\n"
        + "     (a) under intellectual property rights (other than patent or trademark) Lic"
        + "ensable by Contributor, to use, reproduce, modify, display, perform, sublicense "
        + "and distribute the Modifications created by such Contributor (or portions thereo"
        + "f) either on an unmodified basis, with other Modifications, as Covered Code and/"
        + "or as part of a Larger Work; and\n"
        + "\n"
        + "     (b) under Patent Claims infringed by the making, using, or selling of Modif"
        + "ications made by that Contributor either alone and/or in combination with its Co"
        + "ntributor Version (or portions of such combination), to make, use, sell, offer f"
        + "or sale, have made, and/or otherwise dispose of: 1) Modifications made by that C"
        + "ontributor (or portions thereof); and 2) the combination of Modifications made b"
        + "y that Contributor with its Contributor Version (or portions of such combination"
        + ").\n"
        + "\n"
        + "     (c) the licenses granted in Sections 2.2(a) and 2.2(b) are effective on the"
        + " date Contributor first makes Commercial Use of the Covered Code.\n"
        + "\n"
        + "     (d) Notwithstanding Section 2.2(b) above, no patent license is granted: 1) "
        + "for any code that Contributor has deleted from the Contributor Version; 2) separ"
        + "ate from the Contributor Version; 3) for infringements caused by: i) third party"
        + " modifications of Contributor Version or ii) the combination of Modifications ma"
        + "de by that Contributor with other software (except as part of the Contributor Ve"
        + "rsion) or other devices; or 4) under Patent Claims infringed by Covered Code in "
        + "the absence of Modifications made by that Contributor.\n"
        + "\n"
        + "3. Distribution Obligations.\n"
        + "\n"
        + "3.1. Application of License. The Modifications which You create or to which You "
        + "contribute are governed by the terms of this License, including without limitati"
        + "on Section 2.2. The Source Code version of Covered Code may be distributed only "
        + "under the terms of this License or a future version of this License released und"
        + "er Section 6.1, and You must include a copy of this License with every copy of t"
        + "he Source Code You distribute. You may not offer or impose any terms on any Sour"
        + "ce Code version that alters or restricts the applicable version of this License "
        + "or the recipients' rights hereunder. However, You may include an additional docu"
        + "ment offering the additional rights described in Section 3.5.\n"
        + "\n"
        + "3.2. Availability of Source Code. Any Modification which You create or to which "
        + "You contribute must be made available in Source Code form under the terms of thi"
        + "s License either on the same media as an Executable version or via an accepted E"
        + "lectronic Distribution Mechanism to anyone to whom you made an Executable versio"
        + "n available; and if made available via Electronic Distribution Mechanism, must r"
        + "emain available for at least twelve (12) months after the date it initially beca"
        + "me available, or at least six (6) months after a subsequent version of that part"
        + "icular Modification has been made available to such recipients. You are responsi"
        + "ble for ensuring that the Source Code version remains available even if the Elec"
        + "tronic Distribution Mechanism is maintained by a third party.\n"
        + "\n"
        + "3.3. Description of Modifications. You must cause all Covered Code to which You "
        + "contribute to contain a file documenting the changes You made to create that Cov"
        + "ered Code and the date of any change. You must include a prominent statement tha"
        + "t the Modification is derived, directly or indirectly, from Original Code provid"
        + "ed by the Initial Developer and including the name of the Initial Developer in ("
        + "a) the Source Code, and (b) in any notice in an Executable version or related do"
        + "cumentation in which You describe the origin or ownership of the Covered Code.\n"
        + "\n"
        + "3.4. Intellectual Property Matters\n"
        + "\n"
        + "     (a) Third Party Claims. If Contributor has knowledge that a license under a"
        + " third party's intellectual property rights is required to exercise the rights g"
        + "ranted by such Contributor under Sections 2.1 or 2.2, Contributor must include a"
        + " text file with the Source Code distribution titled \"LEGAL\" which describes the "
        + "claim and the party making the claim in sufficient detail that a recipient will "
        + "know whom to contact. If Contributor obtains such knowledge after the Modificati"
        + "on is made available as described in Section 3.2, Contributor shall promptly mod"
        + "ify the LEGAL file in all copies Contributor makes available thereafter and shal"
        + "l take other steps (such as notifying appropriate mailing lists or newsgroups) r"
        + "easonably calculated to inform those who received the Covered Code that new know"
        + "ledge has been obtained.\n"
        + "\n"
        + "     (b) Contributor APIs. If Contributor's Modifications include an application"
        + " programming interface and Contributor has knowledge of patent licenses which ar"
        + "e reasonably necessary to implement that API, Contributor must also include this"
        + " information in the LEGAL file.\n"
        + "\n"
        + "     (c) Representations. Contributor represents that, except as disclosed pursu"
        + "ant to Section 3.4(a) above, Contributor believes that Contributor's Modificatio"
        + "ns are Contributor's original creation(s) and/or Contributor has sufficient righ"
        + "ts to grant the rights conveyed by this License.\n"
        + "\n"
        + "3.5. Required Notices. You must duplicate the notice in Exhibit A in each file o"
        + "f the Source Code. If it is not possible to put such notice in a particular Sour"
        + "ce Code file due to its structure, then You must include such notice in a locati"
        + "on (such as a relevant directory) where a user would be likely to look for such "
        + "a notice. If You created one or more Modification(s) You may add your name as a "
        + "Contributor to the notice described in Exhibit A. You must also duplicate this L"
        + "icense in any documentation for the Source Code where You describe recipients' r"
        + "ights or ownership rights relating to Covered Code. You may choose to offer, and"
        + " to charge a fee for, warranty, support, indemnity or liability obligations to o"
        + "ne or more recipients of Covered Code. However, You may do so only on Your own b"
        + "ehalf, and not on behalf of the Initial Developer or any Contributor. You must m"
        + "ake it absolutely clear than any such warranty, support, indemnity or liability "
        + "obligation is offered by You alone, and You hereby agree to indemnify the Initia"
        + "l Developer and every Contributor for any liability incurred by the Initial Deve"
        + "loper or such Contributor as a result of warranty, support, indemnity or liabili"
        + "ty terms You offer.\n"
        + "\n"
        + "3.6. Distribution of Executable Versions. You may distribute Covered Code in Exe"
        + "cutable form only if the requirements of Section 3.1-3.5 have been met for that "
        + "Covered Code, and if You include a notice stating that the Source Code version o"
        + "f the Covered Code is available under the terms of this License, including a des"
        + "cription of how and where You have fulfilled the obligations of Section 3.2. The"
        + " notice must be conspicuously included in any notice in an Executable version, r"
        + "elated documentation or collateral in which You describe recipients' rights rela"
        + "ting to the Covered Code. You may distribute the Executable version of Covered C"
        + "ode or ownership rights under a license of Your choice, which may contain terms "
        + "different from this License, provided that You are in compliance with the terms "
        + "of this License and that the license for the Executable version does not attempt"
        + " to limit or alter the recipient's rights in the Source Code version from the ri"
        + "ghts set forth in this License. If You distribute the Executable version under a"
        + " different license You must make it absolutely clear that any terms which differ"
        + " from this License are offered by You alone, not by the Initial Developer or any"
        + " Contributor. You hereby agree to indemnify the Initial Developer and every Cont"
        + "ributor for any liability incurred by the Initial Developer or such Contributor "
        + "as a result of any such terms You offer.\n"
        + "\n"
        + "3.7. Larger Works. You may create a Larger Work by combining Covered Code with o"
        + "ther code not governed by the terms of this License and distribute the Larger Wo"
        + "rk as a single product. In such a case, You must make sure the requirements of t"
        + "his License are fulfilled for the Covered Code.\n"
        + "\n"
        + "4. Inability to Comply Due to Statute or Regulation.\n"
        + "If it is impossible for You to comply with any of the terms of this License with"
        + " respect to some or all of the Covered Code due to statute, judicial order, or r"
        + "egulation then You must: (a) comply with the terms of this License to the maximu"
        + "m extent possible; and (b) describe the limitations and the code they affect. Su"
        + "ch description must be included in the LEGAL file described in Section 3.4 and m"
        + "ust be included with all distributions of the Source Code. Except to the extent "
        + "prohibited by statute or regulation, such description must be sufficiently detai"
        + "led for a recipient of ordinary skill to be able to understand it.\n"
        + "\n"
        + "5. Application of this License.\n"
        + "This License applies to code to which the Initial Developer has attached the not"
        + "ice in Exhibit A and to related Covered Code.\n"
        + "\n"
        + "6. Versions of the License.\n"
        + "\n"
        + "6.1. New Versions. CUA Office Project may publish revised and/or new versions of"
        + " the License from time to time. Each version will be given a distinguishing vers"
        + "ion number.\n"
        + "\n"
        + "6.2. Effect of New Versions. Once Covered Code has been published under a partic"
        + "ular version of the License, You may always continue to use it under the terms o"
        + "f that version. You may also choose to use such Covered Code under the terms of "
        + "any subsequent version of the License published by CUA Office Project. No one ot"
        + "her than CUA Office Project has the right to modify the terms applicable to Cove"
        + "red Code created under this License.\n"
        + "\n"
        + "6.3. Derivative Works. If You create or use a modified version of this License ("
        + "which you may only do in order to apply it to code which is not already Covered "
        + "Code governed by this License), You must (a) rename Your license so that the phr"
        + "ases \"CUA Office\", \"CUA\", \"CUAPL\", or any confusingly similar phrase do not appe"
        + "ar in your license (except to note that your license differs from this License) "
        + "and (b) otherwise make it clear that Your version of the license contains terms "
        + "which differ from the CUA Office Public License. (Filling in the name of the Ini"
        + "tial Developer, Original Code or Contributor in the notice described in Exhibit "
        + "A shall not of themselves be deemed to be modifications of this License.)\n"
        + "\n"
        + "7. DISCLAIMER OF WARRANTY.\n"
        + "COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN \"AS IS\" BASIS, WITHOUT WARRANT"
        + "Y OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRA"
        + "NTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICUL"
        + "AR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE "
        + "OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY "
        + "RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COS"
        + "T OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY "
        + "CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUT"
        + "HORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.\n"
        + "\n"
        + "8. TERMINATION.\n"
        + "\n"
        + "8.1. This License and the rights granted hereunder will terminate automatically "
        + "if You fail to comply with terms herein and fail to cure such breach within 30 d"
        + "ays of becoming aware of the breach. All sublicenses to the Covered Code which a"
        + "re properly granted shall survive any termination of this License. Provisions wh"
        + "ich, by their nature, must remain in effect beyond the termination of this Licen"
        + "se shall survive.\n"
        + "\n"
        + "8.2. If You initiate litigation by asserting a patent infringement claim (exclud"
        + "ing declatory judgment actions) against Initial Developer or a Contributor (the "
        + "Initial Developer or Contributor against whom You file such action is referred t"
        + "o as \"Participant\") alleging that:\n"
        + "\n"
        + "(a) such Participant's Contributor Version directly or indirectly infringes any "
        + "patent, then any and all rights granted by such Participant to You under Section"
        + "s 2.1 and/or 2.2 of this License shall, upon 60 days notice from Participant ter"
        + "minate prospectively, unless if within 60 days after receipt of notice You eithe"
        + "r: (i) agree in writing to pay Participant a mutually agreeable reasonable royal"
        + "ty for Your past and future use of Modifications made by such Participant, or (i"
        + "i) withdraw Your litigation claim with respect to the Contributor Version agains"
        + "t such Participant. If within 60 days of notice, a reasonable royalty and paymen"
        + "t arrangement are not mutually agreed upon in writing by the parties or the liti"
        + "gation claim is not withdrawn, the rights granted by Participant to You under Se"
        + "ctions 2.1 and/or 2.2 automatically terminate at the expiration of the 60 day no"
        + "tice period specified above.\n"
        + "\n"
        + "(b) any software, hardware, or device, other than such Participant's Contributor"
        + " Version, directly or indirectly infringes any patent, then any rights granted t"
        + "o You by such Participant under Sections 2.1(b) and 2.2(b) are revoked effective"
        + " as of the date You first made, used, sold, distributed, or had made, Modificati"
        + "ons made by that Participant.\n"
        + "\n"
        + "8.3. If You assert a patent infringement claim against Participant alleging that"
        + " such Participant's Contributor Version directly or indirectly infringes any pat"
        + "ent where such claim is resolved (such as by license or settlement) prior to the"
        + " initiation of patent infringement litigation, then the reasonable value of the "
        + "licenses granted by such Participant under Sections 2.1 or 2.2 shall be taken in"
        + "to account in determining the amount or value of any payment or license.\n"
        + "\n"
        + "8.4. In the event of termination under Sections 8.1 or 8.2 above, all end user l"
        + "icense agreements (excluding distributors and resellers) which have been validly"
        + " granted by You or any distributor hereunder prior to termination shall survive "
        + "termination.\n"
        + "\n"
        + "9. LIMITATION OF LIABILITY.\n"
        + "UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER TORT (INCLUDING NEGLIG"
        + "ENCE), CONTRACT, OR OTHERWISE, SHALL YOU, THE INITIAL DEVELOPER, ANY OTHER CONTR"
        + "IBUTOR, OR ANY DISTRIBUTOR OF COVERED CODE, OR ANY SUPPLIER OF ANY OF SUCH PARTI"
        + "ES, BE LIABLE TO ANY PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENT"
        + "IAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF "
        + "GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER C"
        + "OMMERCIAL DAMAGES OR LOSSES, EVEN IF SUCH PARTY SHALL HAVE BEEN INFORMED OF THE "
        + "POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION OF LIABILITY SHALL NOT APPLY TO LIA"
        + "BILITY FOR DEATH OR PERSONAL INJURY RESULTING FROM SUCH PARTY'S NEGLIGENCE TO TH"
        + "E EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION. SOME JURISDICTIONS DO NOT ALL"
        + "OW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS E"
        + "XCLUSION AND LIMITATION MAY NOT APPLY TO YOU.\n"
        + "\n"
        + "10. U.S. GOVERNMENT END USERS.\n"
        + "The Covered Code is a \"commercial item,\" as that term is defined in 48 C.F.R. 2."
        + "101 (Oct. 1995), consisting of \"commercial computer software\" and \"commercial co"
        + "mputer software documentation,\" as such terms are used in 48 C.F.R. 12.212 (Sept"
        + ". 1995). Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through 227.7"
        + "202-4 (June 1995), all U.S. Government End Users acquire Covered Code with only "
        + "those rights set forth herein.\n"
        + "\n"
        + "11. MISCELLANEOUS.\n"
        + "This License represents the complete agreement concerning subject matter hereof."
        + " If any provision of this License is held to be unenforceable, such provision sh"
        + "all be reformed only to the extent necessary to make it enforceable. This Licens"
        + "e shall be governed by California law provisions (except to the extent applicabl"
        + "e law, if any, provides otherwise), excluding its conflict-of-law provisions. Wi"
        + "th respect to disputes in which at least one party is a citizen of, or an entity"
        + " chartered or registered to do business in the United States of America, any lit"
        + "igation relating to this License shall be subject to the jurisdiction of the Fed"
        + "eral Courts of the Northern District of California, with venue lying in Santa Cl"
        + "ara County, California, with the losing party responsible for costs, including w"
        + "ithout limitation, court costs and reasonable attorneys' fees and expenses. The "
        + "application of the United Nations Convention on Contracts for the International "
        + "Sale of Goods is expressly excluded. Any law or regulation which provides that t"
        + "he language of a contract shall be construed against the drafter shall not apply"
        + " to this License.\n"
        + "\n"
        + "12. RESPONSIBILITY FOR CLAIMS.\n"
        + "As between Initial Developer and the Contributors, each party is responsible for"
        + " claims and damages arising, directly or indirectly, out of its utilization of r"
        + "ights under this License and You agree to work with Initial Developer and Contri"
        + "butors to distribute such responsibility on an equitable basis. Nothing herein i"
        + "s intended or shall be deemed to constitute any admission of liability.\n"
        + "\n"
        + "13. MULTIPLE-LICENSED CODE.\n"
        + "Initial Developer may designate portions of the Covered Code as \"Multiple-Licens"
        + "ed\". \"Multiple-Licensed\" means that the Initial Developer permits you to utilize"
        + " portions of the Covered Code under Your choice of the NPL or the alternative li"
        + "censes, if any, specified by the Initial Developer in the file described in Exhi"
        + "bit A.\n"
        + "\n"
        + "EXHIBIT A - CUA Office Public License.\n"
        + "\n"
        + "\"The contents of this file are subject to the CUA Office Public License Version "
        + "1.0 (the \"License\"); you may not use this file except in compliance with the Lic"
        + "ense. You may obtain a copy of the License at http://cuaoffice.sourceforge.net/\n"
        + "\n"
        + "Software distributed under the License is distributed on an \"AS IS\" basis, WITHO"
        + "UT WARRANTY OF ANY KIND, either express or implied. See the License for the spec"
        + "ific language governing rights and limitations under the License.\n"
        + "\n"
        + "The Original Code is ______________________________________.\n"
        + "\n"
        + "The Initial Developer of the Original Code is ________________________. Portions"
        + " created by ______________________ are Copyright (C) ______ ____________________"
        + "___. All Rights Reserved.\n"
        + "\n"
        + "Contributor(s): ______________________________________.\n"
        + "\n"
        + "Alternatively, the contents of this file may be used under the terms of the ____"
        + "_ license (the \"[___] License\"), in which case the provisions of [______] Licens"
        + "e are applicable instead of those above. If you wish to allow use of your versio"
        + "n of this file only under the terms of the [____] License and not to allow other"
        + "s to use your version of this file under the CUAPL, indicate your decision by de"
        + "leting the provisions above and replace them with the notice and other provision"
        + "s required by the [___] License. If you do not delete the provisions above, a re"
        + "cipient may use your version of this file under either the CUAPL or the [___] Li"
        + "cense.\"\n"
        + "\n"
        + "[NOTE: The text of this Exhibit A may differ slightly from the text of the notic"
        + "es in the Source Code files of the Original Code. You should use the text of thi"
        + "s Exhibit A rather than the text found in the Original Code Source Code for Your"
        + " Modifications.]\n"
; // the license text
    }
 
    
}
