package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:17:09Z
 * LicenseName: AGPL-3.0+
 * FileName: EUPL_1_1.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class EUPL_1_1 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return true; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "EUPL-1.1"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "European Union Public License 1.1"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "European Union Public Licence V. 1.1\n"
        + "\n"
        + "EUPL (c) the European Community 2007\n"
        + "\n"
        + "This European Union Public Licence (the \"EUPL\") applies to the Work or Software "
        + "(as defined below) which is provided under the terms of this Licence. Any use of"
        + " the Work, other than as authorised under this Licence is prohibited (to the ext"
        + "ent such use is covered by a right of the copyright holder of the Work).\n"
        + "\n"
        + "The Original Work is provided under the terms of this Licence when the Licensor "
        + "(as defined below) has placed the following notice immediately following the cop"
        + "yright notice for the Original Work: \n"
        + "\n"
        + "     Licensed under the EUPL V.1.1 \n"
        + "\n"
        + "or has expressed by any other mean his willingness to license under the EUPL.\n"
        + "\n"
        + "1. Definitions\n"
        + "\n"
        + "In this Licence, the following terms have the following meaning:\n"
        + "\n"
        + "     - The Licence: this Licence.\n"
        + "\n"
        + "     - The Original Work or the Software: the software distributed and/or commun"
        + "icated by the Licensor under this Licence, available as Source Code and also as "
        + "Executable Code as the case may be.\n"
        + "\n"
        + "     - Derivative Works: the works or software that could be created by the Lice"
        + "nsee, based upon the Original Work or modifications thereof. This Licence does n"
        + "ot define the extent of modification or dependence on the Original Work required"
        + " in order to classify a work as a Derivative Work; this extent is determined by "
        + "copyright law applicable in the country mentioned in Article 15.\n"
        + "\n"
        + "     - The Work: the Original Work and/or its Derivative Works.\n"
        + "\n"
        + "     - The Source Code: the human-readable form of the Work which is the most co"
        + "nvenient for people to study and modify.\n"
        + "\n"
        + "     - The Executable Code: any code which has generally been compiled and which"
        + " is meant to be interpreted by a computer as a program.\n"
        + "\n"
        + "     - The Licensor: the natural or legal person that distributes and/or communi"
        + "cates the Work under the Licence.\n"
        + "\n"
        + "     - Contributor(s): any natural or legal person who modifies the Work under t"
        + "he Licence, or otherwise contributes to the creation of a Derivative Work.\n"
        + "\n"
        + "     - The Licensee or \"You\": any natural or legal person who makes any usage of"
        + " the Software under the terms of the Licence.\n"
        + "\n"
        + "     - Distribution and/or Communication: any act of selling, giving, lending, r"
        + "enting, distributing, communicating, transmitting, or otherwise making available"
        + ", on-line or off-line, copies of the Work or providing access to its essential f"
        + "unctionalities at the disposal of any other natural or legal person.\n"
        + "\n"
        + "2. Scope of the rights granted by the Licence\n"
        + "\n"
        + "The Licensor hereby grants You a world-wide, royalty-free, non-exclusive, sublic"
        + "ensable licence to do the following, for the duration of copyright vested in the"
        + " Original Work:\n"
        + "\n"
        + "     - use the Work in any circumstance and for all usage, \n"
        + "\n"
        + "     - reproduce the Work, \n"
        + "\n"
        + "     - modify the Original Work, and make Derivative Works based upon the Work, \n"
        + "\n"
        + "     - communicate to the public, including the right to make available or displ"
        + "ay the Work or copies thereof to the public and perform publicly, as the case ma"
        + "y be, the Work, \n"
        + "\n"
        + "     - distribute the Work or copies thereof, \n"
        + "\n"
        + "     - lend and rent the Work or copies thereof, \n"
        + "\n"
        + "     - sub-license rights in the Work or copies thereof.\n"
        + "\n"
        + "Those rights can be exercised on any media, supports and formats, whether now kn"
        + "own or later invented, as far as the applicable law permits so.\n"
        + "\n"
        + "In the countries where moral rights apply, the Licensor waives his right to exer"
        + "cise his moral right to the extent allowed by law in order to make effective the"
        + " licence of the economic rights here above listed.\n"
        + "\n"
        + "The Licensor grants to the Licensee royalty-free, non exclusive usage rights to "
        + "any patents held by the Licensor, to the extent necessary to make use of the rig"
        + "hts granted on the Work under this Licence.\n"
        + "\n"
        + "3. Communication of the Source Code\n"
        + "\n"
        + "The Licensor may provide the Work either in its Source Code form, or as Executab"
        + "le Code. If the Work is provided as Executable Code, the Licensor provides in ad"
        + "dition a machine-readable copy of the Source Code of the Work along with each co"
        + "py of the Work that the Licensor distributes or indicates, in a notice following"
        + " the copyright notice attached to the Work, a repository where the Source Code i"
        + "s easily and freely accessible for as long as the Licensor continues to distribu"
        + "te and/or communicate the Work.\n"
        + "\n"
        + "4. Limitations on copyright\n"
        + "\n"
        + "Nothing in this Licence is intended to deprive the Licensee of the benefits from"
        + " any exception or limitation to the exclusive rights of the rights owners in the"
        + " Original Work or Software, of the exhaustion of those rights or of other applic"
        + "able limitations thereto.\n"
        + "\n"
        + "5. Obligations of the Licensee\n"
        + "\n"
        + "The grant of the rights mentioned above is subject to some restrictions and obli"
        + "gations imposed on the Licensee. Those obligations are the following:\n"
        + "\n"
        + "Attribution right: the Licensee shall keep intact all copyright, patent or trade"
        + "marks notices and all notices that refer to the Licence and to the disclaimer of"
        + " warranties. The Licensee must include a copy of such notices and a copy of the "
        + "Licence with every copy of the Work he/she distributes and/or communicates. The "
        + "Licensee must cause any Derivative Work to carry prominent notices stating that "
        + "the Work has been modified and the date of modification.\n"
        + "\n"
        + "Copyleft clause: If the Licensee distributes and/or communicates copies of the O"
        + "riginal Works or Derivative Works based upon the Original Work, this Distributio"
        + "n and/or Communication will be done under the terms of this Licence or of a late"
        + "r version of this Licence unless the Original Work is expressly distributed only"
        + " under this version of the Licence. The Licensee (becoming Licensor) cannot offe"
        + "r or impose any additional terms or conditions on the Work or Derivative Work th"
        + "at alter or restrict the terms of the Licence.\n"
        + "\n"
        + "Compatibility clause: If the Licensee Distributes and/or Communicates Derivative"
        + " Works or copies thereof based upon both the Original Work and another work lice"
        + "nsed under a Compatible Licence, this Distribution and/or Communication can be d"
        + "one under the terms of this Compatible Licence. For the sake of this clause, �Co"
        + "mpatible Licence,� refers to the licences listed in the appendix attached to thi"
        + "s Licence. Should the Licensee’s obligations under the Compatible Licence confli"
        + "ct with his/her obligations under this Licence, the obligations of the Compatibl"
        + "e Licence shall prevail.\n"
        + "\n"
        + "Provision of Source Code: When distributing and/or communicating copies of the W"
        + "ork, the Licensee will provide a machine-readable copy of the Source Code or ind"
        + "icate a repository where this Source will be easily and freely available for as "
        + "long as the Licensee continues to distribute and/or communicate the Work.\n"
        + "\n"
        + "Legal Protection: This Licence does not grant permission to use the trade names,"
        + " trademarks, service marks, or names of the Licensor, except as required for rea"
        + "sonable and customary use in describing the origin of the Work and reproducing t"
        + "he content of the copyright notice.\n"
        + "\n"
        + "6. Chain of Authorship\n"
        + "\n"
        + "The original Licensor warrants that the copyright in the Original Work granted h"
        + "ereunder is owned by him/her or licensed to him/her and that he/she has the powe"
        + "r and authority to grant the Licence.\n"
        + "\n"
        + "Each Contributor warrants that the copyright in the modifications he/she brings "
        + "to the Work are owned by him/her or licensed to him/her and that he/she has the "
        + "power and authority to grant the Licence.\n"
        + "\n"
        + "Each time You accept the Licence, the original Licensor and subsequent Contribut"
        + "ors grant You a licence to their contributions to the Work, under the terms of t"
        + "his Licence.\n"
        + "\n"
        + "7. Disclaimer of Warranty\n"
        + "\n"
        + "The Work is a work in progress, which is continuously improved by numerous contr"
        + "ibutors. It is not a finished work and may therefore contain defects or \"bugs\" i"
        + "nherent to this type of software development.\n"
        + "\n"
        + "For the above reason, the Work is provided under the Licence on an \"as is\" basis"
        + " and without warranties of any kind concerning the Work, including without limit"
        + "ation merchantability, fitness for a particular purpose, absence of defects or e"
        + "rrors, accuracy, non-infringement of intellectual property rights other than cop"
        + "yright as stated in Article 6 of this Licence.\n"
        + "\n"
        + "This disclaimer of warranty is an essential part of the Licence and a condition "
        + "for the grant of any rights to the Work.\n"
        + "\n"
        + "8. Disclaimer of Liability\n"
        + "\n"
        + "Except in the cases of wilful misconduct or damages directly caused to natural p"
        + "ersons, the Licensor will in no event be liable for any direct or indirect, mate"
        + "rial or moral, damages of any kind, arising out of the Licence or of the use of "
        + "the Work, including without limitation, damages for loss of goodwill, work stopp"
        + "age, computer failure or malfunction, loss of data or any commercial damage, eve"
        + "n if the Licensor has been advised of the possibility of such damage. However, t"
        + "he Licensor will be liable under statutory product liability laws as far such la"
        + "ws apply to the Work.\n"
        + "\n"
        + "9. Additional agreements\n"
        + "\n"
        + "While distributing the Original Work or Derivative Works, You may choose to conc"
        + "lude an additional agreement to offer, and charge a fee for, acceptance of suppo"
        + "rt, warranty, indemnity, or other liability obligations and/or services consiste"
        + "nt with this Licence. However, in accepting such obligations, You may act only o"
        + "n your own behalf and on your sole responsibility, not on behalf of the original"
        + " Licensor or any other Contributor, and only if You agree to indemnify, defend, "
        + "and hold each Contributor harmless for any liability incurred by, or claims asse"
        + "rted against such Contributor by the fact You have accepted any such warranty or"
        + " additional liability.\n"
        + "\n"
        + "10. Acceptance of the Licence\n"
        + "\n"
        + "The provisions of this Licence can be accepted by clicking on an icon \"I agree\" "
        + "placed under the bottom of a window displaying the text of this Licence or by af"
        + "firming consent in any other similar way, in accordance with the rules of applic"
        + "able law. Clicking on that icon indicates your clear and irrevocable acceptance "
        + "of this Licence and all of its terms and conditions.\n"
        + "\n"
        + "Similarly, you irrevocably accept this Licence and all of its terms and conditio"
        + "ns by exercising any rights granted to You by Article 2 of this Licence, such as"
        + " the use of the Work, the creation by You of a Derivative Work or the Distributi"
        + "on and/or Communication by You of the Work or copies thereof.\n"
        + "\n"
        + "11. Information to the public\n"
        + "\n"
        + "In case of any Distribution and/or Communication of the Work by means of electro"
        + "nic communication by You (for example, by offering to download the Work from a r"
        + "emote location) the distribution channel or media (for example, a website) must "
        + "at least provide to the public the information requested by the applicable law r"
        + "egarding the Licensor, the Licence and the way it may be accessible, concluded, "
        + "stored and reproduced by the Licensee.\n"
        + "\n"
        + "12. Termination of the Licence\n"
        + "\n"
        + "The Licence and the rights granted hereunder will terminate automatically upon a"
        + "ny breach by the Licensee of the terms of the Licence. Such a termination will n"
        + "ot terminate the licences of any person who has received the Work from the Licen"
        + "see under the Licence, provided such persons remain in full compliance with the "
        + "Licence.\n"
        + "\n"
        + "13. Miscellaneous\n"
        + "\n"
        + "Without prejudice of Article 9 above, the Licence represents the complete agreem"
        + "ent between the Parties as to the Work licensed hereunder.\n"
        + "\n"
        + "If any provision of the Licence is invalid or unenforceable under applicable law"
        + ", this will not affect the validity or enforceability of the Licence as a whole."
        + " Such provision will be construed and/or reformed so as necessary to make it val"
        + "id and enforceable.\n"
        + "\n"
        + "The European Commission may publish other linguistic versions and/or new version"
        + "s of this Licence, so far this is required and reasonable, without reducing the "
        + "scope of the rights granted by the Licence. New versions of the Licence will be "
        + "published with a unique version number.\n"
        + "\n"
        + "All linguistic versions of this Licence, approved by the European Commission, ha"
        + "ve identical value. Parties can take advantage of the linguistic version of thei"
        + "r choice.\n"
        + "\n"
        + "14. Jurisdiction\n"
        + "\n"
        + "Any litigation resulting from the interpretation of this License, arising betwee"
        + "n the European Commission, as a Licensor, and any Licensee, will be subject to t"
        + "he jurisdiction of the Court of Justice of the European Communities, as laid dow"
        + "n in article 238 of the Treaty establishing the European Community.\n"
        + "\n"
        + "Any litigation arising between Parties, other than the European Commission, and "
        + "resulting from the interpretation of this License, will be subject to the exclus"
        + "ive jurisdiction of the competent court where the Licensor resides or conducts i"
        + "ts primary business.\n"
        + "\n"
        + "15. Applicable Law\n"
        + "\n"
        + "This Licence shall be governed by the law of the European Union country where th"
        + "e Licensor resides or has his registered office.\n"
        + "\n"
        + "This licence shall be governed by the Belgian law if:\n"
        + "\n"
        + "     - a litigation arises between the European Commission, as a Licensor, and a"
        + "ny Licensee; \n"
        + "\n"
        + "     - the Licensor, other than the European Commission, has no residence or reg"
        + "istered office inside a European Union country.\n"
        + "\n"
        + "\n"
        + "\n"
        + "Appendix\n"
        + "\n"
        + "\"Compatible Licences\" according to article 5 EUPL are: \n"
        + "\n"
        + "     - GNU General Public License (GNU GPL) v. 2 \n"
        + "     - Open Software License (OSL) v. 2.1, v. 3.0 \n"
        + "     - Common Public License v. 1.0 \n"
        + "     - Eclipse Public License v. 1.0 \n"
        + "     - Cecill v. 2.0\n"
; // the license text
    }
 
    
}
