package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:17:50Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: MPL_1_1.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class MPL_1_1 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return true; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "MPL-1.1"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "Mozilla Public License 1.1 "; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "Mozilla Public License Version 1.1\n"
        + "\n"
        + "1. Definitions.\n"
        + "\n"
        + "     1.0.1. \"Commercial Use\" means distribution or otherwise making the Covered "
        + "Code available to a third party.\n"
        + "\n"
        + "     1.1. \"Contributor\" means each entity that creates or contributes to the cre"
        + "ation of Modifications.\n"
        + "\n"
        + "     1.2. \"Contributor Version\" means the combination of the Original Code, prio"
        + "r Modifications used by a Contributor, and the Modifications made by that partic"
        + "ular Contributor.\n"
        + "\n"
        + "     1.3. \"Covered Code\" means the Original Code or Modifications or the combina"
        + "tion of the Original Code and Modifications, in each case including portions the"
        + "reof.\n"
        + "\n"
        + "     1.4. \"Electronic Distribution Mechanism\" means a mechanism generally accept"
        + "ed in the software development community for the electronic transfer of data.\n"
        + "\n"
        + "     1.5. \"Executable\" means Covered Code in any form other than Source Code.\n"
        + "\n"
        + "     1.6. \"Initial Developer\" means the individual or entity identified as the I"
        + "nitial Developer in the Source Code notice required by Exhibit A.\n"
        + "\n"
        + "     1.7. \"Larger Work\" means a work which combines Covered Code or portions the"
        + "reof with code not governed by the terms of this License.\n"
        + "\n"
        + "     1.8. \"License\" means this document.\n"
        + "\n"
        + "     1.8.1. \"Licensable\" means having the right to grant, to the maximum extent "
        + "possible, whether at the time of the initial grant or subsequently acquired, any"
        + " and all of the rights conveyed herein.\n"
        + "\n"
        + "     1.9. \"Modifications\" means any addition to or deletion from the substance o"
        + "r structure of either the Original Code or any previous Modifications. When Cove"
        + "red Code is released as a series of files, a Modification is:\n"
        + "Any addition to or deletion from the contents of a file containing Original Code"
        + " or previous Modifications.\n"
        + "Any new file that contains any part of the Original Code or previous Modificatio"
        + "ns.\n"
        + "\n"
        + "     1.10. \"Original Code\" means Source Code of computer software code which is "
        + "described in the Source Code notice required by Exhibit A as Original Code, and "
        + "which, at the time of its release under this License is not already Covered Code"
        + " governed by this License.\n"
        + "\n"
        + "     1.10.1. \"Patent Claims\" means any patent claim(s), now owned or hereafter a"
        + "cquired, including without limitation, method, process, and apparatus claims, in"
        + " any patent Licensable by grantor.\n"
        + "\n"
        + "     1.11. \"Source Code\" means the preferred form of the Covered Code for making"
        + " modifications to it, including all modules it contains, plus any associated int"
        + "erface definition files, scripts used to control compilation and installation of"
        + " an Executable, or source code differential comparisons against either the Origi"
        + "nal Code or another well known, available Covered Code of the Contributor's choi"
        + "ce. The Source Code can be in a compressed or archival form, provided the approp"
        + "riate decompression or de-archiving software is widely available for no charge.\n"
        + "\n"
        + "     1.12. \"You\" (or \"Your\") means an individual or a legal entity exercising ri"
        + "ghts under, and complying with all of the terms of, this License or a future ver"
        + "sion of this License issued under Section 6.1. For legal entities, \"You\" include"
        + "s any entity which controls, is controlled by, or is under common control with Y"
        + "ou. For purposes of this definition, \"control\" means (a) the power, direct or in"
        + "direct, to cause the direction or management of such entity, whether by contract"
        + " or otherwise, or (b) ownership of more than fifty percent (50%) of the outstand"
        + "ing shares or beneficial ownership of such entity.\n"
        + "\n"
        + "2. Source Code License.\n"
        + "\n"
        + "     2.1. The Initial Developer Grant. The Initial Developer hereby grants You a"
        + " world-wide, royalty-free, non-exclusive license, subject to third party intelle"
        + "ctual property claims:\n"
        + "\n"
        + "          a. under intellectual property rights (other than patent or trademark)"
        + " Licensable by Initial Developer to use, reproduce, modify, display, perform, su"
        + "blicense and distribute the Original Code (or portions thereof) with or without "
        + "Modifications, and/or as part of a Larger Work; and\n"
        + "          b. under Patents Claims infringed by the making, using or selling of O"
        + "riginal Code, to make, have made, use, practice, sell, and offer for sale, and/o"
        + "r otherwise dispose of the Original Code (or portions thereof).\n"
        + "          c. the licenses granted in this Section 2.1 (a) and (b) are effective "
        + "on the date Initial Developer first distributes Original Code under the terms of"
        + " this License.\n"
        + "          d. Notwithstanding Section 2.1 (b) above, no patent license is granted"
        + ": 1) for code that You delete from the Original Code; 2) separate from the Origi"
        + "nal Code; or 3) for infringements caused by: i) the modification of the Original"
        + " Code or ii) the combination of the Original Code with other software or devices"
        + ".\n"
        + "\n"
        + "     2.2. Contributor Grant. Subject to third party intellectual property claims"
        + ", each Contributor hereby grants You a world-wide, royalty-free, non-exclusive l"
        + "icense\n"
        + "\n"
        + "          a. under intellectual property rights (other than patent or trademark)"
        + " Licensable by Contributor, to use, reproduce, modify, display, perform, sublice"
        + "nse and distribute the Modifications created by such Contributor (or portions th"
        + "ereof) either on an unmodified basis, with other Modifications, as Covered Code "
        + "and/or as part of a Larger Work; and\n"
        + "          b. under Patent Claims infringed by the making, using, or selling of M"
        + "odifications made by that Contributor either alone and/or in combination with it"
        + "s Contributor Version (or portions of such combination), to make, use, sell, off"
        + "er for sale, have made, and/or otherwise dispose of: 1) Modifications made by th"
        + "at Contributor (or portions thereof); and 2) the combination of Modifications ma"
        + "de by that Contributor with its Contributor Version (or portions of such combina"
        + "tion).\n"
        + "          c. the licenses granted in Sections 2.2 (a) and 2.2 (b) are effective "
        + "on the date Contributor first makes Commercial Use of the Covered Code.\n"
        + "          d. Notwithstanding Section 2.2 (b) above, no patent license is granted"
        + ": 1) for any code that Contributor has deleted from the Contributor Version; 2) "
        + "separate from the Contributor Version; 3) for infringements caused by: i) third "
        + "party modifications of Contributor Version or ii) the combination of Modificatio"
        + "ns made by that Contributor with other software (except as part of the Contribut"
        + "or Version) or other devices; or 4) under Patent Claims infringed by Covered Cod"
        + "e in the absence of Modifications made by that Contributor.\n"
        + "\n"
        + "3. Distribution Obligations.\n"
        + "\n"
        + "     3.1. Application of License. The Modifications which You create or to which"
        + " You contribute are governed by the terms of this License, including without lim"
        + "itation Section 2.2. The Source Code version of Covered Code may be distributed "
        + "only under the terms of this License or a future version of this License release"
        + "d under Section 6.1, and You must include a copy of this License with every copy"
        + " of the Source Code You distribute. You may not offer or impose any terms on any"
        + " Source Code version that alters or restricts the applicable version of this Lic"
        + "ense or the recipients' rights hereunder. However, You may include an additional"
        + " document offering the additional rights described in Section 3.5.\n"
        + "\n"
        + "     3.2. Availability of Source Code. Any Modification which You create or to w"
        + "hich You contribute must be made available in Source Code form under the terms o"
        + "f this License either on the same media as an Executable version or via an accep"
        + "ted Electronic Distribution Mechanism to anyone to whom you made an Executable v"
        + "ersion available; and if made available via Electronic Distribution Mechanism, m"
        + "ust remain available for at least twelve (12) months after the date it initially"
        + " became available, or at least six (6) months after a subsequent version of that"
        + " particular Modification has been made available to such recipients. You are res"
        + "ponsible for ensuring that the Source Code version remains available even if the"
        + " Electronic Distribution Mechanism is maintained by a third party.\n"
        + "\n"
        + "     3.3. Description of Modifications. You must cause all Covered Code to which"
        + " You contribute to contain a file documenting the changes You made to create tha"
        + "t Covered Code and the date of any change. You must include a prominent statemen"
        + "t that the Modification is derived, directly or indirectly, from Original Code p"
        + "rovided by the Initial Developer and including the name of the Initial Developer"
        + " in (a) the Source Code, and (b) in any notice in an Executable version or relat"
        + "ed documentation in which You describe the origin or ownership of the Covered Co"
        + "de.\n"
        + "\n"
        + "     3.4. Intellectual Property Matters\n"
        + "\n"
        + "          (a) Third Party Claims\n"
        + "          If Contributor has knowledge that a license under a third party's inte"
        + "llectual property rights is required to exercise the rights granted by such Cont"
        + "ributor under Sections 2.1 or 2.2, Contributor must include a text file with the"
        + " Source Code distribution titled \"LEGAL\" which describes the claim and the party"
        + " making the claim in sufficient detail that a recipient will know whom to contac"
        + "t. If Contributor obtains such knowledge after the Modification is made availabl"
        + "e as described in Section 3.2, Contributor shall promptly modify the LEGAL file "
        + "in all copies Contributor makes available thereafter and shall take other steps "
        + "(such as notifying appropriate mailing lists or newsgroups) reasonably calculate"
        + "d to inform those who received the Covered Code that new knowledge has been obta"
        + "ined.\n"
        + "\n"
        + "          (b) Contributor APIs\n"
        + "          If Contributor's Modifications include an application programming inte"
        + "rface and Contributor has knowledge of patent licenses which are reasonably nece"
        + "ssary to implement that API, Contributor must also include this information in t"
        + "he LEGAL file.\n"
        + "\n"
        + "          (c) Representations.\n"
        + "          Contributor represents that, except as disclosed pursuant to Section 3"
        + ".4 (a) above, Contributor believes that Contributor's Modifications are Contribu"
        + "tor's original creation(s) and/or Contributor has sufficient rights to grant the"
        + " rights conveyed by this License.\n"
        + "\n"
        + "     3.5. Required Notices. You must duplicate the notice in Exhibit A in each f"
        + "ile of the Source Code. If it is not possible to put such notice in a particular"
        + " Source Code file due to its structure, then You must include such notice in a l"
        + "ocation (such as a relevant directory) where a user would be likely to look for "
        + "such a notice. If You created one or more Modification(s) You may add your name "
        + "as a Contributor to the notice described in Exhibit A. You must also duplicate t"
        + "his License in any documentation for the Source Code where You describe recipien"
        + "ts' rights or ownership rights relating to Covered Code. You may choose to offer"
        + ", and to charge a fee for, warranty, support, indemnity or liability obligations"
        + " to one or more recipients of Covered Code. However, You may do so only on Your "
        + "own behalf, and not on behalf of the Initial Developer or any Contributor. You m"
        + "ust make it absolutely clear than any such warranty, support, indemnity or liabi"
        + "lity obligation is offered by You alone, and You hereby agree to indemnify the I"
        + "nitial Developer and every Contributor for any liability incurred by the Initial"
        + " Developer or such Contributor as a result of warranty, support, indemnity or li"
        + "ability terms You offer.\n"
        + "\n"
        + "     3.6. Distribution of Executable Versions. You may distribute Covered Code i"
        + "n Executable form only if the requirements of Sections 3.1, 3.2, 3.3, 3.4 and 3."
        + "5 have been met for that Covered Code, and if You include a notice stating that "
        + "the Source Code version of the Covered Code is available under the terms of this"
        + " License, including a description of how and where You have fulfilled the obliga"
        + "tions of Section 3.2. The notice must be conspicuously included in any notice in"
        + " an Executable version, related documentation or collateral in which You describ"
        + "e recipients' rights relating to the Covered Code. You may distribute the Execut"
        + "able version of Covered Code or ownership rights under a license of Your choice,"
        + " which may contain terms different from this License, provided that You are in c"
        + "ompliance with the terms of this License and that the license for the Executable"
        + " version does not attempt to limit or alter the recipient's rights in the Source"
        + " Code version from the rights set forth in this License. If You distribute the E"
        + "xecutable version under a different license You must make it absolutely clear th"
        + "at any terms which differ from this License are offered by You alone, not by the"
        + " Initial Developer or any Contributor. You hereby agree to indemnify the Initial"
        + " Developer and every Contributor for any liability incurred by the Initial Devel"
        + "oper or such Contributor as a result of any such terms You offer.\n"
        + "\n"
        + "     3.7. Larger Works. You may create a Larger Work by combining Covered Code w"
        + "ith other code not governed by the terms of this License and distribute the Larg"
        + "er Work as a single product. In such a case, You must make sure the requirements"
        + " of this License are fulfilled for the Covered Code.\n"
        + "\n"
        + "4. Inability to Comply Due to Statute or Regulation.\n"
        + "\n"
        + "If it is impossible for You to comply with any of the terms of this License with"
        + " respect to some or all of the Covered Code due to statute, judicial order, or r"
        + "egulation then You must: (a) comply with the terms of this License to the maximu"
        + "m extent possible; and (b) describe the limitations and the code they affect. Su"
        + "ch description must be included in the LEGAL file described in Section 3.4 and m"
        + "ust be included with all distributions of the Source Code. Except to the extent "
        + "prohibited by statute or regulation, such description must be sufficiently detai"
        + "led for a recipient of ordinary skill to be able to understand it.\n"
        + "\n"
        + "5. Application of this License.\n"
        + "This License applies to code to which the Initial Developer has attached the not"
        + "ice in Exhibit A and to related Covered Code.\n"
        + "\n"
        + "6. Versions of the License.\n"
        + "\n"
        + "     6.1. New Versions\n"
        + "     Netscape Communications Corporation (\"Netscape\") may publish revised and/or"
        + " new versions of the License from time to time. Each version will be given a dis"
        + "tinguishing version number.\n"
        + "\n"
        + "     6.2. Effect of New Versions\n"
        + "     Once Covered Code has been published under a particular version of the Lice"
        + "nse, You may always continue to use it under the terms of that version. You may "
        + "also choose to use such Covered Code under the terms of any subsequent version o"
        + "f the License published by Netscape. No one other than Netscape has the right to"
        + " modify the terms applicable to Covered Code created under this License.\n"
        + "\n"
        + "     6.3. Derivative Works\n"
        + "     If You create or use a modified version of this License (which you may only"
        + " do in order to apply it to code which is not already Covered Code governed by t"
        + "his License), You must (a) rename Your license so that the phrases \"Mozilla\", \"M"
        + "OZILLAPL\", \"MOZPL\", \"Netscape\", \"MPL\", \"NPL\" or any confusingly similar phrase d"
        + "o not appear in your license (except to note that your license differs from this"
        + " License) and (b) otherwise make it clear that Your version of the license conta"
        + "ins terms which differ from the Mozilla Public License and Netscape Public Licen"
        + "se. (Filling in the name of the Initial Developer, Original Code or Contributor "
        + "in the notice described in Exhibit A shall not of themselves be deemed to be mod"
        + "ifications of this License.)\n"
        + "\n"
        + "7. DISCLAIMER OF WARRANTY\n"
        + "COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN \"AS IS\" BASIS, WITHOUT WARRANT"
        + "Y OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRA"
        + "NTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICUL"
        + "AR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE "
        + "OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY "
        + "RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COS"
        + "T OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY "
        + "CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUT"
        + "HORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.\n"
        + "\n"
        + "8. Termination\n"
        + "\n"
        + "     8.1. This License and the rights granted hereunder will terminate automatic"
        + "ally if You fail to comply with terms herein and fail to cure such breach within"
        + " 30 days of becoming aware of the breach. All sublicenses to the Covered Code wh"
        + "ich are properly granted shall survive any termination of this License. Provisio"
        + "ns which, by their nature, must remain in effect beyond the termination of this "
        + "License shall survive.\n"
        + "\n"
        + "     8.2. If You initiate litigation by asserting a patent infringement claim (e"
        + "xcluding declatory judgment actions) against Initial Developer or a Contributor "
        + "(the Initial Developer or Contributor against whom You file such action is refer"
        + "red to as \"Participant\") alleging that:\n"
        + "\n"
        + "          a. such Participant's Contributor Version directly or indirectly infri"
        + "nges any patent, then any and all rights granted by such Participant to You unde"
        + "r Sections 2.1 and/or 2.2 of this License shall, upon 60 days notice from Partic"
        + "ipant terminate prospectively, unless if within 60 days after receipt of notice "
        + "You either: (i) agree in writing to pay Participant a mutually agreeable reasona"
        + "ble royalty for Your past and future use of Modifications made by such Participa"
        + "nt, or (ii) withdraw Your litigation claim with respect to the Contributor Versi"
        + "on against such Participant. If within 60 days of notice, a reasonable royalty a"
        + "nd payment arrangement are not mutually agreed upon in writing by the parties or"
        + " the litigation claim is not withdrawn, the rights granted by Participant to You"
        + " under Sections 2.1 and/or 2.2 automatically terminate at the expiration of the "
        + "60 day notice period specified above.\n"
        + "          b. any software, hardware, or device, other than such Participant's Co"
        + "ntributor Version, directly or indirectly infringes any patent, then any rights "
        + "granted to You by such Participant under Sections 2.1(b) and 2.2(b) are revoked "
        + "effective as of the date You first made, used, sold, distributed, or had made, M"
        + "odifications made by that Participant.\n"
        + "\n"
        + "     8.3. If You assert a patent infringement claim against Participant alleging"
        + " that such Participant's Contributor Version directly or indirectly infringes an"
        + "y patent where such claim is resolved (such as by license or settlement) prior t"
        + "o the initiation of patent infringement litigation, then the reasonable value of"
        + " the licenses granted by such Participant under Sections 2.1 or 2.2 shall be tak"
        + "en into account in determining the amount or value of any payment or license.\n"
        + "\n"
        + "     8.4. In the event of termination under Sections 8.1 or 8.2 above, all end u"
        + "ser license agreements (excluding distributors and resellers) which have been va"
        + "lidly granted by You or any distributor hereunder prior to termination shall sur"
        + "vive termination.\n"
        + "\n"
        + "9. LIMITATION OF LIABILITY\n"
        + "UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER TORT (INCLUDING NEGLIG"
        + "ENCE), CONTRACT, OR OTHERWISE, SHALL YOU, THE INITIAL DEVELOPER, ANY OTHER CONTR"
        + "IBUTOR, OR ANY DISTRIBUTOR OF COVERED CODE, OR ANY SUPPLIER OF ANY OF SUCH PARTI"
        + "ES, BE LIABLE TO ANY PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENT"
        + "IAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF "
        + "GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER C"
        + "OMMERCIAL DAMAGES OR LOSSES, EVEN IF SUCH PARTY SHALL HAVE BEEN INFORMED OF THE "
        + "POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION OF LIABILITY SHALL NOT APPLY TO LIA"
        + "BILITY FOR DEATH OR PERSONAL INJURY RESULTING FROM SUCH PARTY'S NEGLIGENCE TO TH"
        + "E EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION. SOME JURISDICTIONS DO NOT ALL"
        + "OW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS E"
        + "XCLUSION AND LIMITATION MAY NOT APPLY TO YOU.\n"
        + "\n"
        + "10. U.S. government end users\n"
        + "The Covered Code is a \"commercial item,\" as that term is defined in 48 C.F.R. 2."
        + "101 (Oct. 1995), consisting of \"commercial computer software\" and \"commercial co"
        + "mputer software documentation,\" as such terms are used in 48 C.F.R. 12.212 (Sept"
        + ". 1995). Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through 227.7"
        + "202-4 (June 1995), all U.S. Government End Users acquire Covered Code with only "
        + "those rights set forth herein.\n"
        + "\n"
        + "11. Miscellaneous\n"
        + "This License represents the complete agreement concerning subject matter hereof."
        + " If any provision of this License is held to be unenforceable, such provision sh"
        + "all be reformed only to the extent necessary to make it enforceable. This Licens"
        + "e shall be governed by California law provisions (except to the extent applicabl"
        + "e law, if any, provides otherwise), excluding its conflict-of-law provisions. Wi"
        + "th respect to disputes in which at least one party is a citizen of, or an entity"
        + " chartered or registered to do business in the United States of America, any lit"
        + "igation relating to this License shall be subject to the jurisdiction of the Fed"
        + "eral Courts of the Northern District of California, with venue lying in Santa Cl"
        + "ara County, California, with the losing party responsible for costs, including w"
        + "ithout limitation, court costs and reasonable attorneys' fees and expenses. The "
        + "application of the United Nations Convention on Contracts for the International "
        + "Sale of Goods is expressly excluded. Any law or regulation which provides that t"
        + "he language of a contract shall be construed against the drafter shall not apply"
        + " to this License.\n"
        + "\n"
        + "12. Responsibility for claims\n"
        + "As between Initial Developer and the Contributors, each party is responsible for"
        + " claims and damages arising, directly or indirectly, out of its utilization of r"
        + "ights under this License and You agree to work with Initial Developer and Contri"
        + "butors to distribute such responsibility on an equitable basis. Nothing herein i"
        + "s intended or shall be deemed to constitute any admission of liability.\n"
        + "\n"
        + "13. Multiple-licensed code\n"
        + "Initial Developer may designate portions of the Covered Code as \"Multiple-Licens"
        + "ed\". \"Multiple-Licensed\" means that the Initial Developer permits you to utilize"
        + " portions of the Covered Code under Your choice of the MPL or the alternative li"
        + "censes, if any, specified by the Initial Developer in the file described in Exhi"
        + "bit A.\n"
        + "\n"
        + "Exhibit A - Mozilla Public License.\n"
        + "\n"
        + "\"The contents of this file are subject to the Mozilla Public License Version 1.1"
        + " (the \"License\"); you may not use this file except in compliance with the Licens"
        + "e. You may obtain a copy of the License at http://www.mozilla.org/MPL/\n"
        + "\n"
        + "Software distributed under the License is distributed on an \"AS IS\" basis, WITHO"
        + "UT WARRANTY OF ANY KIND, either express or implied. See the License for the spec"
        + "ific language governing rights and limitations under the License.\n"
        + "\n"
        + "The Original Code is ______________________________________.\n"
        + "\n"
        + "The Initial Developer of the Original Code is ________________________.\n"
        + "Portions created by ______________________ are Copyright (C) ______\n"
        + "_______________________. All Rights Reserved.\n"
        + "\n"
        + "Contributor(s): ______________________________________.\n"
        + "\n"
        + "Alternatively, the contents of this file may be used under the terms of the ____"
        + "_ license (the  \"[___] License\"), in which case the provisions of [______] Licen"
        + "se are applicable instead of those above. If you wish to allow use of your versi"
        + "on of this file only under the terms of the [____] License and not to allow othe"
        + "rs to use your version of this file under the MPL, indicate your decision by del"
        + "eting the provisions above and replace them with the notice and other provisions"
        + " required by the [___] License. If you do not delete the provisions above, a rec"
        + "ipient may use your version of this file under either the MPL or the [___] Licen"
        + "se.\"\n"
        + "\n"
        + "NOTE: The text of this Exhibit A may differ slightly from the text of the notice"
        + "s in the Source Code files of the Original Code. You should use the text of this"
        + " Exhibit A rather than the text found in the Original Code Source Code for Your "
        + "Modifications.\n"
; // the license text
    }
 
    
}
