package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:17:50Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: MPL_2_0.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class MPL_2_0 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return true; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "MPL-2.0"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "Mozilla Public License 2.0"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "Mozilla Public License Version 2.0 \n"
        + "\n"
        + "1. Definitions\n"
        + "\n"
        + "     1.1. \"Contributor\" means each individual or legal entity that creates, cont"
        + "ributes to the creation of, or owns Covered Software.\n"
        + "\n"
        + "     1.2. \"Contributor Version\" means the combination of the Contributions of ot"
        + "hers (if any) used by a Contributor and that particular Contributor's Contributi"
        + "on.\n"
        + "\n"
        + "     1.3. \"Contribution\" means Covered Software of a particular Contributor.\n"
        + "\n"
        + "     1.4. \"Covered Software\" means Source Code Form to which the initial Contrib"
        + "utor has attached the notice in Exhibit A, the Executable Form of such Source Co"
        + "de Form, and Modifications of such Source Code Form, in each case including port"
        + "ions thereof.\n"
        + "\n"
        + "     1.5. \"Incompatible With Secondary Licenses\" means\n"
        + "\n"
        + "          (a) that the initial Contributor has attached the notice described in "
        + "Exhibit B to the Covered Software; or\n"
        + "\n"
        + "          (b) that the Covered Software was made available under the terms of ve"
        + "rsion 1.1 or earlier of the License, but not also under the terms of a Secondary"
        + " License.\n"
        + "\n"
        + "     1.6. \"Executable Form\" means any form of the work other than Source Code Fo"
        + "rm.\n"
        + "\n"
        + "     1.7. \"Larger Work\" means a work that combines Covered Software with other m"
        + "aterial, in a separate file or files, that is not Covered Software.\n"
        + "\n"
        + "     1.8. \"License\" means this document.\n"
        + "\n"
        + "     1.9. \"Licensable\" means having the right to grant, to the maximum extent po"
        + "ssible, whether at the time of the initial grant or subsequently, any and all of"
        + " the rights conveyed by this License.\n"
        + "\n"
        + "     1.10. \"Modifications\" means any of the following:\n"
        + "\n"
        + "          (a) any file in Source Code Form that results from an addition to, del"
        + "etion from, or modification of the contents of Covered Software; or\n"
        + "\n"
        + "          (b) any new file in Source Code Form that contains any Covered Softwar"
        + "e.\n"
        + "\n"
        + "     1.11. \"Patent Claims\" of a Contributor means any patent claim(s), including"
        + " without limitation, method, process, and apparatus claims, in any patent Licens"
        + "able by such Contributor that would be infringed, but for the grant of the Licen"
        + "se, by the making, using, selling, offering for sale, having made, import, or tr"
        + "ansfer of either its Contributions or its Contributor Version.\n"
        + "\n"
        + "     1.12. \"Secondary License\" means either the GNU General Public License, Vers"
        + "ion 2.0, the GNU Lesser General Public License, Version 2.1, the GNU Affero Gene"
        + "ral Public License, Version 3.0, or any later versions of those licenses.\n"
        + "\n"
        + "     1.13. \"Source Code Form\" means the form of the work preferred for making mo"
        + "difications.\n"
        + "\n"
        + "     1.14. \"You\" (or \"Your\") means an individual or a legal entity exercising ri"
        + "ghts under this License. For legal entities, \"You\" includes any entity that cont"
        + "rols, is controlled by, or is under common control with You. For purposes of thi"
        + "s definition, \"control\" means (a) the power, direct or indirect, to cause the di"
        + "rection or management of such entity, whether by contract or otherwise, or (b) o"
        + "wnership of more than fifty percent (50%) of the outstanding shares or beneficia"
        + "l ownership of such entity.\n"
        + "\n"
        + "2. License Grants and Conditions \n"
        + "\n"
        + "     2.1. Grants\n"
        + "     Each Contributor hereby grants You a world-wide, royalty-free, non-exclusiv"
        + "e license:\n"
        + "\n"
        + "          (a) under intellectual property rights (other than patent or trademark"
        + ") Licensable by such Contributor to use, reproduce, make available, modify, disp"
        + "lay, perform, distribute, and otherwise exploit its Contributions, either on an "
        + "unmodified basis, with Modifications, or as part of a Larger Work; and\n"
        + "\n"
        + "          (b) under Patent Claims of such Contributor to make, use, sell, offer "
        + "for sale, have made, import, and otherwise transfer either its Contributions or "
        + "its Contributor Version.\n"
        + "\n"
        + "     2.2. Effective Date\n"
        + "     The licenses granted in Section 2.1 with respect to any Contribution become"
        + " effective for each Contribution on the date the Contributor first distributes s"
        + "uch Contribution.\n"
        + "\n"
        + "     2.3. Limitations on Grant Scope\n"
        + "     The licenses granted in this Section 2 are the only rights granted under th"
        + "is License. No additional rights or licenses will be implied from the distributi"
        + "on or licensing of Covered Software under this License. Notwithstanding Section "
        + "2.1(b) above, no patent license is granted by a Contributor:\n"
        + "\n"
        + "          (a) for any code that a Contributor has removed from Covered Software;"
        + " or\n"
        + "\n"
        + "          (b) for infringements caused by: (i) Your and any other third party's "
        + "modifications of Covered Software, or (ii) the combination of its Contributions "
        + "with other software (except as part of its Contributor Version); or\n"
        + "\n"
        + "          (c) under Patent Claims infringed by Covered Software in the absence o"
        + "f its Contributions.\n"
        + "\n"
        + "     This License does not grant any rights in the trademarks, service marks, or"
        + " logos of any Contributor (except as may be necessary to comply with the notice "
        + "requirements in Section 3.4).\n"
        + "\n"
        + "     2.4. Subsequent Licenses\n"
        + "     No Contributor makes additional grants as a result of Your choice to distri"
        + "bute the Covered Software under a subsequent version of this License (see Sectio"
        + "n 10.2) or under the terms of a Secondary License (if permitted under the terms "
        + "of Section 3.3).\n"
        + "\n"
        + "     2.5. Representation\n"
        + "     Each Contributor represents that the Contributor believes its Contributions"
        + " are its original creation(s) or it has sufficient rights to grant the rights to"
        + " its Contributions conveyed by this License.\n"
        + "\n"
        + "     2.6. Fair Use\n"
        + "     This License is not intended to limit any rights You have under applicable "
        + "copyright doctrines of fair use, fair dealing, or other equivalents.\n"
        + "\n"
        + "     2.7. Conditions\n"
        + "     Sections 3.1, 3.2, 3.3, and 3.4 are conditions of the licenses granted in S"
        + "ection 2.1.\n"
        + "\n"
        + "3. Responsibilities\n"
        + "\n"
        + "     3.1. Distribution of Source Form\n"
        + "     All distribution of Covered Software in Source Code Form, including any Mod"
        + "ifications that You create or to which You contribute, must be under the terms o"
        + "f this License. You must inform recipients that the Source Code Form of the Cove"
        + "red Software is governed by the terms of this License, and how they can obtain a"
        + " copy of this License. You may not attempt to alter or restrict the recipients' "
        + "rights in the Source Code Form.\n"
        + "\n"
        + "     3.2. Distribution of Executable Form\n"
        + "     If You distribute Covered Software in Executable Form then:\n"
        + "\n"
        + "          (a) such Covered Software must also be made available in Source Code F"
        + "orm, as described in Section 3.1, and You must inform recipients of the Executab"
        + "le Form how they can obtain a copy of such Source Code Form by reasonable means "
        + "in a timely manner, at a charge no more than the cost of distribution to the rec"
        + "ipient; and\n"
        + "\n"
        + "          (b) You may distribute such Executable Form under the terms of this Li"
        + "cense, or sublicense it under different terms, provided that the license for the"
        + " Executable Form does not attempt to limit or alter the recipients' rights in th"
        + "e Source Code Form under this License.\n"
        + "\n"
        + "     3.3. Distribution of a Larger Work\n"
        + "     You may create and distribute a Larger Work under terms of Your choice, pro"
        + "vided that You also comply with the requirements of this License for the Covered"
        + " Software. If the Larger Work is a combination of Covered Software with a work g"
        + "overned by one or more Secondary Licenses, and the Covered Software is not Incom"
        + "patible With Secondary Licenses, this License permits You to additionally distri"
        + "bute such Covered Software under the terms of such Secondary License(s), so that"
        + " the recipient of the Larger Work may, at their option, further distribute the C"
        + "overed Software under the terms of either this License or such Secondary License"
        + "(s).\n"
        + "\n"
        + "     3.4. Notices\n"
        + "     You may not remove or alter the substance of any license notices (including"
        + " copyright notices, patent notices, disclaimers of warranty, or limitations of l"
        + "iability) contained within the Source Code Form of the Covered Software, except "
        + "that You may alter any license notices to the extent required to remedy known fa"
        + "ctual inaccuracies.\n"
        + " \n"
        + "     3.5. Application of Additional Terms\n"
        + "     You may choose to offer, and to charge a fee for, warranty, support, indemn"
        + "ity or liability obligations to one or more recipients of Covered Software. Howe"
        + "ver, You may do so only on Your own behalf, and not on behalf of any Contributor"
        + ". You must make it absolutely clear that any such warranty, support, indemnity, "
        + "or liability obligation is offered by You alone, and You hereby agree to indemni"
        + "fy every Contributor for any liability incurred by such Contributor as a result "
        + "of warranty, support, indemnity or liability terms You offer. You may include ad"
        + "ditional disclaimers of warranty and limitations of liability specific to any ju"
        + "risdiction.\n"
        + "\n"
        + "4. Inability to Comply Due to Statute or Regulation \n"
        + "If it is impossible for You to comply with any of the terms of this License with"
        + " respect to some or all of the Covered Software due to statute, judicial order, "
        + "or regulation then You must: (a) comply with the terms of this License to the ma"
        + "ximum extent possible; and (b) describe the limitations and the code they affect"
        + ". Such description must be placed in a text file included with all distributions"
        + " of the Covered Software under this License. Except to the extent prohibited by "
        + "statute or regulation, such description must be sufficiently detailed for a reci"
        + "pient of ordinary skill to be able to understand it.\n"
        + "\n"
        + "5. Termination \n"
        + "\n"
        + "     5.1. The rights granted under this License will terminate automatically if "
        + "You fail to comply with any of its terms. However, if You become compliant, then"
        + " the rights granted under this License from a particular Contributor are reinsta"
        + "ted (a) provisionally, unless and until such Contributor explicitly and finally "
        + "terminates Your grants, and (b) on an ongoing basis, if such Contributor fails t"
        + "o notify You of the non-compliance by some reasonable means prior to 60 days aft"
        + "er You have come back into compliance. Moreover, Your grants from a particular C"
        + "ontributor are reinstated on an ongoing basis if such Contributor notifies You o"
        + "f the non-compliance by some reasonable means, this is the first time You have r"
        + "eceived notice of non-compliance with this License from such Contributor, and Yo"
        + "u become compliant prior to 30 days after Your receipt of the notice.\n"
        + "\n"
        + "     5.2. If You initiate litigation against any entity by asserting a patent in"
        + "fringement claim (excluding declaratory judgment actions, counter-claims, and cr"
        + "oss-claims) alleging that a Contributor Version directly or indirectly infringes"
        + " any patent, then the rights granted to You by any and all Contributors for the "
        + "Covered Software under Section 2.1 of this License shall terminate.\n"
        + "\n"
        + "     5.3. In the event of termination under Sections 5.1 or 5.2 above, all end u"
        + "ser license agreements (excluding distributors and resellers) which have been va"
        + "lidly granted by You or Your distributors under this License prior to terminatio"
        + "n shall survive termination.\n"
        + "\n"
        + "6. Disclaimer of Warranty \n"
        + "Covered Software is provided under this License on an \"as is\" basis, without war"
        + "ranty of any kind, either expressed, implied, or statutory, including, without l"
        + "imitation, warranties that the Covered Software is free of defects, merchantable"
        + ", fit for a particular purpose or non-infringing. The entire risk as to the qual"
        + "ity and performance of the Covered Software is with You. Should any Covered Soft"
        + "ware prove defective in any respect, You (not any Contributor) assume the cost o"
        + "f any necessary servicing, repair, or correction. This disclaimer of warranty co"
        + "nstitutes an essential part of this License. No use of any Covered Software is a"
        + "uthorized under this License except under this disclaimer. \n"
        + "\n"
        + "7. Limitation of Liability \n"
        + "Under no circumstances and under no legal theory, whether tort (including neglig"
        + "ence), contract, or otherwise, shall any Contributor, or anyone who distributes "
        + "Covered Software as permitted above, be liable to You for any direct, indirect, "
        + "special, incidental, or consequential damages of any character including, withou"
        + "t limitation, damages for lost profits, loss of goodwill, work stoppage, compute"
        + "r failure or malfunction, or any and all other commercial damages or losses, eve"
        + "n if such party shall have been informed of the possibility of such damages. Thi"
        + "s limitation of liability shall not apply to liability for death or personal inj"
        + "ury resulting from such party's negligence to the extent applicable law prohibit"
        + "s such limitation. Some jurisdictions do not allow the exclusion or limitation o"
        + "f incidental or consequential damages, so this exclusion and limitation may not "
        + "apply to You. \n"
        + "\n"
        + "8. Litigation \n"
        + "Any litigation relating to this License may be brought only in the courts of a j"
        + "urisdiction where the defendant maintains its principal place of business and su"
        + "ch litigation shall be governed by laws of that jurisdiction, without reference "
        + "to its conflict-of-law provisions. Nothing in this Section shall prevent a party"
        + "'s ability to bring cross-claims or counter-claims.\n"
        + "\n"
        + "9. Miscellaneous \n"
        + "This License represents the complete agreement concerning the subject matter her"
        + "eof. If any provision of this License is held to be unenforceable, such provisio"
        + "n shall be reformed only to the extent necessary to make it enforceable. Any law"
        + " or regulation which provides that the language of a contract shall be construed"
        + " against the drafter shall not be used to construe this License against a Contri"
        + "butor.\n"
        + "\n"
        + "10. Versions of the License \n"
        + "\n"
        + "     10.1. New Versions\n"
        + "     Mozilla Foundation is the license steward. Except as provided in Section 10"
        + ".3, no one other than the license steward has the right to modify or publish new"
        + " versions of this License. Each version will be given a distinguishing version n"
        + "umber.\n"
        + "\n"
        + "     10.2. Effect of New Versions\n"
        + "     You may distribute the Covered Software under the terms of the version of t"
        + "he License under which You originally received the Covered Software, or under th"
        + "e terms of any subsequent version published by the license steward.\n"
        + "\n"
        + "     10.3. Modified Versions\n"
        + "     If you create software not governed by this License, and you want to create"
        + " a new license for such software, you may create and use a modified version of t"
        + "his License if you rename the license and remove any references to the name of t"
        + "he license steward (except to note that such modified license differs from this "
        + "License).\n"
        + "\n"
        + "     10.4. Distributing Source Code Form that is Incompatible With Secondary Lic"
        + "enses\n"
        + "     If You choose to distribute Source Code Form that is Incompatible With Seco"
        + "ndary Licenses under the terms of this version of the License, the notice descri"
        + "bed in Exhibit B of this License must be attached.\n"
        + "\n"
        + "Exhibit A - Source Code Form License Notice \n"
        + "\n"
        + "     This Source Code Form is subject to the terms of the Mozilla Public License"
        + ", v. 2.0. If a copy of the MPL was not distributed with this file, You can obtai"
        + "n one at http://mozilla.org/MPL/2.0/.\n"
        + "\n"
        + "If it is not possible or desirable to put the notice in a particular file, then "
        + "You may include the notice in a location (such as a LICENSE file in a relevant d"
        + "irectory) where a recipient would be likely to look for such a notice.\n"
        + "\n"
        + "You may add additional accurate notices of copyright ownership.\n"
        + "\n"
        + "Exhibit B - \"Incompatible With Secondary Licenses\" Notice \n"
        + "\n"
        + "     This Source Code Form is \"Incompatible With Secondary Licenses\", as defined"
        + " by the Mozilla Public License, v. 2.0.\n"
; // the license text
    }
 
    
}
