package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:17:54Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: NOSL.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class NOSL extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return false; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "NOSL"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "Netizen Open Source License"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "NETIZEN OPEN SOURCE LICENSE \n"
        + "Version 1.0 \n"
        + "\n"
        + "1. Definitions.\n"
        + "\n"
        + "     1.0.1. \"Commercial Use\" means distribution or otherwise making the Covered "
        + "Code available to a third party. \n"
        + "   \n"
        + "     1.1. \"Contributor\" means each entity that creates or contributes to the cre"
        + "ation of Modifications. \n"
        + "\n"
        + "     1.2. \"Contributor Version\" means the combination of the Original Code, prio"
        + "r Modifications used by a Contributor, and the Modifications made by that partic"
        + "ular Contributor. \n"
        + "\n"
        + "     1.3. \"Covered Code\" means the Original Code or Modifications or the combina"
        + "tion of the Original Code and Modifications, in each case including portions the"
        + "reof. \n"
        + "\n"
        + "     1.4. \"Electronic Distribution Mechanism\" means a mechanism generally accept"
        + "ed in the software development community for the electronic transfer of data. \n"
        + "\n"
        + "     1.5. \"Executable\" means Covered Code in any form other than Source Code. \n"
        + "\n"
        + "     1.6. \"Initial Developer\" means the individual or entity identified as the I"
        + "nitial Developer in the Source Code notice required by Exhibit A. \n"
        + "\n"
        + "     1.7. \"Larger Work\" means a work which combines Covered Code or portions the"
        + "reof with code not governed by the terms of this License.\n"
        + "\n"
        + "     1.8. \"License\" means this document. \n"
        + "\n"
        + "     1.8.1. \"Licensable\" means having the right to grant, to the maximum extent "
        + "possible, whether at the time of the initial grant or subsequently acquired, any"
        + " and all of the rights conveyed herein. \n"
        + "\n"
        + "     1.9. \"Modifications\" means any addition to or deletion from the substance o"
        + "r structure of either the Original Code or any previous Modifications. When Cove"
        + "red Code is released as a series of files, a Modification is:\n"
        + "          A. Any addition to or deletion from the contents of a file containing "
        + "Original Code or previous Modifications. \n"
        + "          B. Any new file that contains any part of the Original Code or previou"
        + "s Modifications. \n"
        + "\n"
        + "     1.10. \"Original Code\" means Source Code of computer software code which is "
        + "described in the Source Code notice required by Exhibit A as Original Code, and "
        + "which, at the time of its release under this License is not already Covered Code"
        + " governed by this License. \n"
        + "\n"
        + "     1.10.1. \"Patent Claims\" means any patent claim(s), now owned or hereafter a"
        + "cquired, including without limitation, method, process, and apparatus claims, in"
        + " any patent Licensable by grantor. \n"
        + "\n"
        + "     1.11. \"Source Code\" means the preferred form of the Covered Code for making"
        + " modifications to it, including all modules it contains, plus any associated int"
        + "erface definition files, scripts used to control compilation and installation of"
        + " an Executable, or source code differential comparisons against either the Origi"
        + "nal Code or another well known, available Covered Code of the Contributor's choi"
        + "ce. The Source Code can be in a compressed or archival form, provided the approp"
        + "riate decompression or de-archiving software is widely available for no charge. \n"
        + "\n"
        + "     1.12. \"You\" (or \"Your\") means an individual or a legal entity exercising ri"
        + "ghts under, and complying with all of the terms of, this License or a future ver"
        + "sion of this License issued under Section 6.1. For legal entities, \"You\" include"
        + "s any entity which controls, is controlled by, or is under common control with Y"
        + "ou. For purposes of this definition, \"control\" means (a) the power, direct or in"
        + "direct, to cause the direction or management of such entity, whether by contract"
        + " or otherwise, or (b) ownership of more than fifty percent (50%) of the outstand"
        + "ing shares or beneficial ownership of such entity. \n"
        + "\n"
        + "2. Source Code License. \n"
        + "\n"
        + "     2.1. The Initial Developer Grant. The Initial Developer hereby grants You a"
        + " world-wide, royalty-free, non-exclusive license, subject to third party intelle"
        + "ctual property claims:\n"
        + "          (a) under intellectual property rights (other than patent or trademark"
        + ") Licensable by Initial Developer to use, reproduce, modify, display, perform, s"
        + "ublicense and distribute the Original Code (or portions thereof) with or without"
        + " Modifications, and/or as part of a Larger Work; and \n"
        + "          (b) under Patents Claims infringed by the making, using or selling of "
        + "Original Code, to make, have made, use, practice, sell, and offer for sale, and/"
        + "or otherwise dispose of the Original Code (or portions thereof). \n"
        + "          (c) the licenses granted in this Section 2.1(a) and (b) are effective "
        + "on the date Initial Developer first distributes Original Code under the terms of"
        + " this License. \n"
        + "          (d) Notwithstanding Section 2.1(b) above, no patent license is granted"
        + ": 1) for code that You delete from the Original Code; 2) separate from the Origi"
        + "nal Code; or 3) for infringements caused by: i) the modification of the Original"
        + " Code or ii) the combination of the Original Code with other software or devices"
        + ". \n"
        + "\n"
        + "     2.2. Contributor Grant.\n"
        + "     Subject to third party intellectual property claims, each Contributor hereb"
        + "y grants You a world-wide, royalty-free, non-exclusive license \n"
        + "          (a) under intellectual property rights (other than patent or trademark"
        + ") Licensable by Contributor, to use, reproduce, modify, display, perform, sublic"
        + "ense and distribute the Modifications created by such Contributor (or portions t"
        + "hereof) either on an unmodified basis, with other Modifications, as Covered Code"
        + " and/or as part of a Larger Work; and \n"
        + "          (b) under Patent Claims infringed by the making, using, or selling of "
        + "Modifications made by that Contributor either alone and/or in combination with i"
        + "ts Contributor Version (or portions of such combination), to make, use, sell, of"
        + "fer for sale, have made, and/or otherwise dispose of: 1) Modifications made by t"
        + "hat Contributor (or portions thereof); and 2) the combination of Modifications m"
        + "ade by that Contributor with its Contributor Version (or portions of such combin"
        + "ation). \n"
        + "          (c) the licenses granted in Sections 2.2(a) and 2.2(b) are effective o"
        + "n the date Contributor first makes Commercial Use of the Covered Code. \n"
        + "          (d) Notwithstanding Section 2.2(b) above, no patent license is granted"
        + ": 1) for any code that Contributor has deleted from the Contributor Version; 2) "
        + "separate from the Contributor Version; 3) for infringements caused by: i) third "
        + "party modifications of Contributor Version or ii) the combination of Modificatio"
        + "ns made by that Contributor with other software (except as part of the Contribut"
        + "or Version) or other devices; or 4) under Patent Claims infringed by Covered Cod"
        + "e in the absence of Modifications made by that Contributor. \n"
        + "\n"
        + "3. Distribution Obligations. \n"
        + "\n"
        + "     3.1. Application of License. The Modifications which You create or to which"
        + " You contribute are governed by the terms of this License, including without lim"
        + "itation Section 2.2. The Source Code version of Covered Code may be distributed "
        + "only under the terms of this License or a future version of this License release"
        + "d under Section 6.1, and You must include a copy of this License with every copy"
        + " of the Source Code You distribute. You may not offer or impose any terms on any"
        + " Source Code version that alters or restricts the applicable version of this Lic"
        + "ense or the recipients' rights hereunder. However, You may include an additional"
        + " document offering the additional rights described in Section 3.5. \n"
        + "\n"
        + "     3.2. Availability of Source Code. Any Modification which You create or to w"
        + "hich You contribute must be made available in Source Code form under the terms o"
        + "f this License either on the same media as an Executable version or via an accep"
        + "ted Electronic Distribution Mechanism to anyone to whom you made an Executable v"
        + "ersion available; and if made available via Electronic Distribution Mechanism, m"
        + "ust remain available for at least twelve (12) months after the date it initially"
        + " became available, or at least six (6) months after a subsequent version of that"
        + " particular Modification has been made available to such recipients. You are res"
        + "ponsible for ensuring that the Source Code version remains available even if the"
        + " Electronic Distribution Mechanism is maintained by a third party. \n"
        + "\n"
        + "     3.3. Description of Modifications. You must cause all Covered Code to which"
        + " You contribute to contain a file documenting the changes You made to create tha"
        + "t Covered Code and the date of any change. You must include a prominent statemen"
        + "t that the Modification is derived, directly or indirectly, from Original Code p"
        + "rovided by the Initial Developer and including the name of the Initial Developer"
        + " in (a) the Source Code, and (b) in any notice in an Executable version or relat"
        + "ed documentation in which You describe the origin or ownership of the Covered Co"
        + "de. \n"
        + "\n"
        + "     3.4. Intellectual Property Matters\n"
        + "          (a) Third Party Claims.\n"
        + "          If Contributor has knowledge that a license under a third party's inte"
        + "llectual property rights is required to exercise the rights granted by such Cont"
        + "ributor under Sections 2.1 or 2.2, Contributor must include a text file with the"
        + " Source Code distribution titled \"LEGAL\" which describes the claim and the party"
        + " making the claim in sufficient detail that a recipient will know whom to contac"
        + "t. If Contributor obtains such knowledge after the Modification is made availabl"
        + "e as described in Section 3.2, Contributor shall promptly modify the LEGAL file "
        + "in all copies Contributor makes available thereafter and shall take other steps "
        + "(such as notifying appropriate mailing lists or newsgroups) reasonably calculate"
        + "d to inform those who received the Covered Code that new knowledge has been obta"
        + "ined. \n"
        + "          (b) Contributor APIs. \n"
        + "          If Contributor's Modifications include an application programming inte"
        + "rface and Contributor has knowledge of patent licenses which are reasonably nece"
        + "ssary to implement that API, Contributor must also include this information in t"
        + "he LEGAL file. \n"
        + "          (c) Representations.\n"
        + "          Contributor represents that, except as disclosed pursuant to Section 3"
        + ".4(a) above, Contributor believes that Contributor's Modifications are Contribut"
        + "or's original creation(s) and/or Contributor has sufficient rights to grant the "
        + "rights conveyed by this License. \n"
        + "trend\n"
        + "\n"
        + "     3.5. Required Notices.\n"
        + "     You must duplicate the notice in Exhibit A in each file of the Source Code."
        + " If it is not possible to put such notice in a particular Source Code file due t"
        + "o its structure, then You must include such notice in a location (such as a rele"
        + "vant directory) where a user would be likely to look for such a notice. If You c"
        + "reated one or more Modification(s) You may add your name as a Contributor to the"
        + " notice described in Exhibit A. You must also duplicate this License in any docu"
        + "mentation for the Source Code where You describe recipients' rights or ownership"
        + " rights relating to Covered Code. You may choose to offer, and to charge a fee f"
        + "or, warranty, support, indemnity or liability obligations to one or more recipie"
        + "nts of Covered Code. However, You may do so only on Your own behalf, and not on "
        + "behalf of the Initial Developer or any Contributor. You must make it absolutely "
        + "clear than any such warranty, support, indemnity or liability obligation is offe"
        + "red by You alone, and You hereby agree to indemnify the Initial Developer and ev"
        + "ery Contributor for any liability incurred by the Initial Developer or such Cont"
        + "ributor as a result of warranty, support, indemnity or liability terms You offer"
        + ". \n"
        + "\n"
        + "     3.6. Distribution of Executable Versions.\n"
        + "     You may distribute Covered Code in Executable form only if the requirements"
        + " of Section 3.1-3.5 have been met for that Covered Code, and if You include a no"
        + "tice stating that the Source Code version of the Covered Code is available under"
        + " the terms of this License, including a description of how and where You have fu"
        + "lfilled the obligations of Section 3.2. The notice must be conspicuously include"
        + "d in any notice in an Executable version, related documentation or collateral in"
        + " which You describe recipients' rights relating to the Covered Code. You may dis"
        + "tribute the Executable version of Covered Code or ownership rights under a licen"
        + "se of Your choice, which may contain terms different from this License, provided"
        + " that You are in compliance with the terms of this License and that the license "
        + "for the Executable version does not attempt to limit or alter the recipient's ri"
        + "ghts in the Source Code version from the rights set forth in this License. If Yo"
        + "u distribute the Executable version under a different license You must make it a"
        + "bsolutely clear that any terms which differ from this License are offered by You"
        + " alone, not by the Initial Developer or any Contributor. You hereby agree to ind"
        + "emnify the Initial Developer and every Contributor for any liability incurred by"
        + " the Initial Developer or such Contributor as a result of any such terms You off"
        + "er. \n"
        + "\n"
        + "     3.7. Larger Works.\n"
        + "     You may create a Larger Work by combining Covered Code with other code not "
        + "governed by the terms of this License and distribute the Larger Work as a single"
        + " LEDs product. In such a case, You must make sure the requirements of this Licen"
        + "se are fulfilled for the Covered Code. \n"
        + "\n"
        + "4. Inability to Comply Due to Statute or Regulation.\n"
        + "\n"
        + "If it is impossible for You to comply with any of the terms of this License with"
        + " respect to some or all of the Covered Code due to statute, judicial order, or r"
        + "egulation then You must: (a) comply with the terms of this License to the maximu"
        + "m extent possible; and (b) describe the limitations and the code they affect. Su"
        + "ch description must be included in the LEGAL file described in Section 3.4 and m"
        + "ust be included with all distributions of the Source Code. Except to the extent "
        + "prohibited by statute or regulation, such description must be sufficiently detai"
        + "led for a recipient of ordinary skill to be able to understand it. \n"
        + "\n"
        + "5. Application of this License. \n"
        + "\n"
        + "This License applies to code to which the Initial Developer has attached the not"
        + "ice in Exhibit A and to related Covered Code. \n"
        + "\n"
        + "6. Versions of the License. \n"
        + "\n"
        + "     6.1. New Versions.\n"
        + "     Netizen Pty Ltd (\"Netizen \") may publish revised and/or new versions of the"
        + " License from time to time. Each version will be given a distinguishing version "
        + "number. \n"
        + "\n"
        + "     6.2. Effect of New Versions.\n"
        + "     Once Covered Code has been published under a particular version of the Lice"
        + "nse, You may always continue to use it under the terms of that version. You may "
        + "also choose to use such Covered Code under the terms of any subsequent version o"
        + "f the License published by Netizen. No one other than Netizen has the right to m"
        + "odify the terms applicable to Covered Code created under this License. \n"
        + "\n"
        + "     6.3. Derivative Works. \n"
        + "     If You create or use a modified version of this License (which you may only"
        + " do in order to apply it to code which is not already Covered Code governed by t"
        + "his License), You must (a) rename Your license so that the phrases \"Netizen\", \"N"
        + "OSL\" or any confusingly similar phrase do not appear in your license (except to "
        + "note that your license differs from this License) and (b) otherwise make it clea"
        + "r that Your version of the license contains terms which differ from the Netizen "
        + "Open Source License and Xen Open Source License. (Filling in the name of the Ini"
        + "tial Developer, Original Code or Contributor in the notice described in Exhibit "
        + "A shall not of themselves be deemed to be modifications of this License.) \n"
        + "\n"
        + "7. DISCLAIMER OF WARRANTY.\n"
        + "\n"
        + "COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN \"AS IS\" BASIS, WITHOUT WARRANT"
        + "Y OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRA"
        + "NTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICUL"
        + "AR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE "
        + "OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY "
        + "RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COS"
        + "T OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY "
        + "CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUT"
        + "HORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER. \n"
        + "\n"
        + "     7.1 To the extent permitted by law and except as expressly provided to the "
        + "contrary in this Agreement, all warranties whether express, implied, statutory o"
        + "r otherwise, relating in any way to the subject matter of this Agreement or to t"
        + "his Agreement generally, are excluded. Where legislation implies in this Agreeme"
        + "nt any condition or warranty and that legislation avoids or prohibits provisions"
        + " in a contract excluding or modifying the application of or the exercise of or l"
        + "iability under such term, such term shall be deemed to be included in this Agree"
        + "ment. However, the liability of Supplier for any breach of such term shall be li"
        + "mited, at the option of Supplier, to any one or more of the following: if the br"
        + "each related to goods: the replacement of the goods or the supply of equivalent "
        + "goods; the repair of such goods; the payment of the cost of replacing the goods "
        + "or of acquiring equivalent goods; or the payment of the cost of having the goods"
        + " repaired; and if the breach relates to services the supplying of the services a"
        + "gain; or the payment of the cost of having the services supplied again. \n"
        + "\n"
        + "8. TERMINATION. \n"
        + "\n"
        + "     8.1. This License and the rights granted hereunder will terminate automatic"
        + "ally if You fail to comply with terms herein and fail to cure such breach within"
        + " 30 days of becoming aware of the breach. All sublicenses to the Covered Code wh"
        + "ich are properly granted shall survive any termination of this License. Provisio"
        + "ns which, by their nature, must remain in effect beyond the termination of this "
        + "License shall survive. \n"
        + "\n"
        + "     8.2. If You initiate litigation by asserting a patent infringement claim (e"
        + "xcluding declatory judgment actions) against Initial Developer or a Contributor "
        + "(the Initial Developer or Contributor against whom You file such action is refer"
        + "red to as \"Participant\") alleging that: \n"
        + "          (a) such Participant's Contributor Version directly or indirectly infr"
        + "inges any patent, then any and all rights granted by such Participant to You und"
        + "er Sections 2.1 and/or 2.2 of this License shall, upon 60 days notice from Parti"
        + "cipant terminate prospectively, unless if within 60 days after receipt of notice"
        + " You either: (i) agree in writing to pay Participant a mutually agreeable reason"
        + "able royalty for Your past and future use of Modifications made by such Particip"
        + "ant, or (ii) withdraw Your litigation claim with respect to the Contributor Vers"
        + "ion against such Participant. If within 60 days of notice, a reasonable royalty "
        + "and payment arrangement are not mutually agreed upon in writing by the parties o"
        + "r the litigation claim is not withdrawn, the rights granted by Participant to Yo"
        + "u under Sections 2.1 and/or 2.2 automatically terminate at the expiration of the"
        + " 60 day notice period specified above. \n"
        + "          (b) any software, hardware, or device, other than such Participant's C"
        + "ontributor Version, directly or indirectly infringes any patent, then any rights"
        + " granted to You by such Participant under Sections 2.1(b) and 2.2(b) are revoked"
        + " effective as of the date You first made, used, sold, distributed, or had made, "
        + "Modifications made by that Participant. \n"
        + "\n"
        + "     8.3. If You assert a patent infringement claim against Participant alleging"
        + " that such Participant's Contributor Version directly or indirectly infringes an"
        + "y patent where such claim is resolved (such as by license or settlement) prior t"
        + "o the initiation of patent infringement litigation, then the reasonable value of"
        + " the licenses granted by such Participant under Sections 2.1 or 2.2 shall be tak"
        + "en into account in determining the amount or value of any payment or license. \n"
        + "\n"
        + "     8.4. In the event of termination under Sections 8.1 or 8.2 above, all end u"
        + "ser license agreements (excluding distributors and resellers) which have been va"
        + "lidly granted by You or any distributor hereunder prior to termination shall sur"
        + "vive termination. \n"
        + "\n"
        + "9. LIMITATION OF LIABILITY. \n"
        + "UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER TORT (INCLUDING NEGLIG"
        + "ENCE), CONTRACT, OR OTHERWISE, SHALL YOU, THE INITIAL DEVELOPER, ANY OTHER CONTR"
        + "IBUTOR, OR ANY DISTRIBUTOR OF COVERED CODE, OR ANY SUPPLIER OF ANY OF SUCH PARTI"
        + "ES, BE LIABLE TO ANY PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENT"
        + "IAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF "
        + "GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER C"
        + "OMMERCIAL DAMAGES OR LOSSES, EVEN IF SUCH PARTY SHALL HAVE BEEN INFORMED OF THE "
        + "POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION OF LIABILITY SHALL NOT APPLY TO LIA"
        + "BILITY FOR DEATH OR PERSONAL INJURY RESULTING FROM SUCH PARTY'S NEGLIGENCE TO TH"
        + "E EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION. SOME JURISDICTIONS DO NOT ALL"
        + "OW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS E"
        + "XCLUSION AND LIMITATION MAY NOT APPLY TO YOU. \n"
        + "\n"
        + "10. U.S. GOVERNMENT END USERS. \n"
        + "\n"
        + "The Covered Code is a \"commercial item,\" as that term is defined in 48 C.F.R. 2."
        + "101 (Oct. 1995), consisting of \"commercial computer software\" and \"commercial co"
        + "mputer software documentation,\" as such terms are used in 48 C.F.R. 12.212 (Sept"
        + ". 1995). Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through 227.7"
        + "202-4 (June 1995), all U.S. Government End Users acquire Covered Code with only "
        + "those rights set forth herein. \n"
        + "\n"
        + "11. MISCELLANEOUS. \n"
        + "\n"
        + "This License represents the complete agreement concerning subject matter hereof."
        + " If any provision of this License is held to be unenforceable, such provision sh"
        + "all be reformed only to the extent necessary to make it enforceable. \n"
        + "This Agreement shall be governed by and construed according to the law of the St"
        + "ate of Victoria. The parties irrevocably submit to the exclusive jurisdiction of"
        + " the Courts of Victoria and Australia and any Courts hearing appeals from such C"
        + "ourts. This Agreement is deemed to have been made in Victoria. \n"
        + "The application of the United Nations Convention on Contracts for the Internatio"
        + "nal Sale of Goods is expressly excluded. Any law or regulation which provides th"
        + "at the language of a contract shall be construed against the drafter shall not a"
        + "pply to this License. \n"
        + "\n"
        + "12. RESPONSIBILITY FOR CLAIMS. \n"
        + "\n"
        + "As between Initial Developer and the Contributors, each party is responsible for"
        + " claims and damages arising, directly or indirectly, out of its utilization of r"
        + "ights under this License and You agree to work with Initial Developer and Contri"
        + "butors to distribute such responsibility on an equitable basis. Nothing herein i"
        + "s intended or shall be deemed to constitute any admission of liability. \n"
        + "\n"
        + "13. MULTIPLE-LICENSED CODE. \n"
        + "\n"
        + "Initial Developer may designate portions of the Covered Code as \"Multiple-Licens"
        + "ed\". \"Multiple-Licensed\" means that the Initial Developer permits you to utilize"
        + " portions of the Covered Code under Your choice of the NPL or the alternative li"
        + "censes, if any, specified by the Initial Developer in the file described in Exhi"
        + "bit A. \n"
        + "\n"
        + "EXHIBIT A - Netizen Open Source License \n"
        + "\n"
        + "     ``The contents of this file are subject to the Netizen Open Source License "
        + "Version 1.0 (the \"License\"); you may not use this file except in compliance with"
        + " the License. You may obtain a copy of the License at http://netizen.com.au/lice"
        + "nses/NOPL/ \n"
        + "\n"
        + "     Software distributed under the License is distributed on an \"AS IS\" basis, "
        + "WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the"
        + " specific language governing rights and limitations under the License. \n"
        + "\n"
        + "     The Original Code is ______________________________________. \n"
        + "\n"
        + "     The Initial Developer of the Original Code is ________________________. Por"
        + "tions created by ______________________ are Copyright (C) ______ _______________"
        + "________. All Rights Reserved. \n"
        + "\n"
        + "     Contributor(s): ______________________________________. \n"
        + "\n"
        + "     Alternatively, the contents of this file may be used under the terms of the"
        + " _____ license (the \"[___] License\"), in which case the provisions of [______] L"
        + "icense are applicable instead of those above. If you wish to allow use of your v"
        + "ersion of this file only under the terms of the [____] License and not to allow "
        + "others to use your version of this file under the NOSL, indicate your decision b"
        + "y deleting the provisions above and replace them with the notice and other provi"
        + "sions required by the [___] License. If you do not delete the provisions above, "
        + "a recipient may use your version of this file under either the NOSL or the [___]"
        + " License.\" \n"
        + "\n"
        + "     [NOTE: The text of this Exhibit A may differ slightly from the text of the "
        + "notices in the Source Code files of the Original Code. You should use the text o"
        + "f this Exhibit A rather than the text found in the Original Code Source Code for"
        + " Your Modifications.]\n"
; // the license text
    }
 
    
}
