package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:18:10Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: OPL_1_0.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class OPL_1_0 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return false; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "OPL-1.0"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "Open Public License v1.0"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "OPEN PUBLIC LICENSE \n"
        + "Version 1.0 \n"
        + "\n"
        + "1. Definitions.\n"
        + "\n"
        + "     1.1. \"Contributor\" means each entity that creates or contributes to the cre"
        + "ation of Modifications.\n"
        + "\n"
        + "     1.2. \"Contributor Version\" means the combination of the Original Code, prio"
        + "r Modifications used by a Contributor, and the Modifications made by that partic"
        + "ular Contributor.\n"
        + "\n"
        + "     1.3. \"Covered Code\" means the Original Code or Modifications or the combina"
        + "tion of the Original Code and Modifications, in each case including portions the"
        + "reof.\n"
        + "\n"
        + "     1.4. \"Electronic Distribution Mechanism\" means a mechanism generally accept"
        + "ed in the software development community for the electronic transfer of data.\n"
        + "\n"
        + "     1.5. \"Executable\" means Covered Code in any form other than Source Code.\n"
        + "\n"
        + "     1.6. \"Initial Developer\" means the individual or entity identified as the I"
        + "nitial Developer in the Source Code notice required by Exhibit A.\n"
        + "\n"
        + "     1.7. \"Larger Work\" means a work, which combines Covered Code or portions th"
        + "ereof with code not governed by the terms of this License.\n"
        + "\n"
        + "     1.8. \"License\" means this document and the corresponding addendum described"
        + " in section 6.4 below.\n"
        + "\n"
        + "     1.9. \"Modifications\" means any addition to or deletion from the substance o"
        + "r structure of either the Original Code or any previous Modifications. When Cove"
        + "red Code is released as a series of files, a Modification is:\n"
        + "\n"
        + "          A. Any addition to or deletion from the contents of a file containing "
        + "Original Code or previous Modifications.\n"
        + "\n"
        + "          B. Any new file that contains any part of the Original Code or previou"
        + "s Modifications.\n"
        + "\n"
        + "     1.10. \"Original Code\" means Source Code of computer software code which is "
        + "described in the Source Code notice required by Exhibit A as Original Code, and "
        + "which, at the time of its release under this License is not already Covered Code"
        + " governed by this License.\n"
        + "\n"
        + "     1.11. \"Source Code\" means the preferred form of the Covered Code for making"
        + " modifications to it, including all modules it contains, plus any associated int"
        + "erface definition files, scripts used to control compilation and installation of"
        + " an Executable, or a list of source code differential comparisons against either"
        + " the Original Code or another well known, available Covered Code of the Contribu"
        + "tor's choice. The Source Code can be in a compressed or archival form, provided "
        + "the appropriate decompression or de-archiving software is widely available for n"
        + "o charge.\n"
        + "\n"
        + "     1.12. \"You\" means an individual or a legal entity exercising rights under, "
        + "and complying with all of the terms of, this License or a future version of this"
        + " License issued under Section 6.1. For legal entities, \"You'' includes any entit"
        + "y which controls, is controlled by, or is under common control with You. For pur"
        + "poses of this definition, \"control'' means (a) the power, direct or indirect, to"
        + " cause the direction or management of such entity, whether by contract or otherw"
        + "ise, or (b) ownership of fifty percent (50%) or more of the outstanding shares o"
        + "r beneficial ownership of such entity.\n"
        + "\n"
        + "     1.13 \"License Author\" means Lutris Technologies, Inc.\n"
        + "\n"
        + "2. Source Code License.\n"
        + "\n"
        + "     2.1. The Initial Developer Grant. The Initial Developer hereby grants You a"
        + " worldwide, royalty-free, non-exclusive license, subject to third party intellec"
        + "tual property claims:\n"
        + "\n"
        + "          (a) under intellectual property rights (other than patent or trademark"
        + ") to use, reproduce, modify, display, perform, sublicense and distribute the Ori"
        + "ginal Code (or portions thereof) with or without Modifications, or as part of a "
        + "Larger Work; and\n"
        + "\n"
        + "          (b) under patents now or hereafter owned or controlled by Initial Deve"
        + "loper, to make, have made, use and sell (``offer to sell and import'') the Origi"
        + "nal Code (or portions thereof), but solely to the extent that any such patent is"
        + " reasonably necessary to enable You to Utilize the Original Code (or portions th"
        + "ereof) and not to any greater extent that may be necessary to Utilize further Mo"
        + "difications or combinations.\n"
        + "\n"
        + "     2.2. Contributor Grant. Each Contributor hereby grants You a worldwide, roy"
        + "alty-free, non-exclusive license, subject to third party intellectual property c"
        + "laims:\n"
        + "\n"
        + "          (a) under intellectual property rights (other than patent or trademark"
        + ") to use, reproduce, modify, display, perform, sublicense and distribute the Mod"
        + "ifications created by such Contributor (or portions thereof) either on an unmodi"
        + "fied basis, with other Modifications, as Covered Code or as part of a Larger Wor"
        + "k; and\n"
        + "\n"
        + "          (b) under patents now or hereafter owned or controlled by Contributor,"
        + " to to make, have made, use and sell (``offer to sell and import'') the Contribu"
        + "tor Version (or portions thereof), but solely to the extent that any such patent"
        + " is reasonably necessary to enable You to Utilize the Contributor Version (or po"
        + "rtions thereof), and not to any greater extent that may be necessary to Utilize "
        + "further Modifications or combinations\n"
        + "\n"
        + "3. Distribution Obligations.\n"
        + "\n"
        + "     3.1. Application of License. The Modifications which You create or to which"
        + " You contribute are governed by the terms of this License, including without lim"
        + "itation Section 2.2. The Source Code version of Covered Code may be distributed "
        + "only under the terms of this License or a future version of this License release"
        + "d under Section 6.1, and You must include a copy of this License with every copy"
        + " of the Source Code You distribute. You may not offer or impose any terms on any"
        + " Source Code version that alters or restricts the applicable version of this Lic"
        + "ense or the recipients' rights hereunder. However, You may include an additional"
        + " document offering the additional rights described in Section 3.5.\n"
        + "\n"
        + "     3.2. Availability of Source Code. Any Modification which You create or to w"
        + "hich You contribute must be made available, prior to any use, except for interna"
        + "l development and practice, in Source Code form under the terms of this License "
        + "either on the same media as an Executable version or via an accepted Electronic "
        + "Distribution Mechanism to anyone to whom you made an Executable version availabl"
        + "e; and if made available via Electronic Distribution Mechanism, must remain avai"
        + "lable for at least twelve (12) months after the date it initially became availab"
        + "le, or at least six (6) months after a subsequent version of that particular Mod"
        + "ification has been made available to such recipients. You shall notify the Initi"
        + "al Developer of the Modification and the location of the Source Code via the con"
        + "tact means provided for in the Developer Specific license. Initial Developer wil"
        + "l be acting as maintainer of the Source Code and may provide an Electronic Distr"
        + "ibution mechanism for the Modification to be made available.\n"
        + "\n"
        + "     3.3. Description of Modifications. You must cause all Covered Code to which"
        + " you contribute to contain a file documenting the changes You made to create tha"
        + "t Covered Code and the date of any change. You must include a prominent statemen"
        + "t that the Modification is derived, directly or indirectly, from Original Code p"
        + "rovided by the Initial Developer and including the name of the Initial Developer"
        + " in (a) the Source Code, and (b) in any notice in an Executable version or relat"
        + "ed documentation in which You describe the origin or ownership of the Covered Co"
        + "de.\n"
        + "\n"
        + "     3.4. Intellectual Property Matters\n"
        + "\n"
        + "          (a) Third Party Claims. If You have knowledge that a party claims an i"
        + "ntellectual property right in particular functionality or code (or its utilizati"
        + "on under this License), you must include a text file with the source code distri"
        + "bution titled \"LEGAL\" which describes the claim and the party making the claim i"
        + "n sufficient detail that a recipient will know whom to contact. If you obtain su"
        + "ch knowledge after You make Your Modification available as described in Section "
        + "3.2, You shall promptly modify the LEGAL file in all copies You make available t"
        + "hereafter and shall take other steps (such as notifying appropriate mailing list"
        + "s or newsgroups) reasonably calculated to inform those who received the Covered "
        + "Code that new knowledge has been obtained.\n"
        + "\n"
        + "          (b) Representations. Contributor represents that, except as disclosed "
        + "pursuant to Section 3.4(a) above, Contributor believes that Contributor's Modifi"
        + "cations are Contributor's original creation(s) and/or Contributor has sufficient"
        + " rights to grant the rights conveyed by this License.\n"
        + "\n"
        + "     3.5. Required Notices. You must duplicate the notice in Exhibit A in each f"
        + "ile of the Source Code, and this License in any documentation for the Source Cod"
        + "e, where You describe recipients' rights relating to Covered Code. If You create"
        + "d one or more Modification(s), You may add your name as a Contributor to the not"
        + "ice described in Exhibit A. If it is not possible to put such notice in a partic"
        + "ular Source Code file due to its structure, then you must include such notice in"
        + " a location (such as a relevant directory file) where a user would be likely to "
        + "look for such a notice. You may choose to offer, and to charge a fee for, warran"
        + "ty, support, indemnity or liability obligations to one or more recipients of Cov"
        + "ered Code. However, You may do so only on Your own behalf, and not on behalf of "
        + "the Initial Developer or any Contributor. You must make it absolutely clear that"
        + " any such warranty, support, indemnity or liability obligation is offered by You"
        + " alone, and You hereby agree to indemnify the Initial Developer and every Contri"
        + "butor for any liability incurred by the Initial Developer or such Contributor as"
        + " a result of warranty, support, indemnity or liability terms You offer.\n"
        + "\n"
        + "     3.6. Distribution of Executable Versions. You may distribute Covered Code i"
        + "n Executable form only if the requirements of Section 3.1-3.5 have been met for "
        + "that Covered Code, and if You include a notice stating that the Source Code vers"
        + "ion of the Covered Code is available under the terms of this License, including "
        + "a description of how and where You have fulfilled the obligations of Section 3.2"
        + ". The notice must be conspicuously included in any notice in an Executable versi"
        + "on, related documentation or collateral in which You describe recipients' rights"
        + " relating to the Covered Code. You may distribute the Executable version of Cove"
        + "red Code under a license of Your choice, which may contain terms different from "
        + "this License, provided that You are in compliance with the terms of this License"
        + " and that the license for the Executable version does not attempt to limit or al"
        + "ter the recipient's rights in the Source Code version from the rights set forth "
        + "in this License. If You distribute the Executable version under a different lice"
        + "nse You must make it absolutely clear that any terms which differ from this Lice"
        + "nse are offered by You alone, not by the Initial Developer or any Contributor. Y"
        + "ou hereby agree to indemnify the Initial Developer and every Contributor for any"
        + " liability incurred by the Initial Developer or such Contributor as a result of "
        + "any such terms You offer. If you distribute executable versions containing Cover"
        + "ed Code, you must reproduce the notice in Exhibit B in the documentation and/or "
        + "other materials provided with the product.\n"
        + "\n"
        + "     3.7. Larger Works. You may create a Larger Work by combining Covered Code w"
        + "ith other code not governed by the terms of this License and distribute the Larg"
        + "er Work as a single product. In such a case, You must make sure the requirements"
        + " of this License are fulfilled for the Covered Code.\n"
        + "\n"
        + "4. Inability to Comply Due to Statute or Regulation.\n"
        + "\n"
        + "If it is impossible for You to comply with any of the terms of this License with"
        + " respect to some or all of the Covered Code due to statute or regulation then Yo"
        + "u must: (a) comply with the terms of this License to the maximum extent possible"
        + "; and (b) Cite all of the statutes or regulations that prohibit you from complyi"
        + "ng fully with this license. (c) describe the limitations and the code they affec"
        + "t. Such description must be included in the LEGAL file described in Section 3.4 "
        + "and must be included with all distributions of the Source Code. Except to the ex"
        + "tent prohibited by statute or regulation, such description must be sufficiently "
        + "detailed for a recipient of ordinary skill to be able to understand it.\n"
        + "\n"
        + "5. Application of this License.\n"
        + "\n"
        + "This License applies to code to which the Initial Developer has attached the not"
        + "ice in Exhibit A, and to related Covered Code.\n"
        + "\n"
        + "6. Versions of the License.\n"
        + "\n"
        + "     6.1. New Versions. License Author may publish revised and/or new versions o"
        + "f the License from time to time. Each version will be given a distinguishing ver"
        + "sion number and shall be submitted to opensource.org for certification.\n"
        + "\n"
        + "     6.2. Effect of New Versions. Once Covered Code has been published under a p"
        + "articular version of the License, You may always continue to use it under the te"
        + "rms of that version. You may also choose to use such Covered Code under the term"
        + "s of any subsequent version of the License published by Initial Developer. No on"
        + "e other than Initial Developer has the right to modify the terms applicable to C"
        + "overed Code created under this License.\n"
        + "\n"
        + "     6.3. Derivative Works. If you create or use a modified version of this Lice"
        + "nse, except in association with the required Developer Specific License describe"
        + "d in section 6.4, (which you may only do in order to apply it to code which is n"
        + "ot already Covered Code governed by this License), you must (a) rename Your lice"
        + "nse so that the phrases ``Open'', ``OpenPL'', ``OPL'' or any confusingly similar"
        + " phrase do not appear anywhere in your license and (b) otherwise make it clear t"
        + "hat your version of the license contains terms which differ from the Open Public"
        + " License. (Filling in the name of the Initial Developer, Original Code or Contri"
        + "butor in the notice described in Exhibit A shall not of themselves be deemed to "
        + "be modifications of this License.)\n"
        + "\n"
        + "     6.4. Required Additional Developer Specific License\n"
        + "This license is a union of the following two parts that should be found as text "
        + "files in the same place (directory), in the order of preeminence:\n"
        + "\n"
        + "          [1] A Developer specific license.\n"
        + "\n"
        + "          [2] The contents of this file OPL_1_0.TXT, stating the general licensi"
        + "ng policy of the software.\n"
        + "\n"
        + "In case of conflicting dispositions in the parts of this license, the terms of t"
        + "he lower-numbered part will always be superseded by the terms of the higher numb"
        + "ered part.\n"
        + "\n"
        + "7. DISCLAIMER OF WARRANTY.\n"
        + "\n"
        + "COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN \"AS IS\" BASIS, WITHOUT WARRANT"
        + "Y OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRA"
        + "NTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICUL"
        + "AR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE "
        + "OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY "
        + "RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COS"
        + "T OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY "
        + "CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUT"
        + "HORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.\n"
        + "\n"
        + "8. TERMINATION.\n"
        + "\n"
        + "     8.1 Termination upon Breach\n"
        + "This License and the rights granted hereunder will terminate automatically if Yo"
        + "u fail to comply with terms herein and fail to cure such breach within 30 days o"
        + "f becoming aware of the breach. All sublicenses to the Covered Code, which are p"
        + "roperly granted, shall survive any termination of this License. Provisions that,"
        + " by their nature, must remain in effect beyond the termination of this License s"
        + "hall survive.\n"
        + "\n"
        + "     8.2. Termination Upon Litigation. If You initiate litigation by asserting a"
        + " patent infringement claim (excluding declatory judgment actions) against Initia"
        + "l Developer or a Contributor (the Initial Developer or Contributor against whom "
        + "You file such action is referred to as \"Participant\") alleging that:\n"
        + "\n"
        + "          (a) such Participant's Contributor Version directly or indirectly infr"
        + "inges any patent, then any and all rights granted by such Participant to You und"
        + "er Sections 2.1 and/or 2.2 of this License shall, upon 60 days notice from Parti"
        + "cipant terminate prospectively, unless if within 60 days after receipt of notice"
        + " You either: (i) agree in writing to pay Participant a mutually agreeable reason"
        + "able royalty for Your past and future use of Modifications made by such Particip"
        + "ant, or (ii) withdraw Your litigation claim with respect to the Contributor Vers"
        + "ion against such Participant. If within 60 days of notice, a reasonable royalty "
        + "and payment arrangement are not mutually agreed upon in writing by the parties o"
        + "r the litigation claim is not withdrawn, the rights granted by Participant to Yo"
        + "u under Sections 2.1 and/or 2.2 automatically terminate at the expiration of the"
        + " 60 day notice period specified above.\n"
        + "\n"
        + "          (b) any software, hardware, or device, other than such Participant's C"
        + "ontributor Version, directly or indirectly infringes any patent, then any rights"
        + " granted to You by such Participant under Sections 2.1(b) and 2.2(b) are revoked"
        + " effective as of the date You first made, used, sold, distributed, or had made, "
        + "Modifications made by that Participant.\n"
        + "\n"
        + "     8.3. If You assert a patent infringement claim against Participant alleging"
        + " that such Participant's Contributor Version directly or indirectly infringes an"
        + "y patent where such claim is resolved (such as by license or settlement) prior t"
        + "o the initiation of patent infringement litigation, then the reasonable value of"
        + " the licenses granted by such Participant under Sections 2.1 or 2.2 shall be tak"
        + "en into account in determining the amount or value of any payment or license.\n"
        + "\n"
        + "     8.4. In the event of termination under Sections 8.1 or 8.2 above, all end u"
        + "ser license agreements (excluding distributors and resellers) which have been va"
        + "lidly granted by You or any distributor hereunder prior to termination shall sur"
        + "vive termination.\n"
        + "\n"
        + "9. LIMITATION OF LIABILITY.\n"
        + "\n"
        + "UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER TORT (INCLUDING NEGLIG"
        + "ENCE), CONTRACT, OR OTHERWISE, SHALL THE INITIAL DEVELOPER, ANY OTHER CONTRIBUTO"
        + "R, OR ANY DISTRIBUTOR OF COVERED CODE, OR ANY SUPPLIER OF ANY OF SUCH PARTIES, B"
        + "E LIABLE TO YOU OR ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CO"
        + "NSEQUENTIAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR "
        + "LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL"
        + " OTHER COMMERCIAL DAMAGES OR LOSSES, EVEN IF SUCH PARTY SHALL HAVE BEEN INFORMED"
        + " OF THE POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION OF LIABILITY SHALL NOT APPL"
        + "Y TO LIABILITY FOR DEATH OR PERSONAL INJURY RESULTING FROM SUCH PARTY'S NEGLIGEN"
        + "CE TO THE EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION. SOME JURISDICTIONS DO"
        + " NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, S"
        + "O THAT EXCLUSION AND LIMITATION MAY NOT APPLY TO YOU.\n"
        + "\n"
        + "10. U.S. GOVERNMENT END USERS.\n"
        + "\n"
        + "The Covered Code is a ``commercial item,'' as that term is defined in 48 C.F.R. "
        + "2.101 (Oct. 1995), consisting of ``commercial computer software'' and ``commerci"
        + "al computer software documentation,'' as such terms are used in 48 C.F.R. 12.212"
        + " (Sept. 1995). Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through"
        + " 227.7202-4 (June 1995), all U.S. Government End Users acquire Covered Code with"
        + " only those rights set forth herein.\n"
        + "\n"
        + "11. MISCELLANEOUS.\n"
        + "\n"
        + " his section was intentionally left blank. The contents of this section are foun"
        + "d in the corresponding addendum described above.\n"
        + "\n"
        + "12. RESPONSIBILITY FOR CLAIMS.\n"
        + "\n"
        + "Except in cases where another Contributor has failed to comply with Section 3.4,"
        + " You are responsible for damages arising, directly or indirectly, out of Your ut"
        + "ilization of rights under this License, based on the number of copies of Covered"
        + " Code you made available, the revenues you received from utilizing such rights, "
        + "and other relevant factors. You agree to work with affected parties to distribut"
        + "e with Initial Developer responsibility on an equitable basis.\n"
        + "\n"
        + "EXHIBIT A.\n"
        + "\n"
        + "Text for this Exhibit A is found in the corresponding addendum, described in sec"
        + "tion 6.4 above, text file provided by the Initial Developer. This license is not"
        + " valid or complete with out that file.\n"
        + "\n"
        + "EXHIBIT B.\n"
        + "\n"
        + "Text for this Exhibit B is found in the corresponding addendum, described in sec"
        + "tion 6.4 above, text file provided by the Initial Developer. This license is not"
        + " valid or complete with out that file. \n"
; // the license text
    }
 
    
}
