package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:18:20Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: RPL_1_1.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class RPL_1_1 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return true; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "RPL-1.1"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "Reciprocal Public License 1.1"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "Reciprocal Public License, version 1.1\n"
        + "\n"
        + "Copyright (C) 2001-2002 Technical Pursuit Inc., All Rights Reserved.\n"
        + "\n"
        + "PREAMBLE\n"
        + "\n"
        + "This Preamble is intended to describe, in plain English, the nature, intent, and"
        + " scope of this License. However, this Preamble is not a part of this License. Th"
        + "e legal effect of this License is dependent only upon the terms of the License a"
        + "nd not this Preamble.\n"
        + "\n"
        + "This License is based on the concept of reciprocity. In exchange for being grant"
        + "ed certain rights under the terms of this License to Licensor's Software, whose "
        + "Source Code You have access to, You are required to reciprocate by providing equ"
        + "al access and rights to all third parties to the Source Code of any Modification"
        + "s, Derivative Works, and Required Components for execution of same (collectively"
        + " defined as Extensions) that You Deploy by Deploying Your Extensions under the t"
        + "erms of this License. In this fashion the available Source Code related to the o"
        + "riginal Licensed Software is enlarged for the benefit of everyone.\n"
        + "\n"
        + "Under the terms of this License You may:\n"
        + "\n"
        + "a. Distribute the Licensed Software exactly as You received it under the terms o"
        + "f this License either alone or as a component of an aggregate software distribut"
        + "ion containing programs from several different sources without payment of a roya"
        + "lty or other fee.\n"
        + "\n"
        + "b. Use the Licensed Software for any purpose consistent with the rights granted "
        + "by this License, but the Licensor is not providing You any warranty whatsoever, "
        + "nor is the Licensor accepting any liability in the event that the Licensed Softw"
        + "are doesn't work properly or causes You any injury or damages.\n"
        + "\n"
        + "c. Create Extensions to the Licensed Software consistent with the rights granted"
        + " by this License, provided that You make the Source Code to any Extensions You D"
        + "eploy available to all third parties under the terms of this License, document Y"
        + "our Modifications clearly, and title all Extensions distinctly from the Licensed"
        + " Software.\n"
        + "\n"
        + "d. Charge a fee for warranty or support, or for accepting indemnity or liability"
        + " obligations for Your customers.\n"
        + "\n"
        + "Under the terms of this License You may not:\n"
        + "\n"
        + "a. Charge for the Source Code to the Licensed Software, or Your Extensions, othe"
        + "r than a nominal fee not to exceed Your cost for reproduction and distribution w"
        + "here such reproduction and distribution involve physical media.\n"
        + "\n"
        + "b. Modify or delete any pre-existing copyright notices, change notices, or Licen"
        + "se text in the Licensed Software.\n"
        + "\n"
        + "c. Assert any patent claims against the Licensor or Contributors, or which would"
        + " in any way restrict the ability of any third party to use the Licensed Software"
        + " or portions thereof in any form under the terms of this License, or Your rights"
        + " to the Licensed Software under this License automatically terminate.\n"
        + "\n"
        + "d. Represent either expressly or by implication, appearance, or otherwise that Y"
        + "ou represent Licensor or \n"
        + "\n"
        + "Contributors in any capacity or that You have any form of legal association by v"
        + "irtue of this License.\n"
        + "\n"
        + "Under the terms of this License You must:\n"
        + "\n"
        + "a. Document any Modifications You make to the Licensed Software including the na"
        + "ture of the change, the authors of the change, and the date of the change. This "
        + "documentation must appear both in the Source Code and in a text file titled \"CHA"
        + "NGES\" distributed with the Licensed Software and Your Extensions.\n"
        + "\n"
        + "b. Make the Source Code for any Extensions You Deploy available in a timely fash"
        + "ion via an Electronic Distribution Mechanism such as FTP or HTTP download.\n"
        + "\n"
        + "c. Notify the Licensor of the availability of Source Code to Your Extensions in "
        + "a timely fashion and include in such notice a brief description of the Extension"
        + "s, the distinctive title used, and instructions on how to acquire the Source Cod"
        + "e and future updates.\n"
        + "\n"
        + "d. Grant Licensor and all third parties a world-wide, non-exclusive, royalty-fre"
        + "e license under any intellectual property rights owned or controlled by You to u"
        + "se, reproduce, display, perform, modify, sublicense, and distribute Your Extensi"
        + "ons, in any form, under the terms of this License.\n"
        + "\n"
        + "LICENSE TERMS\n"
        + "\n"
        + "1.0 General; Applicability & Definitions. This Reciprocal Public License Version"
        + " 1.1 (\"License\") applies to any programs or other works as well as any and all u"
        + "pdates or maintenance releases of said programs or works (\"Software\") not alread"
        + "y covered by this License which the Software copyright holder (\"Licensor\") makes"
        + " publicly available containing a Notice (hereinafter defined) from the Licensor "
        + "specifying or allowing use or distribution under the terms of this License. As u"
        + "sed in this License and Preamble:\n"
        + "\n"
        + "     1.1 \"Contributor\" means any person or entity who created or contributed to "
        + "the creation of an Extension.\n"
        + "\n"
        + "     1.2 \"Deploy\" means to use, Serve, sublicense or distribute Licensed Softwar"
        + "e other than for Your internal Research and/or Personal Use, and includes withou"
        + "t limitation, any and all internal use or distribution of Licensed Software with"
        + "in Your business or organization other than for Research and/or Personal Use, as"
        + " well as direct or indirect sublicensing or distribution of Licensed Software by"
        + " You to any third party in any form or manner.\n"
        + "\n"
        + "     1.3 \"Derivative Works\" as used in this License is defined under U.S. copyri"
        + "ght law.\n"
        + "\n"
        + "     1.4 \"Electronic Distribution Mechanism\" means a mechanism generally accepte"
        + "d in the software development community for the electronic transfer of data such"
        + " as download from an FTP or web site, where such mechanism is publicly accessibl"
        + "e.\n"
        + "\n"
        + "     1.5 \"Extensions\" means any Modifications, Derivative Works, or Required Com"
        + "ponents as those terms are defined in this License.\n"
        + "\n"
        + "     1.6 \"License\" means this Reciprocal Public License.\n"
        + "\n"
        + "     1.7 \"Licensed Software\" means any Software licensed pursuant to this Licens"
        + "e. Licensed Software also includes all previous Extensions from any Contributor "
        + "that You receive.\n"
        + "\n"
        + "     1.8 \"Licensor\" means the copyright holder of any Software previously uncove"
        + "red by this License who releases the Software under the terms of this License.\n"
        + "\n"
        + "     1.9 \"Modifications\" means any additions to or deletions from the substance "
        + "or structure of (i) a file or other storage containing Licensed Software, or (ii"
        + ") any new file or storage that contains any part of Licensed Software, or (iii) "
        + "any file or storage which replaces or otherwise alters the original functionalit"
        + "y of Licensed Software at runtime.\n"
        + "\n"
        + "     1.10 \"Notice\" means the notice contained in EXHIBIT A.\n"
        + "\n"
        + "     1.11 \"Personal Use\" means use of Licensed Software by an individual solely "
        + "for his or her personal, private and non-commercial purposes. An individual's us"
        + "e of Licensed Software in his or her capacity as an officer, employee, member, i"
        + "ndependent contractor or agent of a corporation, business or organization (comme"
        + "rcial or non-commercial) does not qualify as Personal Use.\n"
        + "\n"
        + "     1.12 \"Required Components\" means any text, programs, scripts, schema, inter"
        + "face definitions, control files, or other works created by You which are require"
        + "d by a third party of average skill to successfully install and run Licensed Sof"
        + "tware containing Your Modifications, or to install and run Your Derivative Works"
        + ".\n"
        + "\n"
        + "     1.13 \"Research\" means investigation or experimentation for the purpose of u"
        + "nderstanding the nature and limits of the Licensed Software and its potential us"
        + "es.\n"
        + "\n"
        + "     1.14 \"Serve\" means to deliver Licensed Software and/or Your Extensions by m"
        + "eans of a computer network to one or more computers for purposes of execution of"
        + " Licensed Software and/or Your Extensions.\n"
        + "\n"
        + "     1.15 \"Software\" means any computer programs or other works as well as any u"
        + "pdates or maintenance releases of those programs or works which are distributed "
        + "publicly by Licensor.\n"
        + "\n"
        + "     1.16 \"Source Code\" means the preferred form for making modifications to the"
        + " Licensed Software and/or Your Extensions, including all modules contained there"
        + "in, plus any associated text, interface definition files, scripts used to contro"
        + "l compilation and installation of an executable program or other components requ"
        + "ired by a third party of average skill to build a running version of the License"
        + "d Software or Your Extensions.\n"
        + "\n"
        + "     1.17 \"You\" or \"Your\" means an individual or a legal entity exercising right"
        + "s under this License. For legal entities, \"You\" or \"Your\" includes any entity wh"
        + "ich controls, is controlled by, or is under common control with, You, where \"con"
        + "trol\" means (a) the power, direct or indirect, to cause the direction or managem"
        + "ent of such entity, whether by contract or otherwise, or (b) ownership of fifty "
        + "percent (50%) or more of the outstanding shares or beneficial ownership of such "
        + "entity.\n"
        + "\n"
        + "2.0 Acceptance Of License. You are not required to accept this License since you"
        + " have not signed it, however nothing else grants you permission to use, copy, di"
        + "stribute, modify, or create derivatives of either the Software or any Extensions"
        + " created by a Contributor. These actions are prohibited by law if you do not acc"
        + "ept this License. Therefore, by performing any of these actions You indicate You"
        + "r acceptance of this License and Your agreement to be bound by all its terms and"
        + " conditions. IF YOU DO NOT AGREE WITH ALL THE TERMS AND CONDITIONS OF THIS LICEN"
        + "SE DO NOT USE, MODIFY, CREATE DERIVATIVES, OR DISTRIBUTE THE SOFTWARE. IF IT IS "
        + "IMPOSSIBLE FOR YOU TO COMPLY WITH ALL THE TERMS AND CONDITIONS OF THIS LICENSE T"
        + "HEN YOU CAN NOT USE, MODIFY, CREATE DERIVATIVES, OR DISTRIBUTE THE SOFTWARE.\n"
        + "\n"
        + "3.0 Grant of License From Licensor. Subject to the terms and conditions of this "
        + "License, Licensor hereby grants You a world-wide, royalty-free, non-exclusive li"
        + "cense, subject to Licensor's intellectual property rights, and any third party i"
        + "ntellectual property claims derived from the Licensed Software under this Licens"
        + "e, to do the following:\n"
        + "\n"
        + "     3.1 Use, reproduce, modify, display, perform, sublicense and distribute Lic"
        + "ensed Software and Your Extensions in both Source Code form or as an executable "
        + "program.\n"
        + "\n"
        + "     3.2 Create Derivative Works (as that term is defined under U.S. copyright l"
        + "aw) of Licensed Software by adding to or deleting from the substance or structur"
        + "e of said Licensed Software.\n"
        + "\n"
        + "     3.3 Under claims of patents now or hereafter owned or controlled by Licenso"
        + "r, to make, use, have made, and/or otherwise dispose of Licensed Software or por"
        + "tions thereof, but solely to the extent that any such claim is necessary to enab"
        + "le You to make, use, have made, and/or otherwise dispose of Licensed Software or"
        + " portions thereof.\n"
        + "\n"
        + "     3.4 Licensor reserves the right to release new versions of the Software wit"
        + "h different features, specifications, capabilities, functions, licensing terms, "
        + "general availability or other characteristics. Title, ownership rights, and inte"
        + "llectual property rights in and to the Licensed Software shall remain in Licenso"
        + "r and/or its Contributors.\n"
        + "\n"
        + "4.0 Grant of License From Contributor. By application of the provisions in Secti"
        + "on 6 below, each Contributor hereby grants You a world-wide, royalty-free, non-e"
        + "xclusive license, subject to said Contributor's intellectual property rights, an"
        + "d any third party intellectual property claims derived from the Licensed Softwar"
        + "e under this License, to do the following:\n"
        + "\n"
        + "     4.1 Use, reproduce, modify, display, perform, sublicense and distribute any"
        + " Extensions Deployed by such Contributor or portions thereof, in both Source Cod"
        + "e form or as an executable program, either on an unmodified basis or as part of "
        + "Derivative Works.\n"
        + "\n"
        + "     4.2 Under claims of patents now or hereafter owned or controlled by Contrib"
        + "utor, to make, use, have made, and/or otherwise dispose of Extensions or portion"
        + "s thereof, but solely to the extent that any such claim is necessary to enable Y"
        + "ou to make, use, have made, and/or otherwise dispose of Contributor's Extensions"
        + " or portions thereof.\n"
        + "\n"
        + "5.0 Exclusions From License Grant. Nothing in this License shall be deemed to gr"
        + "ant any rights to trademarks, copyrights, patents, trade secrets or any other in"
        + "tellectual property of Licensor or any Contributor except as expressly stated he"
        + "rein. Except as expressly stated in Sections 3 and 4, no other patent rights, ex"
        + "press or implied, are granted herein. Your Extensions may require additional pat"
        + "ent licenses from Licensor or Contributors which each may grant in its sole disc"
        + "retion. No right is granted to the trademarks of Licensor or any Contributor eve"
        + "n if such marks are included in the Licensed Software. Nothing in this License s"
        + "hall be interpreted to prohibit Licensor from licensing under different terms fr"
        + "om this License any code that Licensor otherwise would have a right to license.\n"
        + "\n"
        + "     5.1 You expressly acknowledge and agree that although Licensor and each Con"
        + "tributor grants the licenses to their respective portions of the Licensed Softwa"
        + "re set forth herein, no assurances are provided by Licensor or any Contributor t"
        + "hat the Licensed Software does not infringe the patent or other intellectual pro"
        + "perty rights of any other entity. Licensor and each Contributor disclaim any lia"
        + "bility to You for claims brought by any other entity based on infringement of in"
        + "tellectual property rights or otherwise. As a condition to exercising the rights"
        + " and licenses granted hereunder, You hereby assume sole responsibility to secure"
        + " any other intellectual property rights needed, if any. For example, if a third "
        + "party patent license is required to allow You to distribute the Licensed Softwar"
        + "e, it is Your responsibility to acquire that license before distributing the Lic"
        + "ensed Software.\n"
        + "\n"
        + "6.0 Your Obligations And Grants. In consideration of, and as an express conditio"
        + "n to, the licenses granted to You under this License You hereby agree that any M"
        + "odifications, Derivative Works, or Required Components (collectively Extensions)"
        + " that You create or to which You contribute are governed by the terms of this Li"
        + "cense including, without limitation, Section 4. Any Extensions that You create o"
        + "r to which You contribute must be Deployed under the terms of this License or a "
        + "future version of this License released under Section 7. You hereby grant to Lic"
        + "ensor and all third parties a world-wide, non-exclusive, royalty-free license un"
        + "der those intellectual property rights You own or control to use, reproduce, dis"
        + "play, perform, modify, create derivatives, sublicense, and distribute Your Exten"
        + "sions, in any form. Any Extensions You make and Deploy must have a distinct titl"
        + "e so as to readily tell any subsequent user or Contributor that the Extensions a"
        + "re by You. You must include a copy of this License with every copy of the Extens"
        + "ions You distribute. You agree not to offer or impose any terms on any Source Co"
        + "de or executable version of the Licensed Software, or its Extensions that alter "
        + "or restrict the applicable version of this License or the recipients' rights her"
        + "eunder.\n"
        + "\n"
        + "     6.1 Availability of Source Code. You must make available, under the terms o"
        + "f this License, the Source Code of the Licensed Software and any Extensions that"
        + " You Deploy, either on the same media as You distribute any executable or other "
        + "form of the Licensed Software, or via an Electronic Distribution Mechanism. The "
        + "Source Code for any version of Licensed Software, or its Extensions that You Dep"
        + "loy must be made available at the time of Deployment and must remain available f"
        + "or as long as You Deploy the Extensions or at least twelve (12) months after the"
        + " date You Deploy, whichever is longer. You are responsible for ensuring that the"
        + " Source Code version remains available even if the Electronic Distribution Mecha"
        + "nism is maintained by a third party. You may not charge a fee for the Source Cod"
        + "e distributed under this Section in excess of Your actual cost of duplication an"
        + "d distribution where such duplication and distribution involve physical media.\n"
        + "\n"
        + "     6.2 Description of Modifications. You must cause any Modifications that You"
        + " create or to which You contribute, to update the file titled \"CHANGES\" distribu"
        + "ted with Licensed Software documenting the additions, changes or deletions You m"
        + "ade, the authors of such Modifications, and the dates of any such additions, cha"
        + "nges or deletions. You must also cause a cross-reference to appear in the Source"
        + " Code at the location of each change. You must include a prominent statement tha"
        + "t the Modifications are derived, directly or indirectly, from the Licensed Softw"
        + "are and include the names of the Licensor and any Contributor to the Licensed So"
        + "ftware in (i) the Source Code and (ii) in any notice displayed by the Licensed S"
        + "oftware You distribute or in related documentation in which You describe the ori"
        + "gin or ownership of the Licensed Software. You may not modify or delete any pre-"
        + "existing copyright notices, change notices or License text in the Licensed Softw"
        + "are.\n"
        + "\n"
        + "     6.3 Intellectual Property Matters.\n"
        + "\n"
        + "          a. Third Party Claims. If You have knowledge that a license to a third"
        + " party's intellectual property right is required to exercise the rights granted "
        + "by this License, You must include a text file with the Source Code distribution "
        + "titled \"LEGAL\" that describes the claim and the party making the claim in suffic"
        + "ient detail that a recipient will know whom to contact. If You obtain such knowl"
        + "edge after You make any Extensions available as described in Section 6.1, You sh"
        + "all promptly modify the LEGAL file in all copies You make available thereafter a"
        + "nd shall take other steps (such as notifying appropriate mailing lists or newsgr"
        + "oups) reasonably calculated to inform those who received the Licensed Software f"
        + "rom You that new knowledge has been obtained.\n"
        + "\n"
        + "          b. Contributor APIs. If Your Extensions include an application program"
        + "ming interface (\"API\") and You have knowledge of patent licenses that are reason"
        + "ably necessary to implement that API, You must also include this information in "
        + "the LEGAL file.\n"
        + "\n"
        + "          c. Representations. You represent that, except as disclosed pursuant t"
        + "o 6.3(a) above, You believe that any Extensions You distribute are Your original"
        + " creations and that You have sufficient rights to grant the rights conveyed by t"
        + "his License.\n"
        + "\n"
        + "     6.4 Required Notices.\n"
        + "\n"
        + "          a. License Text. You must duplicate this License in any documentation "
        + "You provide along with the Source Code of any Extensions You create or to which "
        + "You contribute, wherever You describe recipients' rights relating to Licensed So"
        + "ftware. You must duplicate the notice contained in EXHIBIT A (the \"Notice\") in e"
        + "ach file of the Source Code of any copy You distribute of the Licensed Software "
        + "and Your Extensions. If You create an Extension, You may add Your name as a Cont"
        + "ributor to the text file titled \"CONTRIB\" distributed with the Licensed Software"
        + " along with a description of the contribution. If it is not possible to put the "
        + "Notice in a particular Source Code file due to its structure, then You must incl"
        + "ude such Notice in a location (such as a relevant directory file) where a user w"
        + "ould be likely to look for such a notice.\n"
        + "\n"
        + "          b. Source Code Availability. You must notify Licensor within one (1) m"
        + "onth of the date You initially Deploy of the availability of Source Code to Your"
        + " Extensions and include in such notification the name under which you Deployed Y"
        + "our Extensions, a description of the Extensions, and instructions on how to acqu"
        + "ire the Source Code, including instructions on how to acquire updates over time."
        + " Should such instructions change you must provide Licensor with revised instruct"
        + "ions within one (1) month of the date of change. Should you be unable to notify "
        + "Licensor directly, you must provide notification by posting to appropriate news "
        + "groups, mailing lists, or web sites where a search engine would reasonably be ex"
        + "pected to index them.\n"
        + "\n"
        + "     6.5 Additional Terms. You may choose to offer, and charge a fee for, warran"
        + "ty, support, indemnity or liability obligations to one or more recipients of Lic"
        + "ensed Software. However, You may do so only on Your own behalf, and not on behal"
        + "f of the Licensor or any Contributor. You must make it clear that any such warra"
        + "nty, support, indemnity or liability obligation is offered by You alone, and You"
        + " hereby agree to indemnify the Licensor and every Contributor for any liability "
        + "plus attorney fees, costs, and related expenses due to any such action or claim "
        + "incurred by the Licensor or such Contributor as a result of warranty, support, i"
        + "ndemnity or liability terms You offer.\n"
        + "\n"
        + "     6.6 Conflicts With Other Licenses. Where any portion of Your Extensions, by"
        + " virtue of being Derivative Works of another product or similar circumstance, fa"
        + "ll under the terms of another license, the terms of that license should be honor"
        + "ed however You must also make Your Extensions available under this License. If t"
        + "he terms of this License continue to conflict with the terms of the other licens"
        + "e you may write the Licensor for permission to resolve the conflict in a fashion"
        + " that remains consistent with the intent of this License. Such permission will b"
        + "e granted at the sole discretion of the Licensor.\n"
        + "\n"
        + "7.0 Versions of This License. Licensor may publish from time to time revised and"
        + "/or new versions of the License. Once Licensed Software has been published under"
        + " a particular version of the License, You may always continue to use it under th"
        + "e terms of that version. You may also choose to use such Licensed Software under"
        + " the terms of any subsequent version of the License published by Licensor. No on"
        + "e other than Licensor has the right to modify the terms applicable to Licensed S"
        + "oftware created under this License.\n"
        + "\n"
        + "     7.1 If You create or use a modified version of this License, which You may "
        + "do only in order to apply it to software that is not already Licensed Software u"
        + "nder this License, You must rename Your license so that it is not confusingly si"
        + "milar to this License, and must make it clear that Your license contains terms t"
        + "hat differ from this License. In so naming Your license, You may not use any tra"
        + "demark of Licensor or of any Contributor. Should Your modifications to this Lice"
        + "nse be limited to alteration of EXHIBIT A purely for purposes of adjusting the N"
        + "otice You require of licensees, You may continue to refer to Your License as the"
        + " Reciprocal Public License or simply the RPL.\n"
        + "\n"
        + "8.0 Disclaimer of Warranty. LICENSED SOFTWARE IS PROVIDED UNDER THIS LICENSE ON "
        + "AN \"AS IS\" BASIS, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLU"
        + "DING, WITHOUT LIMITATION, WARRANTIES THAT THE LICENSED SOFTWARE IS FREE OF DEFEC"
        + "TS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. FURTHER THERE "
        + "IS NO WARRANTY MADE AND ALL IMPLIED WARRANTIES ARE DISCLAIMED THAT THE LICENSED "
        + "SOFTWARE MEETS OR COMPLIES WITH ANY DESCRIPTION OF PERFORMANCE OR OPERATION, SAI"
        + "D COMPATIBILITY AND SUITABILITY BEING YOUR RESPONSIBILITY. LICENSOR DISCLAIMS AN"
        + "Y WARRANTY, IMPLIED OR EXPRESSED, THAT ANY CONTRIBUTOR'S EXTENSIONS MEET ANY STA"
        + "NDARD OF COMPATIBILITY OR DESCRIPTION OF PERFORMANCE. THE ENTIRE RISK AS TO THE "
        + "QUALITY AND PERFORMANCE OF THE LICENSED SOFTWARE IS WITH YOU. SHOULD LICENSED SO"
        + "FTWARE PROVE DEFECTIVE IN ANY RESPECT, YOU (AND NOT THE LICENSOR OR ANY OTHER CO"
        + "NTRIBUTOR) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION. UND"
        + "ER THE TERMS OF THIS LICENSOR WILL NOT SUPPORT THIS SOFTWARE AND IS UNDER NO OBL"
        + "IGATION TO ISSUE UPDATES TO THIS SOFTWARE. LICENSOR HAS NO KNOWLEDGE OF ERRANT C"
        + "ODE OR VIRUS IN THIS SOFTWARE, BUT DOES NOT WARRANT THAT THE SOFTWARE IS FREE FR"
        + "OM SUCH ERRORS OR VIRUSES. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL "
        + "PART OF THIS LICENSE. NO USE OF LICENSED SOFTWARE IS AUTHORIZED HEREUNDER EXCEPT"
        + " UNDER THIS DISCLAIMER.\n"
        + "\n"
        + "9.0 Limitation of Liability. UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, W"
        + "HETHER TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE, SHALL THE LICENSOR, "
        + "ANY CONTRIBUTOR, OR ANY DISTRIBUTOR OF LICENSED SOFTWARE, OR ANY SUPPLIER OF ANY"
        + " OF SUCH PARTIES, BE LIABLE TO ANY PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL,"
        + " OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGE"
        + "S FOR LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY A"
        + "ND ALL OTHER COMMERCIAL DAMAGES OR LOSSES, EVEN IF SUCH PARTY SHALL HAVE BEEN IN"
        + "FORMED OF THE POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION OF LIABILITY SHALL NO"
        + "T APPLY TO LIABILITY FOR DEATH OR PERSONAL INJURY RESULTING FROM SUCH PARTY'S NE"
        + "GLIGENCE TO THE EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION. SOME JURISDICTI"
        + "ONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMA"
        + "GES, SO THIS EXCLUSION AND LIMITATION MAY NOT APPLY TO YOU.\n"
        + "\n"
        + "10.0 High Risk Activities. THE LICENSED SOFTWARE IS NOT FAULT-TOLERANT AND IS NO"
        + "T DESIGNED, MANUFACTURED, OR INTENDED FOR USE OR DISTRIBUTION AS ON-LINE CONTROL"
        + " EQUIPMENT IN HAZARDOUS ENVIRONMENTS REQUIRING FAIL-SAFE PERFORMANCE, SUCH AS IN"
        + " THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT NAVIGATION OR COMMUNICATIONS SYST"
        + "EMS, AIR TRAFFIC CONTROL, DIRECT LIFE SUPPORT MACHINES, OR WEAPONS SYSTEMS, IN W"
        + "HICH THE FAILURE OF THE LICENSED SOFTWARE COULD LEAD DIRECTLY TO DEATH, PERSONAL"
        + " INJURY, OR SEVERE PHYSICAL OR ENVIRONMENTAL DAMAGE (\"HIGH RISK ACTIVITIES\"). LI"
        + "CENSOR AND CONTRIBUTORS SPECIFICALLY DISCLAIM ANY EXPRESS OR IMPLIED WARRANTY OF"
        + " FITNESS FOR HIGH RISK ACTIVITIES.\n"
        + "\n"
        + "11.0 Responsibility for Claims. As between Licensor and Contributors, each party"
        + " is responsible for claims and damages arising, directly or indirectly, out of i"
        + "ts utilization of rights under this License which specifically disclaims warrant"
        + "ies and limits any liability of the Licensor. This paragraph is to be used in co"
        + "njunction with and controlled by the Disclaimer Of Warranties of Section 8, the "
        + "Limitation Of Damages in Section 9, and the disclaimer against use for High Risk"
        + " Activities in Section 10. The Licensor has thereby disclaimed all warranties an"
        + "d limited any damages that it is or may be liable for. You agree to work with Li"
        + "censor and Contributors to distribute such responsibility on an equitable basis "
        + "consistent with the terms of this License including Sections 8, 9, and 10. Nothi"
        + "ng herein is intended or shall be deemed to constitute any admission of liabilit"
        + "y.\n"
        + "\n"
        + "12.0 Termination. This License and all rights granted hereunder will terminate i"
        + "mmediately in the event of the circumstances described in Section 13.6 or if app"
        + "licable law prohibits or restricts You from fully and or specifically complying "
        + "with Sections 3, 4 and/or 6, or prevents the enforceability of any of those Sect"
        + "ions, and You must immediately discontinue any use of Licensed Software.\n"
        + "\n"
        + "     12.1 Automatic Termination Upon Breach. This License and the rights granted"
        + " hereunder will terminate automatically if You fail to comply with the terms her"
        + "ein and fail to cure such breach within thirty (30) days of becoming aware of th"
        + "e breach. All sublicenses to the Licensed Software that are properly granted sha"
        + "ll survive any termination of this License. Provisions that, by their nature, mu"
        + "st remain in effect beyond the termination of this License, shall survive.\n"
        + "\n"
        + "     12.2 Termination Upon Assertion of Patent Infringement. If You initiate lit"
        + "igation by asserting a patent infringement claim (excluding declaratory judgment"
        + " actions) against Licensor or a Contributor (Licensor or Contributor against who"
        + "m You file such an action is referred to herein as \"Respondent\") alleging that L"
        + "icensed Software directly or indirectly infringes any patent, then any and all r"
        + "ights granted by such Respondent to You under Sections 3 or 4 of this License sh"
        + "all terminate prospectively upon sixty (60) days notice from Respondent (the \"No"
        + "tice Period\") unless within that Notice Period You either agree in writing (i) t"
        + "o pay Respondent a mutually agreeable reasonably royalty for Your past or future"
        + " use of Licensed Software made by such Respondent, or (ii) withdraw Your litigat"
        + "ion claim with respect to Licensed Software against such Respondent. If within s"
        + "aid Notice Period a reasonable royalty and payment arrangement are not mutually "
        + "agreed upon in writing by the parties or the litigation claim is not withdrawn, "
        + "the rights granted by Licensor to You under Sections 3 and 4 automatically termi"
        + "nate at the expiration of said Notice Period.\n"
        + "\n"
        + "     12.3 Reasonable Value of This License. If You assert a patent infringement "
        + "claim against Respondent alleging that Licensed Software directly or indirectly "
        + "infringes any patent where such claim is resolved (such as by license or settlem"
        + "ent) prior to the initiation of patent infringement litigation, then the reasona"
        + "ble value of the licenses granted by said Respondent under Sections 3 and 4 shal"
        + "l be taken into account in determining the amount or value of any payment or lic"
        + "ense.\n"
        + "\n"
        + "     12.4 No Retroactive Effect of Termination. In the event of termination unde"
        + "r this Section all end user license agreements (excluding licenses to distributo"
        + "rs and resellers) that have been validly granted by You or any distributor hereu"
        + "nder prior to termination shall survive termination.\n"
        + "\n"
        + "13.0 Miscellaneous.\n"
        + "\n"
        + "     13.1 U.S. Government End Users. The Licensed Software is a \"commercial item"
        + ",\" as that term is defined in 48 C.F.R. 2.101 (Oct. 1995), consisting of \"commer"
        + "cial computer software\" and \"commercial computer software documentation,\" as suc"
        + "h terms are used in 48 C.F.R. 12.212 (Sept. 1995). Consistent with 48 C.F.R. 12."
        + "212 and 48 C.F.R. 227.7202-1 through 227.7202-4 (June 1995), all U.S. Government"
        + " End Users acquire Licensed Software with only those rights set forth herein.\n"
        + "\n"
        + "     13.2 Relationship of Parties. This License will not be construed as creatin"
        + "g an agency, partnership, joint venture, or any other form of legal association "
        + "between or among You, Licensor, or any Contributor, and You will not represent t"
        + "o the contrary, whether expressly, by implication, appearance, or otherwise.\n"
        + "\n"
        + "     13.3 Independent Development. Nothing in this License will impair Licensor'"
        + "s right to acquire, license, develop, subcontract, market, or distribute technol"
        + "ogy or products that perform the same or similar functions as, or otherwise comp"
        + "ete with, Extensions that You may develop, produce, market, or distribute.\n"
        + "\n"
        + "     13.4 Consent To Breach Not Waiver. Failure by Licensor or Contributor to en"
        + "force any provision of this License will not be deemed a waiver of future enforc"
        + "ement of that or any other provision.\n"
        + "\n"
        + "     13.5 Severability. This License represents the complete agreement concernin"
        + "g the subject matter hereof. If any provision of this License is held to be unen"
        + "forceable, such provision shall be reformed only to the extent necessary to make"
        + " it enforceable.\n"
        + "\n"
        + "     13.6 Inability to Comply Due to Statute or Regulation. If it is impossible "
        + "for You to comply with any of the terms of this License with respect to some or "
        + "all of the Licensed Software due to statute, judicial order, or regulation, then"
        + " You cannot use, modify, or distribute the software.\n"
        + "\n"
        + "     13.7 Export Restrictions. You may be restricted with respect to downloading"
        + " or otherwise acquiring, exporting, or reexporting the Licensed Software or any "
        + "underlying information or technology by United States and other applicable laws "
        + "and regulations. By downloading or by otherwise obtaining the Licensed Software,"
        + " You are agreeing to be responsible for compliance with all applicable laws and "
        + "regulations.\n"
        + "\n"
        + "     13.8 Arbitration, Jurisdiction & Venue. This License shall be governed by C"
        + "olorado law provisions (except to the extent applicable law, if any, provides ot"
        + "herwise), excluding its conflict-of-law provisions. You expressly agree that any"
        + " dispute relating to this License shall be submitted to binding arbitration unde"
        + "r the rules then prevailing of the American Arbitration Association. You further"
        + " agree that Adams County, Colorado USA is proper venue and grant such arbitratio"
        + "n proceeding jurisdiction as may be appropriate for purposes of resolving any di"
        + "spute under this License. Judgement upon any award made in arbitration may be en"
        + "tered and enforced in any court of competent jurisdiction. The arbitrator shall "
        + "award attorney's fees and costs of arbitration to the prevailing party. Should e"
        + "ither party find it necessary to enforce its arbitration award or seek specific "
        + "performance of such award in a civil court of competent jurisdiction, the prevai"
        + "ling party shall be entitled to reasonable attorney's fees and costs. The applic"
        + "ation of the United Nations Convention on Contracts for the International Sale o"
        + "f Goods is expressly excluded. You and Licensor expressly waive any rights to a "
        + "jury trial in any litigation concerning Licensed Software or this License. Any l"
        + "aw or regulation that provides that the language of a contract shall be construe"
        + "d against the drafter shall not apply to this License.\n"
        + "\n"
        + "     13.9 Entire Agreement. This License constitutes the entire agreement betwee"
        + "n the parties with respect to the subject matter hereof.\n"
        + "\n"
        + "EXHIBIT A\n"
        + "\n"
        + "The Notice below must appear in each file of the Source Code of any copy You dis"
        + "tribute of the Licensed Software or any Extensions thereto, except as may be mod"
        + "ified as allowed under the terms of Section 7.1\n"
        + "Copyright (C) 1999-2002 Technical Pursuit Inc., All Rights Reserved. Patent Pend"
        + "ing, Technical Pursuit Inc.\n"
        + "\n"
        + "Unless explicitly acquired and licensed from Licensor under the Technical Pursui"
        + "t License (\"TPL\") Version 1.0 or greater, the contents of this file are subject "
        + "to the Reciprocal Public License (\"RPL\") Version 1.1, or subsequent versions as "
        + "allowed by the RPL, and You may not copy or use this file in either source code "
        + "or executable form, except in compliance with the terms and conditions of the RP"
        + "L.\n"
        + "You may obtain a copy of both the TPL and the RPL (the \"Licenses\") from Technica"
        + "l Pursuit Inc. at http://www.technicalpursuit.com.\n"
        + "\n"
        + "All software distributed under the Licenses is provided strictly on an \"AS IS\" b"
        + "asis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND TECHNICAL PUR"
        + "SUIT INC. HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, AN"
        + "Y WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYME"
        + "NT, OR NON-INFRINGEMENT. See the Licenses for specific language governing rights"
        + " and limitations under the Licenses.\n"
; // the license text
    }
 
    
}
