package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:18:19Z
 * LicenseName: EUPL-1.1-without-appendix
 * FileName: RPSL_1_0.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class RPSL_1_0 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return true; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "RPSL-1.0"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "RealNetworks Public Source License v1.0"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "RealNetworks Public Source License Version 1.0\n"
        + "\n"
        + "(Rev. Date October 28, 2002)\n"
        + "\n"
        + "1. General Definitions. This License applies to any program or other work which "
        + "RealNetworks, Inc., or any other entity that elects to use this license, (\"Licen"
        + "sor\") makes publicly available and which contains a notice placed by Licensor id"
        + "entifying such program or work as \"Original Code\" and stating that it is subject"
        + " to the terms of this RealNetworks Public Source License version 1.0 (or subsequ"
        + "ent version thereof) (\"License\"). You are not required to accept this License. H"
        + "owever, nothing else grants You permission to use, copy, modify or distribute th"
        + "e software or its derivative works. These actions are prohibited by law if You d"
        + "o not accept this License. Therefore, by modifying, copying or distributing the "
        + "software (or any work based on the software), You indicate your acceptance of th"
        + "is License to do so, and all its terms and conditions. In addition, you agree to"
        + " the terms of this License by clicking the Accept button or downloading the soft"
        + "ware. As used in this License:\n"
        + "\n"
        + "     1.1 \"Applicable Patent Rights\" mean: (a) in the case where Licensor is the "
        + "grantor of rights, claims of patents that (i) are now or hereafter acquired, own"
        + "ed by or assigned to Licensor and (ii) are necessarily infringed by using or mak"
        + "ing the Original Code alone and not in combination with other software or hardwa"
        + "re; and (b) in the case where You are the grantor of rights, claims of patents t"
        + "hat (i) are now or hereafter acquired, owned by or assigned to You and (ii) are "
        + "infringed (directly or indirectly) by using or making Your Modifications, taken "
        + "alone or in combination with Original Code.\n"
        + "\n"
        + "     1.2 \"Compatible Source License\" means any one of the licenses listed on Exh"
        + "ibit B or at https://www.helixcommunity.org/content/complicense or other license"
        + "s specifically identified by Licensor in writing. Notwithstanding any term to th"
        + "e contrary in any Compatible Source License, any code covered by any Compatible "
        + "Source License that is used with Covered Code must be made readily available in "
        + "Source Code format for royalty-free use under the terms of the Compatible Source"
        + " License or this License.\n"
        + "\n"
        + "     1.3 \"Contributor\" means any person or entity that creates or contributes to"
        + " the creation of Modifications.\n"
        + "\n"
        + "     1.4 \"Covered Code\" means the Original Code, Modifications, the combination "
        + "of Original Code and any Modifications, and/or any respective portions thereof.\n"
        + "\n"
        + "     1.5 \"Deploy\" means to use, sublicense or distribute Covered Code other than"
        + " for Your internal research and development (R&D) and/or Personal Use, and inclu"
        + "des without limitation, any and all internal use or distribution of Covered Code"
        + " within Your business or organization except for R&D use and/or Personal Use, as"
        + " well as direct or indirect sublicensing or distribution of Covered Code by You "
        + "to any third party in any form or manner.\n"
        + "\n"
        + "     1.6 \"Derivative Work\" means either the Covered Code or any derivative work "
        + "under United States copyright law, and including any work containing or includin"
        + "g any portion of the Covered Code or Modifications, either verbatim or with modi"
        + "fications and/or translated into another language. Derivative Work also includes"
        + " any work which combines any portion of Covered Code or Modifications with code "
        + "not otherwise governed by the terms of this License.\n"
        + "\n"
        + "     1.7 \"Externally Deploy\" means to Deploy the Covered Code in any way that ma"
        + "y be accessed or used by anyone other than You, used to provide any services to "
        + "anyone other than You, or used in any way to deliver any content to anyone other"
        + " than You, whether the Covered Code is distributed to those parties, made availa"
        + "ble as an application intended for use over a computer network, or used to provi"
        + "de services or otherwise deliver content to anyone other than You.\n"
        + "\n"
        + "     1.8. \"Interface\" means interfaces, functions, properties, class definitions"
        + ", APIs, header files, GUIDs, V-Tables, and/or protocols allowing one piece of so"
        + "ftware, firmware or hardware to communicate or interoperate with another piece o"
        + "f software, firmware or hardware.\n"
        + "\n"
        + "     1.9 \"Modifications\" mean any addition to, deletion from, and/or change to, "
        + "the substance and/or structure of the Original Code, any previous Modifications,"
        + " the combination of Original Code and any previous Modifications, and/or any res"
        + "pective portions thereof. When code is released as a series of files, a Modifica"
        + "tion is: (a) any addition to or deletion from the contents of a file containing "
        + "Covered Code; and/or (b) any new file or other representation of computer progra"
        + "m statements that contains any part of Covered Code.\n"
        + "\n"
        + "     1.10 \"Original Code\" means (a) the Source Code of a program or other work a"
        + "s originally made available by Licensor under this License, including the Source"
        + " Code of any updates or upgrades to such programs or works made available by Lic"
        + "ensor under this License, and that has been expressly identified by Licensor as "
        + "such in the header file(s) of such work; and (b) the object code compiled from s"
        + "uch Source Code and originally made available by Licensor under this License.\n"
        + "\n"
        + "     1.11 \"Personal Use\" means use of Covered Code by an individual solely for h"
        + "is or her personal, private and non-commercial purposes. An individual's use of "
        + "Covered Code in his or her capacity as an officer, employee, member, independent"
        + " contractor or agent of a corporation, business or organization (commercial or n"
        + "on-commercial) does not qualify as Personal Use.\n"
        + "\n"
        + "     1.12 \"Source Code\" means the human readable form of a program or other work"
        + " that is suitable for making modifications to it, including all modules it conta"
        + "ins, plus any associated interface definition files, scripts used to control com"
        + "pilation and installation of an executable (object code).\n"
        + "\n"
        + "     1.13 \"You\" or \"Your\" means an individual or a legal entity exercising right"
        + "s under this License. For legal entities, \"You\" or \"Your\" includes any entity wh"
        + "ich controls, is controlled by, or is under common control with, You, where \"con"
        + "trol\" means (a) the power, direct or indirect, to cause the direction or managem"
        + "ent of such entity, whether by contract or otherwise, or (b) ownership of fifty "
        + "percent (50%) or more of the outstanding shares or beneficial ownership of such "
        + "entity.\n"
        + "\n"
        + "2. Permitted Uses; Conditions & Restrictions. Subject to the terms and condition"
        + "s of this License, Licensor hereby grants You, effective on the date You accept "
        + "this License (via downloading or using Covered Code or otherwise indicating your"
        + " acceptance of this License), a worldwide, royalty-free, non-exclusive copyright"
        + " license, to the extent of Licensor's copyrights cover the Original Code, to do "
        + "the following:\n"
        + "\n"
        + "     2.1 You may reproduce, display, perform, modify and Deploy Covered Code, pr"
        + "ovided that in each instance:\n"
        + "\n"
        + "          (a) You must retain and reproduce in all copies of Original Code the c"
        + "opyright and other proprietary notices and disclaimers of Licensor as they appea"
        + "r in the Original Code, and keep intact all notices in the Original Code that re"
        + "fer to this License;\n"
        + "\n"
        + "          (b) You must include a copy of this License with every copy of Source "
        + "Code of Covered Code and documentation You distribute, and You may not offer or "
        + "impose any terms on such Source Code that alter or restrict this License or the "
        + "recipients' rights hereunder, except as permitted under Section 6;\n"
        + "\n"
        + "          (c) You must duplicate, to the extent it does not already exist, the n"
        + "otice in Exhibit A in each file of the Source Code of all Your Modifications, an"
        + "d cause the modified files to carry prominent notices stating that You changed t"
        + "he files and the date of any change;\n"
        + "\n"
        + "          (d) You must make Source Code of all Your Externally Deployed Modifica"
        + "tions publicly available under the terms of this License, including the license "
        + "grants set forth in Section 3 below, for as long as you Deploy the Covered Code "
        + "or twelve (12) months from the date of initial Deployment, whichever is longer. "
        + "You should preferably distribute the Source Code of Your Deployed Modifications "
        + "electronically (e.g. download from a web site); and\n"
        + "\n"
        + "          (e) if You Deploy Covered Code in object code, executable form only, Y"
        + "ou must include a prominent notice, in the code itself as well as in related doc"
        + "umentation, stating that Source Code of the Covered Code is available under the "
        + "terms of this License with information on how and where to obtain such Source Co"
        + "de. You must also include the Object Code Notice set forth in Exhibit A in the \""
        + "about\" box or other appropriate place where other copyright notices are placed, "
        + "including any packaging materials.\n"
        + "\n"
        + "     2.2 You expressly acknowledge and agree that although Licensor and each Con"
        + "tributor grants the licenses to their respective portions of the Covered Code se"
        + "t forth herein, no assurances are provided by Licensor or any Contributor that t"
        + "he Covered Code does not infringe the patent or other intellectual property righ"
        + "ts of any other entity. Licensor and each Contributor disclaim any liability to "
        + "You for claims brought by any other entity based on infringement of intellectual"
        + " property rights or otherwise. As a condition to exercising the rights and licen"
        + "ses granted hereunder, You hereby assume sole responsibility to secure any other"
        + " intellectual property rights needed, if any. For example, if a third party pate"
        + "nt license is required to allow You to make, use, sell, import or offer for sale"
        + " the Covered Code, it is Your responsibility to acquire such license(s).\n"
        + "\n"
        + "     2.3 Subject to the terms and conditions of this License, Licensor hereby gr"
        + "ants You, effective on the date You accept this License (via downloading or usin"
        + "g Covered Code or otherwise indicating your acceptance of this License), a world"
        + "wide, royalty-free, perpetual, non-exclusive patent license under Licensor's App"
        + "licable Patent Rights to make, use, sell, offer for sale and import the Covered "
        + "Code, provided that in each instance you comply with the terms of this License.\n"
        + "\n"
        + "3. Your Grants. In consideration of, and as a condition to, the licenses granted"
        + " to You under this License:\n"
        + "\n"
        + "     (a) You grant to Licensor and all third parties a non-exclusive, perpetual,"
        + " irrevocable, royalty free license under Your Applicable Patent Rights and other"
        + " intellectual property rights owned or controlled by You, to make, sell, offer f"
        + "or sale, use, import, reproduce, display, perform, modify, distribute and Deploy"
        + " Your Modifications of the same scope and extent as Licensor's licenses under Se"
        + "ctions 2.1 and 2.2; and\n"
        + "\n"
        + "     (b) You grant to Licensor and its subsidiaries a non-exclusive, worldwide, "
        + "royalty-free, perpetual and irrevocable license, under Your Applicable Patent Ri"
        + "ghts and other intellectual property rights owned or controlled by You, to make,"
        + " use, sell, offer for sale, import, reproduce, display, perform, distribute, mod"
        + "ify or have modified (for Licensor and/or its subsidiaries), sublicense and dist"
        + "ribute Your Modifications, in any form and for any purpose, through multiple tie"
        + "rs of distribution.\n"
        + "\n"
        + "     (c) You agree not use any information derived from Your use and review of t"
        + "he Covered Code, including but not limited to any algorithms or inventions that "
        + "may be contained in the Covered Code, for the purpose of asserting any of Your p"
        + "atent rights, or assisting a third party to assert any of its patent rights, aga"
        + "inst Licensor or any Contributor.\n"
        + "\n"
        + "4. Derivative Works. You may create a Derivative Work by combining Covered Code "
        + "with other code not otherwise governed by the terms of this License and distribu"
        + "te the Derivative Work as an integrated product. In each such instance, You must"
        + " make sure the requirements of this License are fulfilled for the Covered Code o"
        + "r any portion thereof, including all Modifications.\n"
        + "\n"
        + "     4.1 You must cause any Derivative Work that you distribute, publish or Exte"
        + "rnally Deploy, that in whole or in part contains or is derived from the Covered "
        + "Code or any part thereof, to be licensed as a whole at no charge to all third pa"
        + "rties under the terms of this License and no other license except as provided in"
        + " Section 4.2. You also must make Source Code available for the Derivative Work u"
        + "nder the same terms as Modifications, described in Sections 2 and 3, above.\n"
        + "\n"
        + "     4.2 Compatible Source Licenses. Software modules that have been independent"
        + "ly developed without any use of Covered Code and which contain no portion of the"
        + " Covered Code, Modifications or other Derivative Works, but are used or combined"
        + " in any way with the Covered Code or any Derivative Work to form a larger Deriva"
        + "tive Work, are exempt from the conditions described in Section 4.1 but only to t"
        + "he extent that: the software module, including any software that is linked to, i"
        + "ntegrated with, or part of the same applications as, the software module by any "
        + "method must be wholly subject to one of the Compatible Source Licenses. Notwiths"
        + "tanding the foregoing, all Covered Code must be subject to the terms of this Lic"
        + "ense. Thus, the entire Derivative Work must be licensed under a combination of t"
        + "he RPSL (for Covered Code) and a Compatible Source License for any independently"
        + " developed software modules within the Derivative Work. The foregoing requiremen"
        + "t applies even if the Compatible Source License would ordinarily allow the softw"
        + "are module to link with, or form larger works with, other software that is not s"
        + "ubject to the Compatible Source License. For example, although the Mozilla Publi"
        + "c License v1.1 allows Mozilla code to be combined with proprietary software that"
        + " is not subject to the MPL, if MPL-licensed code is used with Covered Code the M"
        + "PL-licensed code could not be combined or linked with any code not governed by t"
        + "he MPL. The general intent of this section 4.2 is to enable use of Covered Code "
        + "with applications that are wholly subject to an acceptable open source license. "
        + "You are responsible for determining whether your use of software with Covered Co"
        + "de is allowed under Your license to such software.\n"
        + "\n"
        + "     4.3 Mere aggregation of another work not based on the Covered Code with the"
        + " Covered Code (or with a work based on the Covered Code) on a volume of a storag"
        + "e or distribution medium does not bring the other work under the scope of this L"
        + "icense. If You deliver the Covered Code for combination and/or integration with "
        + "an application previously provided by You (for example, via automatic updating t"
        + "echnology), such combination and/or integration constitutes a Derivative Work su"
        + "bject to the terms of this License.\n"
        + "\n"
        + "5. Exclusions From License Grant. Nothing in this License shall be deemed to gra"
        + "nt any rights to trademarks, copyrights, patents, trade secrets or any other int"
        + "ellectual property of Licensor or any Contributor except as expressly stated her"
        + "ein. No right is granted to the trademarks of Licensor or any Contributor even i"
        + "f such marks are included in the Covered Code. Nothing in this License shall be "
        + "interpreted to prohibit Licensor from licensing under different terms from this "
        + "License any code that Licensor otherwise would have a right to license. Modifica"
        + "tions, Derivative Works and/or any use or combination of Covered Code with other"
        + " technology provided by Licensor or third parties may require additional patent "
        + "licenses from Licensor which Licensor may grant in its sole discretion. No paten"
        + "t license is granted separate from the Original Code or combinations of the Orig"
        + "inal Code with other software or hardware.\n"
        + "\n"
        + "     5.1. Trademarks. This License does not grant any rights to use the trademar"
        + "ks or trade names owned by Licensor (\"Licensor Marks\" defined in Exhibit C) or t"
        + "o any trademark or trade name belonging to any Contributor. No Licensor Marks ma"
        + "y be used to endorse or promote products derived from the Original Code other th"
        + "an as permitted by the Licensor Trademark Policy defined in Exhibit C.\n"
        + "\n"
        + "6. Additional Terms. You may choose to offer, and to charge a fee for, warranty,"
        + " support, indemnity or liability obligations and/or other rights consistent with"
        + " the scope of the license granted herein (\"Additional Terms\") to one or more rec"
        + "ipients of Covered Code. However, You may do so only on Your own behalf and as Y"
        + "our sole responsibility, and not on behalf of Licensor or any Contributor. You m"
        + "ust obtain the recipient's agreement that any such Additional Terms are offered "
        + "by You alone, and You hereby agree to indemnify, defend and hold Licensor and ev"
        + "ery Contributor harmless for any liability incurred by or claims asserted agains"
        + "t Licensor or such Contributor by reason of any such Additional Terms.\n"
        + "\n"
        + "7. Versions of the License. Licensor may publish revised and/or new versions of "
        + "this License from time to time. Each version will be given a distinguishing vers"
        + "ion number. Once Original Code has been published under a particular version of "
        + "this License, You may continue to use it under the terms of that version. You ma"
        + "y also choose to use such Original Code under the terms of any subsequent versio"
        + "n of this License published by Licensor. No one other than Licensor has the righ"
        + "t to modify the terms applicable to Covered Code created under this License.\n"
        + "\n"
        + "8. NO WARRANTY OR SUPPORT. The Covered Code may contain in whole or in part pre-"
        + "release, untested, or not fully tested works. The Covered Code may contain error"
        + "s that could cause failures or loss of data, and may be incomplete or contain in"
        + "accuracies. You expressly acknowledge and agree that use of the Covered Code, or"
        + " any portion thereof, is at Your sole and entire risk. THE COVERED CODE IS PROVI"
        + "DED \"AS IS\" AND WITHOUT WARRANTY, UPGRADES OR SUPPORT OF ANY KIND AND LICENSOR A"
        + "ND LICENSOR'S LICENSOR(S) (COLLECTIVELY REFERRED TO AS \"LICENSOR\" FOR THE PURPOS"
        + "ES OF SECTIONS 8 AND 9) AND ALL CONTRIBUTORS EXPRESSLY DISCLAIM ALL WARRANTIES A"
        + "ND/OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED"
        + " WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FI"
        + "TNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, AND NONINFRINGE"
        + "MENT OF THIRD PARTY RIGHTS. LICENSOR AND EACH CONTRIBUTOR DOES NOT WARRANT AGAIN"
        + "ST INTERFERENCE WITH YOUR ENJOYMENT OF THE COVERED CODE, THAT THE FUNCTIONS CONT"
        + "AINED IN THE COVERED CODE WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE"
        + " COVERED CODE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE COVERE"
        + "D CODE WILL BE CORRECTED. NO ORAL OR WRITTEN DOCUMENTATION, INFORMATION OR ADVIC"
        + "E GIVEN BY LICENSOR, A LICENSOR AUTHORIZED REPRESENTATIVE OR ANY CONTRIBUTOR SHA"
        + "LL CREATE A WARRANTY. You acknowledge that the Covered Code is not intended for "
        + "use in high risk activities, including, but not limited to, the design, construc"
        + "tion, operation or maintenance of nuclear facilities, aircraft navigation, aircr"
        + "aft communication systems, or air traffic control machines in which case the fai"
        + "lure of the Covered Code could lead to death, personal injury, or severe physica"
        + "l or environmental damage. Licensor disclaims any express or implied warranty of"
        + " fitness for such uses.\n"
        + "\n"
        + "9. LIMITATION OF LIABILITY. TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT SHA"
        + "LL LICENSOR OR ANY CONTRIBUTOR BE LIABLE FOR ANY INCIDENTAL, SPECIAL, INDIRECT O"
        + "R CONSEQUENTIAL DAMAGES ARISING OUT OF OR RELATING TO THIS LICENSE OR YOUR USE O"
        + "R INABILITY TO USE THE COVERED CODE, OR ANY PORTION THEREOF, WHETHER UNDER A THE"
        + "ORY OF CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE OR STRICT LIABILITY), PROD"
        + "UCTS LIABILITY OR OTHERWISE, EVEN IF LICENSOR OR SUCH CONTRIBUTOR HAS BEEN ADVIS"
        + "ED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING THE FAILURE OF ESSENTI"
        + "AL PURPOSE OF ANY REMEDY. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIAB"
        + "ILITY OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY T"
        + "O YOU. In no event shall Licensor's total liability to You for all damages (othe"
        + "r than as may be required by applicable law) under this License exceed the amoun"
        + "t of ten dollars ($10.00).\n"
        + "\n"
        + "10. Ownership. Subject to the licenses granted under this License, each Contribu"
        + "tor retains all rights, title and interest in and to any Modifications made by s"
        + "uch Contributor. Licensor retains all rights, title and interest in and to the O"
        + "riginal Code and any Modifications made by or on behalf of Licensor (\"Licensor M"
        + "odifications\"), and such Licensor Modifications will not be automatically subjec"
        + "t to this License. Licensor may, at its sole discretion, choose to license such "
        + "Licensor Modifications under this License, or on different terms from those cont"
        + "ained in this License or may choose not to license them at all.\n"
        + "\n"
        + "11. Termination.\n"
        + "\n"
        + "     11.1 Term and Termination. The term of this License is perpetual unless ter"
        + "minated as provided below. This License and the rights granted hereunder will te"
        + "rminate:\n"
        + "\n"
        + "          (a) automatically without notice from Licensor if You fail to comply w"
        + "ith any term(s) of this License and fail to cure such breach within 30 days of b"
        + "ecoming aware of such breach;\n"
        + "\n"
        + "          (b) immediately in the event of the circumstances described in Section"
        + " 12.5(b); or\n"
        + "\n"
        + "          (c) automatically without notice from Licensor if You, at any time dur"
        + "ing the term of this License, commence an action for patent infringement against"
        + " Licensor (including by cross-claim or counter claim in a lawsuit);\n"
        + "\n"
        + "          (d) upon written notice from Licensor if You, at any time during the t"
        + "erm of this License, commence an action for patent infringement against any thir"
        + "d party alleging that the Covered Code itself (excluding combinations with other"
        + " software or hardware) infringes any patent (including by cross-claim or counter"
        + " claim in a lawsuit).\n"
        + "\n"
        + "     11.2 Effect of Termination. Upon termination, You agree to immediately stop"
        + " any further use, reproduction, modification, sublicensing and distribution of t"
        + "he Covered Code and to destroy all copies of the Covered Code that are in your p"
        + "ossession or control. All sublicenses to the Covered Code which have been proper"
        + "ly granted prior to termination shall survive any termination of this License. P"
        + "rovisions which, by their nature, should remain in effect beyond the termination"
        + " of this License shall survive, including but not limited to Sections 3, 5, 8, 9"
        + ", 10, 11, 12.2 and 13. No party will be liable to any other for compensation, in"
        + "demnity or damages of any sort solely as a result of terminating this License in"
        + " accordance with its terms, and termination of this License will be without prej"
        + "udice to any other right or remedy of any party.\n"
        + "\n"
        + "12. Miscellaneous.\n"
        + "\n"
        + "     12.1 Government End Users. The Covered Code is a \"commercial item\" as defin"
        + "ed in FAR 2.101. Government software and technical data rights in the Covered Co"
        + "de include only those rights customarily provided to the public as defined in th"
        + "is License. This customary commercial license in technical data and software is "
        + "provided in accordance with FAR 12.211 (Technical Data) and 12.212 (Computer Sof"
        + "tware) and, for Department of Defense purchases, DFAR 252.227-7015 (Technical Da"
        + "ta -- Commercial Items) and 227.7202-3 (Rights in Commercial Computer Software o"
        + "r Computer Software Documentation). Accordingly, all U.S. Government End Users a"
        + "cquire Covered Code with only those rights set forth herein.\n"
        + "\n"
        + "     12.2 Relationship of Parties. This License will not be construed as creatin"
        + "g an agency, partnership, joint venture or any other form of legal association b"
        + "etween or among You, Licensor or any Contributor, and You will not represent to "
        + "the contrary, whether expressly, by implication, appearance or otherwise.\n"
        + "\n"
        + "     12.3 Independent Development. Nothing in this License will impair Licensor'"
        + "s right to acquire, license, develop, have others develop for it, market and/or "
        + "distribute technology or products that perform the same or similar functions as,"
        + " or otherwise compete with, Modifications, Derivative Works, technology or produ"
        + "cts that You may develop, produce, market or distribute.\n"
        + "\n"
        + "     12.4 Waiver; Construction. Failure by Licensor or any Contributor to enforc"
        + "e any provision of this License will not be deemed a waiver of future enforcemen"
        + "t of that or any other provision. Any law or regulation which provides that the "
        + "language of a contract shall be construed against the drafter will not apply to "
        + "this License.\n"
        + "\n"
        + "     12.5 Severability. (a) If for any reason a court of competent jurisdiction "
        + "finds any provision of this License, or portion thereof, to be unenforceable, th"
        + "at provision of the License will be enforced to the maximum extent permissible s"
        + "o as to effect the economic benefits and intent of the parties, and the remainde"
        + "r of this License will continue in full force and effect. (b) Notwithstanding th"
        + "e foregoing, if applicable law prohibits or restricts You from fully and/or spec"
        + "ifically complying with Sections 2 and/or 3 or prevents the enforceability of ei"
        + "ther of those Sections, this License will immediately terminate and You must imm"
        + "ediately discontinue any use of the Covered Code and destroy all copies of it th"
        + "at are in your possession or control.\n"
        + "\n"
        + "     12.6 Dispute Resolution. Any litigation or other dispute resolution between"
        + " You and Licensor relating to this License shall take place in the Seattle, Wash"
        + "ington, and You and Licensor hereby consent to the personal jurisdiction of, and"
        + " venue in, the state and federal courts within that District with respect to thi"
        + "s License. The application of the United Nations Convention on Contracts for the"
        + " International Sale of Goods is expressly excluded.\n"
        + "\n"
        + "     12.7 Export/Import Laws. This software is subject to all export and import "
        + "laws and restrictions and regulations of the country in which you receive the Co"
        + "vered Code and You are solely responsible for ensuring that You do not export, r"
        + "e-export or import the Covered Code or any direct product thereof in violation o"
        + "f any such restrictions, laws or regulations, or without all necessary authoriza"
        + "tions.\n"
        + "\n"
        + "     12.8 Entire Agreement; Governing Law. This License constitutes the entire a"
        + "greement between the parties with respect to the subject matter hereof. This Lic"
        + "ense shall be governed by the laws of the United States and the State of Washing"
        + "ton.\n"
        + "\n"
        + "     Where You are located in the province of Quebec, Canada, the following clau"
        + "se applies: The parties hereby confirm that they have requested that this Licens"
        + "e and all related documents be drafted in English. Les parties ont exig� que le "
        + "pr�sent contrat et tous les documents connexes soient r�dig�s en anglais.\n"
        + "\n"
        + "\n"
        + "EXHIBIT A.\n"
        + "\n"
        + "\"Copyright (c) 1995-2002 RealNetworks, Inc. and/or its licensors. All Rights Res"
        + "erved.\n"
        + "\n"
        + "The contents of this file, and the files included with this file, are subject to"
        + " the current version of the RealNetworks Public Source License Version 1.0 (the "
        + "\"RPSL\") available at https://www.helixcommunity.org/content/rpsl unless you have"
        + " licensed the file under the RealNetworks Community Source License Version 1.0 ("
        + "the \"RCSL\") available at https://www.helixcommunity.org/content/rcsl, in which c"
        + "ase the RCSL will apply. You may also obtain the license terms directly from Rea"
        + "lNetworks. You may not use this file except in compliance with the RPSL or, if y"
        + "ou have a valid RCSL with RealNetworks applicable to this file, the RCSL. Please"
        + " see the applicable RPSL or RCSL for the rights, obligations and limitations gov"
        + "erning use of the contents of the file.\n"
        + "\n"
        + "This file is part of the Helix DNA Technology. RealNetworks is the developer of "
        + "the Original code and owns the copyrights in the portions it created.\n"
        + "\n"
        + "This file, and the files included with this file, is distributed and made availa"
        + "ble on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED"
        + ", AND REALNETWORKS HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMIT"
        + "ATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIE"
        + "T ENJOYMENT OR NON-INFRINGEMENT.\n"
        + "\n"
        + "Contributor(s): ____________________________________\n"
        + "\n"
        + "Technology Compatibility Kit Test Suite(s) Location (if licensed under the RCSL)"
        + ":\n"
        + "\n"
        + "________________________________\"\n"
        + "\n"
        + "Object Code Notice: Helix DNA Client technology included. Copyright (c) RealNetw"
        + "orks, Inc., 1995-2002. All rights reserved.\n"
        + "\n"
        + "EXHIBIT B\n"
        + "\n"
        + "Compatible Source Licenses for the RealNetworks Public Source License. The follo"
        + "wing list applies to the most recent version of the license as of October 25, 20"
        + "02, unless otherwise indicated.\n"
        + "\n"
        + "Academic Free License\n"
        + "Apache Software License\n"
        + "Apple Public Source License\n"
        + "Artistic license\n"
        + "Attribution Assurance Licenses\n"
        + "BSD license\n"
        + "Common Public License1\n"
        + "Eiffel Forum License\n"
        + "GNU General Public License (GPL)1\n"
        + "GNU Library or \"Lesser\" General Public License (LGPL)1\n"
        + "IBM Public License\n"
        + "Intel Open Source License\n"
        + "Jabber Open Source License\n"
        + "MIT license\n"
        + "MITRE Collaborative Virtual Workspace License (CVW License)\n"
        + "Motosoto License\n"
        + "Mozilla Public License 1.0 (MPL)\n"
        + "Mozilla Public License 1.1 (MPL)\n"
        + "Nokia Open Source License\n"
        + "Open Group Test Suite License\n"
        + "Python Software Foundation License\n"
        + "Ricoh Source Code Public License\n"
        + "Sun Industry Standards Source License (SISSL)\n"
        + "Sun Public License\n"
        + "University of Illinois/NCSA Open Source License\n"
        + "Vovida Software License v. 1.0\n"
        + "W3C License\n"
        + "X.Net License\n"
        + "Zope Public License\n"
        + "zlib/libpng license\n"
        + "\n"
        + "1Note: because this license contains certain reciprocal licensing terms that pur"
        + "port to extend to independently developed code, You may be prohibited under the "
        + "terms of this otherwise compatible license from using code licensed under its te"
        + "rms with Covered Code because Covered Code may only be licensed under the RealNe"
        + "tworks Public Source License. Any attempt to apply non RPSL license terms, inclu"
        + "ding without limitation the GPL, to Covered Code is expressly forbidden. You are"
        + " responsible for ensuring that Your use of Compatible Source Licensed code does "
        + "not violate either the RPSL or the Compatible Source License.\n"
        + "\n"
        + "The latest version of this list can be found at: https://www.helixcommunity.org/"
        + "content/complicense\n"
        + "\n"
        + "EXHIBIT C\n"
        + "\n"
        + "RealNetworks' Trademark policy.\n"
        + "\n"
        + "RealNetworks defines the following trademarks collectively as \"Licensor Trademar"
        + "ks\": \"RealNetworks\", \"RealPlayer\", \"RealJukebox\", \"RealSystem\", \"RealAudio\", \"Re"
        + "alVideo\", \"RealOne Player\", \"RealMedia\", \"Helix\" or any other trademarks or trad"
        + "e names belonging to RealNetworks.\n"
        + "\n"
        + "RealNetworks \"Licensor Trademark Policy\" forbids any use of Licensor Trademarks "
        + "except as permitted by and in strict compliance at all times with RealNetworks' "
        + "third party trademark usage guidelines which are posted at www.realnetworks.com/"
        + "info/helixlogo.html.\n"
; // the license text
    }
 
    
}
