package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:18:32Z
 * LicenseName: AGPL-3.0+
 * FileName: SISSL_1_2.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class SISSL_1_2 extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return false; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "SISSL-1.2"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "Sun Industry Standards Source License v1.2"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "SUN INDUSTRY STANDARDS SOURCE LICENSE\n"
        + "Version 1.2\n"
        + " 1.0 DEFINITIONS \n"
        + "\n"
        + "     1.1 Commercial Use means distribution or otherwise making the Original Code"
        + " available to a third party. \n"
        + "\n"
        + "     1.2 Contributor Version means the combination of the Original Code, and the"
        + " Modifications made by that particular Contributor. \n"
        + "\n"
        + "     1.3 Electronic Distribution Mechanism means a mechanism generally accepted "
        + "in the software development community for the electronic transfer of data. \n"
        + "\n"
        + "     1.4 Executable means Original Code in any form other than Source Code. \n"
        + "\n"
        + "     1.5 Initial Developer means the individual or entity identified as the Init"
        + "ial Developer in the Source Code notice required by Exhibit A. \n"
        + "\n"
        + "     1.6 Larger Work means a work which combines Original Code or portions there"
        + "of with code not governed by the terms of this License. \n"
        + "\n"
        + "     1.7 License means this document. \n"
        + "\n"
        + "     1.8 Licensable means having the right to grant, to the maximum extent possi"
        + "ble, whether at the time of the initial grant or subsequently acquired, any and "
        + "all of the rights conveyed herein. \n"
        + "\n"
        + "     1.9 Modifications means any addition to or deletion from the substance or s"
        + "tructure of either the Original Code or any previous Modifications. A Modificati"
        + "on is:\n"
        + "\n"
        + "          A. Any addition to or deletion from the contents of a file containing "
        + "Original Code or previous Modifications.\n"
        + "\n"
        + "          B. Any new file that contains any part of the Original Code or previou"
        + "s Modifications.\n"
        + "\n"
        + "     1.10 Original Code means Source Code of computer software code which is des"
        + "cribed in the Source Code notice required by Exhibit A as Original Code.\n"
        + "\n"
        + "     1.11 Patent Claims means any patent claim(s), now owned or hereafter acquir"
        + "ed, including without limitation, method, process, and apparatus claims, in any "
        + "patent Licensable by grantor.\n"
        + "\n"
        + "     1.12 Source Code means the preferred form of the Original Code for making m"
        + "odifications to it, including all modules it contains, plus any associated inter"
        + "face definition files, or scripts used to control compilation and installation o"
        + "f an Executable.\n"
        + "\n"
        + "     1.13 Standards means the standards identified in Exhibit B.\n"
        + "\n"
        + "     1.14 You (or Your) means an individual or a legal entity exercising rights "
        + "under, and complying with all of the terms of, this License or a future version "
        + "of this License issued under Section 6.1. For legal entities, You includes any e"
        + "ntity which controls, is controlled by, or is under common control with You. For"
        + " purposes of this definition, control means (a) the power, direct or indirect, t"
        + "o cause the direction or management of such entity, whether by contract or other"
        + "wise, or (b) ownership of more than fifty percent (50%) of the outstanding share"
        + "s or beneficial ownership of such entity.\n"
        + "\n"
        + "2.0 SOURCE CODE LICENSE\n"
        + "\n"
        + "     2.1 The Initial Developer Grant The Initial Developer hereby grants You a w"
        + "orld-wide, royalty-free, non-exclusive license, subject to third party intellect"
        + "ual property claims:\n"
        + "\n"
        + "          (a)under intellectual property rights (other than patent or trademark)"
        + " Licensable by Initial Developer to use, reproduce, modify, display, perform, su"
        + "blicense and distribute the Original Code (or portions thereof) with or without "
        + "Modifications, and/or as part of a Larger Work; and\n"
        + "\n"
        + "          (b) under Patents Claims infringed by the making, using or selling of "
        + "Original Code, to make, have made, use, practice, sell, and offer for sale, and/"
        + "or otherwise dispose of the Original Code (or portions thereof).\n"
        + "\n"
        + "          (c) the licenses granted in this Section 2.1(a) and (b) are effective "
        + "on the date Initial Developer first distributes Original Code under the terms of"
        + " this License.\n"
        + "\n"
        + "          (d) Notwithstanding Section 2.1(b) above, no patent license is granted"
        + ": 1) for code that You delete from the Original Code; 2) separate from the Origi"
        + "nal Code; or 3) for infringements caused by: i) the modification of the Original"
        + " Code or ii) the combination of the Original Code with other software or devices"
        + ", including but not limited to Modifications.\n"
        + "\n"
        + "3.0 DISTRIBUTION OBLIGATIONS\n"
        + "\n"
        + "     3.1 Application of License. The Source Code version of Original Code may be"
        + " distributed only under the terms of this License or a future version of this Li"
        + "cense released under Section 6.1, and You must include a copy of this License wi"
        + "th every copy of the Source Code You distribute. You may not offer or impose any"
        + " terms on any Source Code version that alters or restricts the applicable versio"
        + "n of this License or the recipients rights hereunder. Your license for shipment "
        + "of the Contributor Version is conditioned upon Your full compliance with this Se"
        + "ction. The Modifications which You create must comply with all requirements set "
        + "out by the Standards body in effect one hundred twenty (120) days before You shi"
        + "p the Contributor Version. In the event that the Modifications do not meet such "
        + "requirements, You agree to publish either (i) any deviation from the Standards p"
        + "rotocol resulting from implementation of Your Modifications and a reference impl"
        + "ementation of Your Modifications or (ii) Your Modifications in Source Code form,"
        + " and to make any such deviation and reference implementation or Modifications av"
        + "ailable to all third parties under the same terms a this license on a royalty fr"
        + "ee basis within thirty (30) days of Your first customer shipment of Your Modific"
        + "ations. Additionally, in the event that the Modifications you create do not meet"
        + " the requirements set out in this Section, You agree to comply with the Standard"
        + "s requirements set out in Exhibit B. \n"
        + "\n"
        + "     3.2 Required Notices. You must duplicate the notice in Exhibit A in each fi"
        + "le of the Source Code. If it is not possible to put such notice in a particular "
        + "Source Code file due to its structure, then You must include such notice in a lo"
        + "cation (such as a relevant directory) where a user would be likely to look for s"
        + "uch a notice. If You created one or more Modification(s) You may add Your name a"
        + "s a Contributor to the notice described in Exhibit A. You must also duplicate th"
        + "is License in any documentation for the Source Code where You describe recipient"
        + "s rights or ownership rights relating to Initial Code. \n"
        + "\n"
        + "     You may choose to offer, and to charge a fee for, warranty, support, indemn"
        + "ity or liability obligations to one or more recipients of Your version of the Co"
        + "de. However, You may do so only on Your own behalf, and not on behalf of the Ini"
        + "tial Developer. You must make it absolutely clear than any such warranty, suppor"
        + "t, indemnity or liability obligation is offered by You alone, and You hereby agr"
        + "ee to indemnify the Initial Developer for any liability incurred by the Initial "
        + "Developer as a result of warranty, support, indemnity or liability terms You off"
        + "er. \n"
        + "\n"
        + "     3.3 Distribution of Executable Versions. You may distribute Original Code i"
        + "n Executable and Source form only if the requirements of Sections 3.1 and 3.2 ha"
        + "ve been met for that Original Code, and if You include a notice stating that the"
        + " Source Code version of the Original Code is available under the terms of this L"
        + "icense. The notice must be conspicuously included in any notice in an Executable"
        + " or Source versions, related documentation or collateral in which You describe r"
        + "ecipients rights relating to the Original Code. You may distribute the Executabl"
        + "e and Source versions of Your version of the Code or ownership rights under a li"
        + "cense of Your choice, which may contain terms different from this License, provi"
        + "ded that You are in compliance with the terms of this License. If You distribute"
        + " the Executable and Source versions under a different license You must make it a"
        + "bsolutely clear that any terms which differ from this License are offered by You"
        + " alone, not by the Initial Developer. You hereby agree to indemnify the Initial "
        + "Developer for any liability incurred by the Initial Developer as a result of any"
        + " such terms You offer. \n"
        + "\n"
        + "     3.4 Larger Works. You may create a Larger Work by combining Original Code w"
        + "ith other code not governed by the terms of this License and distribute the Larg"
        + "er Work as a single product. In such a case, You must make sure the requirements"
        + " of this License are fulfilled for the Original Code. \n"
        + "\n"
        + "4.0 INABILITY TO COMPLY DUE TO STATUTE OR REGULATION\n"
        + "\n"
        + "If it is impossible for You to comply with any of the terms of this License with"
        + " respect to some or all of the Original Code due to statute, judicial order, or "
        + "regulation then You must: (a) comply with the terms of this License to the maxim"
        + "um extent possible; and (b) describe the limitations and the code they affect. S"
        + "uch description must be included in the LEGAL file described in Section 3.2 and "
        + "must be included with all distributions of the Source Code. Except to the extent"
        + " prohibited by statute or regulation, such description must be sufficiently deta"
        + "iled for a recipient of ordinary skill to be able to understand it. \n"
        + "\n"
        + "5.0 APPLICATION OF THIS LICENSE\n"
        + "\n"
        + "This License applies to code to which the Initial Developer has attached the not"
        + "ice in Exhibit A and to related Modifications as set out in Section 3.1. \n"
        + "\n"
        + "6.0 VERSIONS OF THE LICENSE\n"
        + "\n"
        + "     6.1 New Versions. Sun may publish revised and/or new versions of the Licens"
        + "e from time to time. Each version will be given a distinguishing version number.\n"
        + "\n"
        + "     6.2 Effect of New Versions. Once Original Code has been published under a p"
        + "articular version of the License, You may always continue to use it under the te"
        + "rms of that version. You may also choose to use such Original Code under the ter"
        + "ms of any subsequent version of the License published by Sun. No one other than "
        + "Sun has the right to modify the terms applicable to Original Code. \n"
        + "\n"
        + "7.0 DISCLAIMER OF WARRANTY\n"
        + "\n"
        + "ORIGINAL CODE IS PROVIDED UNDER THIS LICENSE ON AN AS IS BASIS, WITHOUT WARRANTY"
        + " OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRAN"
        + "TIES THAT THE ORIGINAL CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICUL"
        + "AR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE "
        + "OF THE ORIGINAL CODE IS WITH YOU. SHOULD ANY ORIGINAL CODE PROVE DEFECTIVE IN AN"
        + "Y RESPECT, YOU (NOT THE INITIAL DEVELOPER) ASSUME THE COST OF ANY NECESSARY SERV"
        + "ICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIA"
        + "L PART OF THIS LICENSE. NO USE OF ANY ORIGINAL CODE IS AUTHORIZED HEREUNDER EXCE"
        + "PT UNDER THIS DISCLAIMER. \n"
        + "\n"
        + "8.0 TERMINATION\n"
        + "\n"
        + "     8.1 This License and the rights granted hereunder will terminate automatica"
        + "lly if You fail to comply with terms herein and fail to cure such breach within "
        + "30 days of becoming aware of the breach. All sublicenses to the Original Code wh"
        + "ich are properly granted shall survive any termination of this License. Provisio"
        + "ns which, by their nature, must remain in effect beyond the termination of this "
        + "License shall survive. 8.2 In the event of termination under Section 8.1 above, "
        + "all end user license agreements (excluding distributors and resellers) which hav"
        + "e been validly granted by You or any distributor hereunder prior to termination "
        + "shall survive termination. \n"
        + "\n"
        + "\n"
        + "EXHIBIT A - Sun Industry Standards Source License\n"
        + "\n"
        + "\"The contents of this file are subject to the Sun Industry Standards Source Lice"
        + "nse Version 1.2 (the License); You \n"
        + "may not use this file except in compliance with the License.\"\n"
        + "\n"
        + "\"You may obtain a copy of the License at gridengine.sunsource.net/license.html\"\n"
        + "\n"
        + "\"Software distributed under the License is distributed on an AS IS basis, WITHOU"
        + "T WARRANTY OF ANY KIND, either express or \n"
        + "implied. See the License for the specific language governing rights and limitati"
        + "ons under the License.\"\n"
        + "\n"
        + "\"The Original Code is Grid Engine.\"\n"
        + "\n"
        + "\"The Initial Developer of the Original Code is: \n"
        + "Sun Microsystems, Inc.\"\n"
        + "\n"
        + "\"Portions created by: Sun Microsystems, Inc. are Copyright (C) 2001 Sun Microsys"
        + "tems, Inc.\"\n"
        + "\n"
        + "\"All Rights Reserved.\"\n"
        + "\n"
        + "\"Contributor(s):__________________________________\"\n"
        + "\n"
        + "EXHIBIT B - Standards\n"
        + "\n"
        + "1.0 Requirements for project Standards. The requirements for project Standards a"
        + "re version-dependent and are defined at: Grid Engine standards.\n"
        + "\n"
        + "2.0 Additional requirements. The additional requirements pursuant to Section 3.1"
        + " are defined as:\n"
        + "\n"
        + "     2.1 Naming Conventions. If any of your Modifications do not meet the requir"
        + "ements of the Standard, then you must change the product name so that Grid Engin"
        + "e, gridengine, gridengine.sunsource, and similar naming conventions are not used"
        + ".\n"
        + "\n"
        + "     2.2 Compliance Claims. If any of your Modifications do not meet the require"
        + "ments of the Standards you may not claim, directly or indirectly, that your impl"
        + "ementation of the Standards is compliant.\n"
; // the license text
    }
 
    
}
