package license.terms.SPDXLL;

import license.License;

/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: nuno
 * Created: 2015-03-02T19:18:29Z
 * LicenseName: AGPL-3.0+
 * FileName: SNIA.java 
 * FileCategory: SOURCE
 * FileCopyrightText: <text> Copyright (c) 2015, nuno </text>
 */


public class SNIA extends License{
   /**
     * Was this license approved by the OSI?
     * @return  True if the license is listed as approved   
     */
    @Override
    public Boolean approvedOSI(){
        return false; // was this license OSI approved or not?
    }
    
    /**
     * The SPDX identifier
     * @return  The unique identifier for this license
     */
    @Override
    public String getId(){
        return "SNIA"; // short and unique id
    }
    
    /**
     * What is the full title for this license?
     * @return  The official full title of the license
     */
    @Override
    public String getTitle(){
        return "SNIA Public License 1.1"; // full text title
    }
    
    /**
     * In most cases, the license will have generic terms that only present
     * minor changes such as copyright attributions. This method provides
     * an idea of the contents of the license.
     * @return  Normal text (no markup) version of the license terms
     */
    @Override
    public String getTerms(){
        return "STORAGE NETWORKING INDUSTRY ASSOCIATION \n"
        + "PUBLIC LICENSE \n"
        + "Version 1.1\n"
        + "\n"
        + "1. Definitions.\n"
        + "\n"
        + "1.1 \"Commercial Use\" means distribution or otherwise making the Covered Code ava"
        + "ilable to a third party.  \n"
        + "\n"
        + "1.2 \"Contributor\" means each entity that creates or contributes to the creation "
        + "of Modifications.  \n"
        + "\n"
        + "1.3 \"Contributor Version\" means the combination of the Original Code, prior Modi"
        + "fications used by a Contributor, and the Modifications made by that particular C"
        + "ontributor.  \n"
        + "\n"
        + "1.4 \"Covered Code\" means the Original Code or Modifications or the combination o"
        + "f the Original Code and Modifications, in each case including portions thereof. "
        + " \n"
        + "\n"
        + "1.5 \"Electronic Distribution Mechanism\" means a mechanism generally accepted in "
        + "the software development community for the electronic transfer of data.  \n"
        + "\n"
        + "1.6 \"Executable\" means Covered Code in any form other than Source Code.  \n"
        + "\n"
        + "1.7 \"Initial Developer\" means the individual or entity identified as the Initial"
        + " Developer in the Source Code notice required by Exhibit A.  \n"
        + "\n"
        + "1.8 \"Larger Work\" means a work which combines Covered Code or portions thereof w"
        + "ith code not governed by the terms of this License.  \n"
        + "\n"
        + "1.9 \"License\" means this document.  \n"
        + "\n"
        + "1.10 \"Licensable\" means having the right to grant, to the maximum extent possibl"
        + "e, whether at the time of the initial grant or subsequently acquired, any and al"
        + "l of the rights conveyed herein.  \n"
        + "\n"
        + "1.11 \"Modifications\" means any addition to or deletion from the substance or str"
        + "ucture of either the Original Code or any previous Modifications. When Covered C"
        + "ode is released as a series of files, a Modification is: \n"
        + "     A. Any addition to or deletion from the contents of a file containing Origi"
        + "nal Code or previous Modifications. \n"
        + "     B. Any new file that contains any part of the Original Code or previous Mod"
        + "ifications.\n"
        + "\n"
        + "1.12 \"Original Code\" means Source Code of computer software code which is descri"
        + "bed in the Source Code notice required by Exhibit A as Original Code, and which,"
        + " at the time of its release under this License is not already Covered Code gover"
        + "ned by this License.  \n"
        + "\n"
        + "1.13 \"Patent Claims\" means any patent claim(s), now owned or hereafter acquired,"
        + " including without limitation, method, process, and apparatus claims, in any pat"
        + "ent Licensable by grantor.  \n"
        + "\n"
        + "1.14 \"Source Code\" means the preferred form of the Covered Code for making modif"
        + "ications to it, including all modules it contains, plus any associated interface"
        + " definition files, scripts used to control compilation and installation of an Ex"
        + "ecutable, or source code differential comparisons against either the Original Co"
        + "de or another well known, available Covered Code of the Contributor's choice. Th"
        + "e Source Code can be in a compressed or archival form, provided the appropriate "
        + "decompression or de-archiving software is widely available for no charge.  \n"
        + "\n"
        + "1.15 \"You\" (or \"Your\") means an individual or a legal entity exercising rights u"
        + "nder, and complying with all of the terms of, this License or a future version o"
        + "f this License issued under Section 6.1. For legal entities, \"You\" includes any "
        + "entity which controls, is controlled by, or is under common control with You. Fo"
        + "r purposes of this definition, \"control\" means (a) the power, direct or indirect"
        + ", to cause the direction or management of such entity, whether by contract or ot"
        + "herwise, or (b) ownership of more than fifty percent (50%) of the outstanding sh"
        + "ares or beneficial ownership of such entity\n"
        + "\n"
        + "2. Source Code License.\n"
        + "\n"
        + "2.1 The Initial Developer Grant. The Initial Developer hereby grants You a world"
        + "-wide, royalty-free, non-exclusive license, subject to third party intellectual "
        + "property claims: \n"
        + "     (a) under intellectual property rights (other than patent or trademark) Lic"
        + "ensable by Initial Developer to use, reproduce, modify, display, perform, sublic"
        + "ense and distribute the Original Code (or portions thereof) with or without Modi"
        + "fications, and/or as part of a Larger Work; and \n"
        + "     (b) under Patents Claims infringed by the making, using or selling of Origi"
        + "nal Code, to make, have made, use, practice, sell, and offer for sale, and/or ot"
        + "herwise dispose of the Original Code (or portions thereof). \n"
        + "     (c) the licenses granted in this Section 2.1(a) and (b) are effective on th"
        + "e date Initial Developer first distributes Original Code under the terms of this"
        + " License. \n"
        + "     (d) Notwithstanding Section 2.1(b) above, no patent license is granted: 1) "
        + "for code that You delete from the Original Code; 2) separate from the Original C"
        + "ode; or 3) for infringements caused by: i) the modification of the Original Code"
        + " or ii) the combination of the Original Code with other software or devices.\n"
        + "\n"
        + "2.2 Contributor Grant. Subject to third party intellectual property claims, each"
        + " Contributor hereby grants You a world-wide, royalty-free, non-exclusive license"
        + " \n"
        + "     (a) under intellectual property rights (other than patent or trademark) Lic"
        + "ensable by Contributor, to use, reproduce, modify, display, perform, sublicense "
        + "and distribute the Modifications created by such Contributor (or portions thereo"
        + "f) either on an unmodified basis, with other Modifications, as Covered Code and/"
        + "or as part of a Larger Work; and \n"
        + "     (b) under Patent Claims infringed by the making, using, or selling of Modif"
        + "ications made by that Contributor either alone and/or in combination with its Co"
        + "ntributor Version (or portions of such combination), to make, use, sell, offer f"
        + "or sale, have made, and/or otherwise dispose of: 1) Modifications made by that C"
        + "ontributor (or portions thereof); and 2) the combination of Modifications made b"
        + "y that Contributor with its Contributor Version (or portions of such combination"
        + "). \n"
        + "     (c) the licenses granted in Sections 2.2(a) and 2.2(b) are effective on the"
        + " date Contributor first makes Commercial Use of the Covered Code. \n"
        + "     (d) Notwithstanding Section 2.2(b) above, no patent license is granted: 1) "
        + "for any code that Contributor has deleted from the Contributor Version; 2) separ"
        + "ate from the Contributor Version; 3) for infringements caused by: i) third party"
        + " modifications of Contributor Version or ii) the combination of Modifications ma"
        + "de by that Contributor with other software (except as part of the Contributor Ve"
        + "rsion) or other devices; or 4) under Patent Claims infringed by Covered Code in "
        + "the absence of Modifications made by that Contributor.\n"
        + "\n"
        + "3. Distribution Obligations.\n"
        + "\n"
        + "3.1 Application of License. The Modifications which You create or to which You c"
        + "ontribute are governed by the terms of this License, including without limitatio"
        + "n Section 2.2. The Source Code version of Covered Code may be distributed only u"
        + "nder the terms of this License or a future version of this License released unde"
        + "r Section 6.1, and You must include a copy of this License with every copy of th"
        + "e Source Code You distribute. You may not offer or impose any terms on any Sourc"
        + "e Code version that alters or restricts the applicable version of this License o"
        + "r the recipients' rights hereunder. However, You may include an additional docum"
        + "ent offering the additional rights described in Section 3.5.  \n"
        + "\n"
        + "3.2 Availability of Source Code. Any Modification which You create or to which Y"
        + "ou contribute must be made available in Source Code form under the terms of this"
        + " License either on the same media as an Executable version or via an accepted El"
        + "ectronic Distribution Mechanism to anyone to whom you made an Executable version"
        + " available; and if made available via Electronic Distribution Mechanism, must re"
        + "main available for at least twelve (12) months after the date it initially becam"
        + "e available, or at least six (6) months after a subsequent version of that parti"
        + "cular Modification has been made available to such recipients. You are responsib"
        + "le for ensuring that the Source Code version remains available even if the Elect"
        + "ronic Distribution Mechanism is maintained by a third party.  \n"
        + "\n"
        + "3.3 Description of Modifications. You must cause all Covered Code to which You c"
        + "ontribute to contain a file documenting the changes You made to create that Cove"
        + "red Code and the date of any change. You must include a prominent statement that"
        + " the Modification is derived, directly or indirectly, from Original Code provide"
        + "d by the Initial Developer and including the name of the Initial Developer in (a"
        + ") the Source Code, and (b) in any notice in an Executable version or related doc"
        + "umentation in which You describe the origin or ownership of the Covered Code.  \n"
        + "\n"
        + "3.4 Intellectual Property Matters. \n"
        + "     (a) Third Party Claims. If Contributor has actual knowledge that a license "
        + "under a third party's intellectual property rights is required to exercise the r"
        + "ights granted by such Contributor under Sections 2.1 or 2.2, Contributor must in"
        + "clude a text file with the Source Code distribution titled \"LEGAL\" which describ"
        + "es the claim and the party making the claim in sufficient detail that a recipien"
        + "t will know whom to contact. If Contributor obtains such knowledge after the Mod"
        + "ification is made available as described in Section 3.2, Contributor shall promp"
        + "tly modify the LEGAL file in all copies Contributor makes available thereafter. \n"
        + "     (b) Contributor API's. If Contributor's Modifications include an applicatio"
        + "n programming interface and Contributor has actual knowledge of patent licenses "
        + "which are reasonably necessary to implement that API, Contributor must also incl"
        + "ude this information in the LEGAL file. \n"
        + "     (c) Representations. Contributor represents that, except as disclosed pursu"
        + "ant to Section 3.4(a) above, Contributor believes that Contributor's Modificatio"
        + "ns are Contributor's original creation(s) and/or Contributor has sufficient righ"
        + "ts to grant the rights conveyed by this License.  \n"
        + "\n"
        + "3.5 Required Notices. You must duplicate the notice in Exhibit A in each file of"
        + " the Source Code. If it is not possible to put such notice in a particular Sourc"
        + "e Code file due to its structure, then You must include such notice in a locatio"
        + "n (such as a relevant directory) where a user would be most likely to look for s"
        + "uch a notice. If You created one or more Modification(s) You may add your name a"
        + "s a Contributor to the notice described in Exhibit A. You must also duplicate th"
        + "is License in any documentation for the Source Code where You describe recipient"
        + "s' rights or ownership rights relating to Covered Code. You may choose to offer,"
        + " and to charge a fee for, warranty, support, indemnity or liability obligations "
        + "to one or more recipients of Covered Code. However, You may do so only on Your o"
        + "wn behalf, and not on behalf of the Initial Developer or any Contributor. You mu"
        + "st make it absolutely clear that any such warranty, support, indemnity or liabil"
        + "ity obligation is offered by You alone, and You hereby agree to indemnify the In"
        + "itial Developer and every Contributor for any liability (excluding any liability"
        + " arising from intellectual property claims relating to the Covered Code) incurre"
        + "d by the Initial Developer or such Contributor as a result of warranty, support,"
        + " indemnity or liability terms You offer.  \n"
        + "\n"
        + "3.6 Distribution of Executable Versions. You may distribute Covered Code in Exec"
        + "utable form only if the requirements of Section 3.1-3.5 have been met for that C"
        + "overed Code, and if You include a notice stating that the Source Code version of"
        + " the Covered Code is available under the terms of this License, including a desc"
        + "ription of how and where You have fulfilled the obligation of Section 3.2. The n"
        + "otice must be conspicuously included in any notice in an Executable version, rel"
        + "ated documentation or collateral in which You describe recipients' rights relati"
        + "ng to the Covered Code. You may distribute the Executable version of Covered Cod"
        + "e or ownership rights under a license of Your choice, which may contain terms di"
        + "fferent from this License, provided that You are in compliance with the terms of"
        + " this License and that the license for the Executable version does not attempt t"
        + "o limit or alter the recipient's rights in the Source Code version from the righ"
        + "ts set forth in this License. If You distribute the Executable version under a d"
        + "ifferent license You must make it absolutely clear that any terms which differ f"
        + "rom this License are offered by You alone, not by the Initial Developer or any C"
        + "ontributor. You hereby agree to indemnify the Initial Developer and every Contri"
        + "butor for any liability (excluding any liability arising from intellectual prope"
        + "rty claims relating to the Covered Code) incurred by the Initial Developer or su"
        + "ch Contributor as a result of any such terms You offer.  \n"
        + "\n"
        + "3.7 Larger Works. You may create a Larger Work by combining Covered Code with ot"
        + "her code not governed by the terms of this License and distribute the Larger Wor"
        + "k as a single product. In such a case, You must make sure the requirements of th"
        + "is License are fulfilled for the Covered Code.\n"
        + "\n"
        + "4. Inability to Comply Due to Statute or Regulation. If it is impossible for You"
        + " to comply with any of the terms of this License with respect to some or all of "
        + "the Covered Code due to statute, judicial order, or regulation then You must: (a"
        + ") comply with the terms of this License to the maximum extent possible; and (b) "
        + "describe the limitations and the code they affect. Such description must be incl"
        + "uded in the LEGAL file described in Section 3.4 and must be included with all di"
        + "stributions of the Source Code. Except to the extent prohibited by statute or re"
        + "gulation, such description must be sufficiently detailed for a recipient of ordi"
        + "nary skill to be able to understand it.\n"
        + "\n"
        + "5. Application of this License. This License applies to code to which the Initia"
        + "l Developer has attached the notice in Exhibit A and to related Covered Code.\n"
        + "\n"
        + "6. Versions of the License.\n"
        + "\n"
        + "6.1 New Versions. The Storage Networking Industry Association (the \"SNIA\") may p"
        + "ublish revised and/or new versions of the License from time to time. Each versio"
        + "n will be given a distinguishing version number.  \n"
        + "\n"
        + "6.2 Effect of New Versions. Once Covered Code has been published under a particu"
        + "lar version of the License, You may always continue to use it under the terms of"
        + " that version. You may also choose to use such Covered Code under the terms of a"
        + "ny subsequent version of the License published by the SNIA. No one other than th"
        + "e SNIA has the right to modify the terms applicable to Covered Code created unde"
        + "r this License.  \n"
        + "\n"
        + "6.3 Derivative Works. If You create or use a modified version of this License (w"
        + "hich you may only do in order to apply it to code which is not already Covered C"
        + "ode governed by this License), You must (a) rename Your license so that the phra"
        + "ses \"Storage Networking Industry Association,\" \"SNIA,\" or any confusingly simila"
        + "r phrase do not appear in your license (except to note that your license differs"
        + " from this License) and (b) otherwise make it clear that Your version of the lic"
        + "ense contains terms which differ from the SNIA Public License. (Filling in the n"
        + "ame of the Initial Developer, Original Code or Contributor in the notice describ"
        + "ed in Exhibit A shall not of themselves be deemed to be modifications of this Li"
        + "cense.)\n"
        + "\n"
        + "7. DISCLAIMER OF WARRANTY. COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN \"AS"
        + " IS\" BASIS, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING"
        + ", WITHOUT LIMITATION, WARRANTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCH"
        + "ANTABLE, FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO T"
        + "HE QUALITY AND PERFORMANCE OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED C"
        + "ODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY OTHER "
        + "CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION. T"
        + "HIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. NO USE"
        + " OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.\n"
        + "\n"
        + "8. TERMINATION.\n"
        + "\n"
        + "8.1 This License and the rights granted hereunder will terminate automatically i"
        + "f You fail to comply with terms herein and fail to cure such breach within a rea"
        + "sonable time after becoming aware of the breach. All sublicenses to the Covered "
        + "Code which are properly granted shall survive any termination of this License. P"
        + "rovisions which, by their nature, must remain in effect beyond the termination o"
        + "f this License shall survive.  \n"
        + "\n"
        + "8.2 If You initiate litigation by asserting a patent infringement claim (excludi"
        + "ng declaratory judgment actions) against Initial Developer or a Contributor (the"
        + " Initial Developer or Contributor against whom You file such action is referred "
        + "to as \"Participant\") alleging that: o (a) such Participant's Contributor Version"
        + " directly or indirectly infringes any patent, then any and all rights granted by"
        + " such Participant to You under Sections 2.1 and/or 2.2 of this License shall, up"
        + "on 60 days notice from Participant terminate prospectively, unless if within 60 "
        + "days after receipt of notice You either: (i) agree in writing to pay Participant"
        + " a mutually agreeable reasonable royalty for Your past and future use of Modific"
        + "ations made by such Participant, or (ii) withdraw Your litigation claim with res"
        + "pect to the Contributor Version against such Participant. If within 60 days of n"
        + "otice, a reasonable royalty and payment arrangement are not mutually agreed upon"
        + " in writing by the parties or the litigation claim is not withdrawn, the rights "
        + "granted by Participant to You under Sections 2.1 and/or 2.2 automatically termin"
        + "ate at the expiration of the 60 day notice period specified above.  \n"
        + "\n"
        + "8.3 If You assert a patent infringement claim against Participant alleging that "
        + "such Participant's Contributor Version directly or indirectly infringes any pate"
        + "nt where such claim is resolved (such as by license or settlement) prior to the "
        + "initiation of patent infringement litigation, then the reasonable value of the l"
        + "icenses granted by such Participant under Sections 2.1 or 2.2 shall be taken int"
        + "o account in determining the amount or value of any payment or license.  \n"
        + "\n"
        + "8.4 In the event of termination under Sections 8.1 or 8.2 above, all end user li"
        + "cense agreements (excluding distributors and resellers) which have been validly "
        + "granted by You or any distributor hereunder prior to termination shall survive t"
        + "ermination.\n"
        + "\n"
        + "9. LIMITATION OF LIABILITY. UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WH"
        + "ETHER TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE, SHALL YOU, THE INITIA"
        + "L DEVELOPER, ANY OTHER CONTRIBUTOR, OR ANY DISTRIBUTOR OF COVERED CODE, OR ANY S"
        + "UPPLIER OF ANY OF SUCH PARTIES, BE LIABLE TO ANY PERSON FOR ANY INDIRECT, SPECIA"
        + "L, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMI"
        + "TATION, DAMAGES FOR LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNC"
        + "TION, OR ANY AND ALL OTHER COMMERCIAL DAMAGES OR LOSSES, EVEN IF SUCH PARTY SHAL"
        + "L HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION OF LIAB"
        + "ILITY SHALL NOT APPLY TO LIABILITY FOR DEATH OR PERSONAL INJURY RESULTING FROM S"
        + "UCH PARTY'S NEGLIGENCE TO THE EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION. S"
        + "OME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONS"
        + "EQUENTIAL DAMAGES, SO THIS EXCLUSION AND LIMITATION MAY NOT APPLY TO YOU.\n"
        + "\n"
        + "10. U.S. GOVERNMENT END USERS. The Covered Code is a \"commercial item,\" as that "
        + "term is defined in 48 C.F.R. 2.101 (Oct. 1995), consisting of \"commercial comput"
        + "er software\" and \"commercial computer software documentation,\" as such terms are"
        + " used in 48 C.F.R. 12.212 (Sept. 1995). Consistent with 48 C.F.R. 12.212 and 48 "
        + "C.F.R. 227.7202-1 through 227.7202-4 (June 1995), all U.S. Government End Users "
        + "acquire Covered Code with only those rights set forth herein.\n"
        + "\n"
        + "11. MISCELLANEOUS This License represents the complete agreement concerning subj"
        + "ect matter hereof. If any provision of this License is held to be unenforceable,"
        + " such provision shall be reformed only to the extent necessary to make it enforc"
        + "eable. This License shall be governed by California law provisions (except to th"
        + "e extent applicable law, if any, provides otherwise), excluding its conflict-of-"
        + "law provisions. The application of the United Nations Convention on Contracts fo"
        + "r the International Sale of Goods is expressly excluded. Any law or regulation w"
        + "hich provides that the language of a contract shall be construed against the dra"
        + "fter shall not apply to this License.\n"
        + "\n"
        + "12. RESPONSIBILITY FOR CLAIMS. As between Initial Developer and the Contributors"
        + ", each party is responsible for claims and damages arising, directly or indirect"
        + "ly, out of its utilization of rights under this License and You agree to work wi"
        + "th Initial Developer and Contributors to distribute such responsibility on an eq"
        + "uitable basis. Nothing herein is intended or shall be deemed to constitute any a"
        + "dmission of liability.\n"
        + "\n"
        + "13. MULTIPLE-LICENSED CODE. Initial Developer may designate portions of the Cove"
        + "red Code as \"Multiple-Licensed\". \"Multiple-Licensed\" means that the Initial Deve"
        + "loper permits you to utilize portions of the Covered Code under Your choice of t"
        + "his License or the alternative licenses, if any, specified by the Initial Develo"
        + "per in the file described in Exhibit A.\n"
        + "\n"
        + "14. ACCEPTANCE. This License is accepted by You if You retain, use, or distribut"
        + "e the Covered Code for any purpose.\n"
        + "\n"
        + "EXHIBIT A The SNIA Public License.\n"
        + "\n"
        + "The contents of this file are subject to the SNIA Public License Version 1.0 (th"
        + "e \"License\"); you may not use this file except in compliance with the License. Y"
        + "ou may obtain a copy of the License at\n"
        + "\n"
        + "www.snia.org/smi/developers/cim/\n"
        + "\n"
        + "Software distributed under the License is distributed on an \"AS IS\" basis, WITHO"
        + "UT WARRANTY OF ANY KIND, either express or implied. See the License for the spec"
        + "ific language governing rights and limitations under the License.\n"
        + "\n"
        + "The Original Code is .\n"
        + "\n"
        + "The Initial Developer of the Original Code is [COMPLETE THIS] .\n"
        + "\n"
        + "Contributor(s): ______________________________________.\n"
        + "\n"
        + "Read more about this license at http://www.snia.org/smi/developers/open_source/\n"
; // the license text
    }
 
    
}
