/*
 * SPDXVersion: SPDX-1.1
 * Creator: Person: Nuno Brito (nuno.brito@triplecheck.de)
 * Creator: Organization: TripleCheck (contact@triplecheck.de)
 * Created: 2014-05-12T09:29:20Z
 * LicenseName: AGPL-3.0+
 * FileName: SPDXfile.java  
 * FileType: SOURCE
 * FileCopyrightText: <text> Copyright 2014 Nuno Brito, TripleCheck </text>
 * FileComment: <text> This class aims to provide a more compact and faster
 * way of processing SPDX documents than its predecessor. The basic principles
 * of functioning are:
 *  - No text files saved in memory
 *  - Be aggressive in avoiding strings, adopt types whenever possible
 *  - Reading and writing operations can be only be done internally</text> 
 */

package spdxlib;

import license.LicenseType;
import license.License;
import spdxlib.swing.TreeNodeSPDX;
import definitions.id;
import definitions.is;
import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.engine;
import main.script.log;
import spdxlib.summary.SummaryControl;
import spdxlib.swing.NodeType;
import definitions.structure.LanguageCounter;
import license.LicenseCounter;
import utils.files;
import utils.www.html;


/**
 *
 * @author Nuno Brito, 10th of April 2014 in Darmstadt, Germany.
 *  nuno.brito@triplecheck.de | http://nunobrito.eu
 */
public class SPDXfile implements Serializable{
 
    // how many files have we indexed?
    private int fileCounter = 0;
    
    // what is the information within?
    private ArrayList<FileInfo> files = new ArrayList();
    
    public SummaryControl summary = new SummaryControl(this);
    
    // which file was used for reading this document?
    public File file;
    
    // the node where all info about files is stored
    private TreeNodeSPDX nodeFiles = new TreeNodeSPDX("Files");
    
    private TreeNodeSPDX 
            nodeAuthorship,
            nodeSettings,
            nodeComponents,
            nodeExport;
    
    // define our authorship counters
    private int 
            filesAuthored = 0,
            filesExternal = 0,
            filesModified = 0,
            filesAutoGenerated = 0,
            filesAutomixed = 0,
            filesUnknown = 0;
    
    // temporary values only used during the initial processing
    FileInfo tempInfo;
    int charPosition = 1;
    private boolean hasComputedStats = false; // were stats calculated already?
        
    // statistical variables
    private int 
        countLicensesDeclared = 0,
        countLicensesConcluded = 0,
        countFilesWithCopyright = 0,
        countLOC = 0,
        countSize = 0;

    // variables used for the language calculation
    private boolean languagesWereNotEvaluated = true;
    //final private EnumMap<FileLanguage, Integer> countMainLanguages = new EnumMap<FileLanguage, Integer>(FileLanguage.class);
    final private LanguageCounter languageCounter = new LanguageCounter();
    // this list keeps files where multiple languages apply
    final private ArrayList<FileInfo> secondList = new ArrayList();

    // variables for handling the licenses inside this document
    final private LicenseCounter licenseCounter = new LicenseCounter();
    
    // was a license declared for this package?
    private License packageLicenseDeclared;
    private String 
            packageLicenseDeclaredText,
            packageName,
            sourceFolder;
    
    // global variables only used during a read of the document
    String globalLine;
    
    // default constructor, we need a file to proceed
    public SPDXfile(final File canonicalFile) {
        this.file = canonicalFile;
        readSPDXfile(file);
    }
    
    /**
     * Refresh the internal variables when we change some values inside the spdx
     */
    public void refresh(){
        files = new ArrayList();
        nodeFiles = new TreeNodeSPDX("Files");
        nodeAuthorship = new TreeNodeSPDX("Authorship");
        charPosition = 1;
        tempInfo = null;
        fileCounter = 0;
    }
    
    /**
     * A constructor without arguments. This method is not public to permit
     * only the other classes on this package to access.
     */
    SPDXfile() {
    }

    /**
     * The name for this SPDX document
     * @return  The name of this SPDX document without the .SPDX extension
     */
    public final String getId(){
        return file.getName().replace(".spdx", "");
    }

    public final String getUID(){
        return ">> "+file.getName()+" >> Reports ";
    }
    
    /**
     * Provides details about the author ship of this SPDX document
     * @return An HTML document ready to be shown at the end-user
     */
    public String computeAuthorship() {
        String result = html.h2("Authorship details");
        // reset our authorship counters back to zero
        filesAuthored = 0;
        filesExternal = 0;
        filesModified = 0;
        filesAutoGenerated = 0;
        filesAutomixed = 0;
        filesUnknown = 0;
        
        final ArrayList<FileInfo> listUnknown = new ArrayList();
        
        // now iterate all the file objects that we have listed
        for(final FileInfo fileInfo : files){
            switch(fileInfo.getFileOrigin()){
                case AUTHORED: filesAuthored++; break;
                case EXTERNAL: filesExternal++; break;
                case MODIFIED: filesModified++; break;
                case AUTOGENERATED: filesAutoGenerated++; break;
                case AUTOMIXED: filesAutomixed++; break;
                case UNKNOWN: 
                    filesUnknown++; 
                    listUnknown.add(fileInfo);
                    break;
            }
        }
        
        // output the result
        result += showAuthorshipDetail("Original files: ", filesAuthored)
                + showAuthorshipDetail("Third-party files: ", filesExternal)
                + showAuthorshipDetail("Modified third-party files: ", filesModified)
                + showAuthorshipDetail("Automatically generated files: ", filesAutoGenerated)
                + showAuthorshipDetail("Automatically generated files that were modified: ", filesAutomixed)
                + showAuthorshipDetail("Files with unknown authorship: ", filesUnknown)
                + html.br
                ;
        
        
        // add a list of files that we should process
        if(filesUnknown > 0 && filesUnknown < 1000){
            result += html.h2("Files missing to process:");
            for(FileInfo fileInfo : listUnknown){
                result += fileInfo.getFileName() + html.br;
            }
        }
        
        // add the div alignment
        result = html.div()
                + result
                + html._div;
        
        return result;
    }

    private String showAuthorshipDetail(final String what, final int counter){
        if(counter == 0){
            return "";
        }else{
            return what + counter + html.br;
        }
    }

    /**
     * Returns the path related to the reports folder
     * @return 
     */
    public String getRelativePath() {
        return file.getAbsolutePath().replace(engine.getProductsFolder().
                getAbsolutePath(), "").replace("\\", "/");
    }

    public TreeNodeSPDX getNodeExport() {
        return nodeExport;
    }

    /**
     * Read the information from the header
     * @param reader 
     */
    private void processHeader(BufferedReader reader) {
        try {
            while ((globalLine = reader.readLine()) != null) {
                // increase the char counting
                charPosition+= globalLine.length() + 1;
                
                // PackageLicenseDeclared:
                if(tagStartsWith(is.tagPackageLicenseDeclared, globalLine)){
                    packageLicenseDeclaredText = tagGetValue(is.tagPackageLicenseDeclared, globalLine);
                }
                
                // PackageName:
                if(tagStartsWith(is.tagPackageName, globalLine)){
                    packageName = tagGetValue(is.tagPackageName, globalLine);
                }
                
                
                // have we read enough?
                if(globalLine.startsWith("FileName:")){
                    // no more header information available
                    break;
                }
            }
            
        } catch (IOException ex) {
            Logger.getLogger(SPDXfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Returns the declared name for this package
     * @return 
     */
    public String getPackageName() {
        if(packageName == null){
            return "";
        }else{
            return packageName;
        }
    }

    // used for tags with multiple lines, such as:
    // FileCopyrightText -> COPYRIGHT
    enum mTypes {COPYRIGHT};
    boolean isMultiple = false;
    // when "isMultiple" is true, then lastTag needs to be defined
    mTypes lastTag;
    // this line keeps the continuation of multiple lines, separated by \n
    private String lastLine;
    

    /**
     * Reads the data inside an SPDX tag/value document onto this object
     * @param file  an SPDX file on disk
     */
    private void readSPDXfile(File file) {
        // go through all the lines of this text file
        readLines(file);
    }
    
    /**
     * The objective of this method is to go throught each line on a given
     * text file and extract every possible information in regards to tag/value
     * data. The result is an arraylist of tags that contain in sequential order
     * all the tag/value entries that were found.
     */
    private void readLines(final File file){
        // iterate through all lines
        charPosition = 0;
        int lineCounter = 0;
      try {
          BufferedReader reader = new BufferedReader(new FileReader(file));
          // get information from the header data (when available)
          processHeader(reader);
          
          // process the file information
          while (globalLine != null) {
               try {
                    // increase the line counter
                    lineCounter++;
                    // read the tag/value information
                    processFileLine(globalLine, charPosition);
               } catch (Exception ex) {
                    log.write(is.ERROR, "SPDX246: Error reading line: %1 of file %2"
                            + " with content: %3"
                            ,lineCounter + "", file.getAbsolutePath(),
                            globalLine);
                    ex.printStackTrace();
                    // no need to stop, continue to the next item
                    continue;
                }
                // increase the char counting
                charPosition+= globalLine.length() + 1;
                // move to the next line
                globalLine = reader.readLine();
            }
            reader.close();
            // small tidybits that were left to fix up
            postProcessing();
      } catch (IOException ex) {
          Logger.getLogger(files.class.getName()).log(Level.SEVERE, null, ex);
          // something went wrong
          log.write(is.ERROR, "Error when reading line: %1 of file %2"
                  ,charPosition + "", file.getAbsolutePath());
      }
    }

    /**
     * This method checks if a given line has the </text> tag which represents
     * the end of a multiple line. When this happens, we collect the result
     * and write back the value.
     * @param line  The line to be processed
     */
    void doMultipleLineCheck(final String line){
        // can we stop accounting these lines as multiple?
        if(line.endsWith(is.textFinal)){
                    isMultiple = false;
                    // now write the appropriate key holder
                    switch(lastTag){
                        // for the moment, only copyright tags use multiple text
                        case COPYRIGHT:
                            final String temp = lastLine
                                    .substring(is.tagFileCopyrightText.length());
                            tempInfo.setFileCopyrightText(temp);
                            break;
                    }
        }
    }
    
    /**
     * Add this piece of data onto our object being formed
     * @param line  the text line to be processed
     * @param charPosition  At which position of the text file is this line?
     */
    private void processFileLine(String line, int linePosition) {
        // multiple lines take precedence and need to be processed first
        // was any license found inside this file?
        if(tagStartsWith(is.tagFileCopyrightText, line)){
            isMultiple = true;
            lastTag = mTypes.COPYRIGHT;
            lastLine = "";
        }
        // is this line a continuation of a previous multiple line?
        if(isMultiple){
            // add this new line, plus a break line
            lastLine = lastLine.concat(line + "\n");
            doMultipleLineCheck(line);
        }else
        // start the block to process all other file tags 
        // have we found a file?
        if(tagStartsWith(is.tagFileName, line)){
            final String fileName = tagGetValue(is.tagFileName, line);
            // create the new file object
            FileInfo fileInfo = new FileInfo(this);
            // add the respective file name
            fileInfo.setFileName(fileName);
            // set the file line position
            fileInfo.setLinePosition(linePosition);
            // compute the file node
            fileInfo.computeNode(nodeFiles);
            // set this file as the last one we have indexed
            tempInfo = fileInfo;
            // add it up to our general counter
            files.add(fileInfo);
            // increase the file counter
            fileCounter++;
        }else
        // Now proceed to find the file type
        if(tagStartsWith(is.tagFileType, line)){
            final String temp = tagGetValue(is.tagFileType, line);
            tempInfo.setFileType(FileType.valueOf(temp));
        }else
        // was a checksum reported?
        if(tagStartsWith(is.tagFileChecksum, line)){
            processChecksumLine(line.substring(
                    is.tagFileChecksum.length()+1));
        }else
        // is a LOC value ready?
        if(tagStartsWith(is.tagFileLOC, line)){
           final String temp = tagGetValue(is.tagFileLOC, line);
           tempInfo.setFileLOC(Integer.parseInt(temp)); 
        }else
        // is a file size value available?
        if(tagStartsWith(is.tagFileSize, line)){
           processFileSizeLine(line.substring(
                    is.tagFileSize.length()+1));
        }else
        // was any license found inside this file?
        if(tagStartsWith(is.tagLicenseInfoInFile, line)){
           final String temp = tagGetValue(is.tagLicenseInfoInFile, line);
            tempInfo.addLicenseInfoInFile(LicenseType.convertToEnum(temp));
         }else
        // Was an origin defined for this file?
        if(tagStartsWith(is.tagFileOrigin, line)){
            final String temp = tagGetValue(is.tagFileOrigin, line);
            tempInfo.setFileOrigin(FileOrigin.valueOf(temp));
        }
        else
       // Was an origin defined for this file?
        if(tagStartsWith(is.tagFileComponent, line)){
            final String temp = tagGetValue(is.tagFileComponent, line);
            tempInfo.setFileComponent(temp);
        }
        else
        // Is a license defined for this file?
        if(tagStartsWith(is.tagLicenseConcluded, line)){
            final String temp = tagGetValue(is.tagLicenseConcluded, line);
            tempInfo.setLicenseConcluded(LicenseType.convertToEnum(temp));
        }else
        if(tagStartsWith(is.tagFileMatchSnippet, line)){
            tempInfo.addMatchSnippet(line);
        }
        else
        if(tagStartsWith(is.tagFileMatchBinary, line)){
            final String temp = tagGetValue(is.tagLicenseConcluded, line);
            tempInfo.addMatchBinary(temp);
        }
        
        
    }
    
    /**
     * This method process the lines related to the checksum of a given
     * file object. 
     */
    private void processChecksumLine(final String line){
      // was a checksum reported?
        if(tagStartsWith(is.tagFileChecksumSHA1, line)){
            final String temp = tagGetValue(is.tagFileChecksumSHA1, line);
            tempInfo.setTagFileChecksumSHA1(temp);
        }else
        if(tagStartsWith(is.tagFileChecksumSHA256, line)){
            final String temp = tagGetValue(is.tagFileChecksumSHA256, line);
            tempInfo.setTagFileChecksumSHA256(temp);
        }else
        if(tagStartsWith(is.tagFileChecksumMD5, line)){
            final String temp = tagGetValue(is.tagFileChecksumMD5, line);
            tempInfo.setTagFileChecksumMD5(temp);
        }else
        if(tagStartsWith(is.tagFileChecksumTLSH, line)){
            final String temp = tagGetValue(is.tagFileChecksumTLSH, line);
            tempInfo.setTagFileChecksumTLSH(temp);
        }
    }
    
    /**
     * Translates the string from a human-readable value onto
     * a long number that can be processed
     * @param substring 
     */
    private void processFileSizeLine(final String value) {
        // find the "(" char which is represented by "40" in ASCII
        final int index = value.indexOf(40);
        if(index==-1){
            // find the space character
            final int space = value.indexOf(32);
            final String size = value.substring(0, space);
            tempInfo.setFileSize(Long.parseLong(size));
        }else{
            // exclude the " bytes)" portions which is sized in 7 bytes
            final String size = value.substring(index+1, value.length()-7);
            tempInfo.setFileSize(Long.parseLong(size));
        }
    }
      
    
    /**
     * Does a given line starts with a given tag name? This is a method
     * optimized for perfomance
     * @param tagName   The tag to find
     * @param line      The line where the tag might be located
     * @return 
     */
    private boolean tagStartsWith(final String tagName, final String line){
        return (line.length() > tagName.length()
                && line.substring(0,tagName.length()).equals(tagName));
    }
    
    /**
     * Returns the value of a given tag
     * @param tagName   The tag to find
     * @param line      The line where the tag might be located
     * @return 
     */
    private String tagGetValue(final String tagName, final String line){
        return line.substring(tagName.length() + 1);
    }
  
    /**
     * Print some feedback about this object
     */
    public void printFeedback(){
              
        System.out.println("SP284 - SPDX: " + file.getName()
              + " with " + charPosition + " characters");
        
        System.out.println(fileCounter + " files processed");
        
        System.out.println(files.get(0).getFileName());
        int counter = 0;
        int counterLOC = 0;
        long counterSize = 0;
        for(FileInfo fileInfo : files){
            if(fileInfo.getFileType() == FileType.SOURCE){
                counter++;
                counterLOC += fileInfo.getFileLOC();
                counterSize += fileInfo.getFileSize();
             }
         }
         System.out.println("Source files: " + counter);
         System.out.println("Total LOC: " + counterLOC);
         System.out.println("Total Size: " + utils.files.humanReadableSize(counterSize));
    }

    /**
     * Gets the list of files that were indexed
     * @return  An array with all the related FileInfo objects
     */
    public ArrayList<FileInfo> getFiles() {
        return files;
    }

    /**
     * Get the pointer to the SPDX document on disk (if one exists)
     * @return The pointer to a file on disk
     */
    public File getFile() {
        return file;
    }
  
    
    
    /**
     * When available, gives back the location where we can find the source code
     * files that were used when creating this document.
     * @return A pointer to the folder where the source code files are located
     */
    public File getSourceFolder() {
        // do we have this value in cache or not? If so, provide the cache.
        if(sourceFolder != null){
            return new File(sourceFolder);
        }
        
        // we need the file associated to this spdx to exist
        if(file== null){
            return null;
        }
        // get the title
        final String title = id.SOURCEFOLDER + file.getName();
        final File fileSettings = new File("settings.xml");
        // read the settings content
        final String content = utils.files.readAsString(fileSettings);
        final String[] lines = content.split("\n");
        String folderLocation = "";
        for(final String line : lines){
            // skips lines that don't matter
            if(line.contains(title) == false){
                continue;
            }
            final int p1 = line.indexOf(">") + 1;
            final int p2 = line.indexOf("</entry>");
            folderLocation = line.substring(p1, p2);
            break;
        }
        
        // empty value means nothing found
        if(folderLocation.isEmpty()){
            return null;
        }
        
        // create the folder pointer
        File folder = new File(folderLocation);
        
        // doesn't exist?
        if(folder.exists() == false){
            return null;
        }
        sourceFolder = folder.getAbsolutePath();
        // all done!
        return folder;
    }
    
    /**
     * Defines the folder where the source code files are located. This method
     * will save the value on the disk settings
     * @param folder    A folder on disk
     */
    public void setSourceFolder(final File folder){
        if(file== null){
            return;
        }
        // get the title
        final String title = id.SOURCEFOLDER + file.getName();
        engine.settings.write(title, folder.getAbsolutePath());
            
    }
    
    /**
     * How many licenses were declared inside this document?
     * @return  The sum of licenses inside the source code
     */
    public int getLicensesDeclaredCount() {
        int counter = 0;
        for(FileInfo fileInfo : files){
            //counter += //fileInfo.getLicenseInfoInFileCounter();
            if(fileInfo.hasLicenseConcluded() || fileInfo.hasLicenseInfoInFile()){
                counter++;
            }
        }
        return counter;
    }
    
    /**
     * Get the summary for the languages adopted across this project
     * @return      An HTML string with the summary of adopted languages
     */
    public String getLanguageEvaluation() {
        if(languagesWereNotEvaluated){
            evaluateLanguagesAndLicenses();
        }
        
        // where we will store the results
        String result = "";
        
        // create a list sorted according to biggest on top
        Map<FileLanguage,Integer> map = languageCounter.sortedMap();
        // how many files do we have in total?
        int total = languageCounter.getOverallCounter();
        for(FileLanguage language : map.keySet()){
            int value = languageCounter.get(language);
            // ignore the empty languages
            if(value == 0){
                continue;
            }
            result += 
                    utils.text.pluralize(value, 
                             language.toString() 
                            + " file")
                    + " ("
                    + utils.misc.getPercentage(value, total) + "%"
                    + ")"
                    + html.br;
        }
        return result;
    }


        
    /**
     * Get the summary for the languages adopted across this project
     * @return      An HTML string with the summary of adopted licenses
     */
    public String getLicenseEvaluationHTML() {
        if(languagesWereNotEvaluated){
            evaluateLanguagesAndLicenses();
        }
        
        // where we will store the results
        String result = "";
        
         // create a licensing list sorted according to biggest on top
        Map<LicenseType,Integer> mapLicenses = licenseCounter.sortedMap();
        // how many files do we have in total?
        int totalLicenses = licenseCounter.getOverallCounter();
        for(LicenseType license : mapLicenses.keySet()){
            int value = licenseCounter.get(license);
            // ignore the empty languages
            if(value == 0){
                continue;
            }
            result += ""
                    + utils.misc.getPercentage(value, totalLicenses) + "%"
                    + " "
                    + license.toId()
                    + " ("
                    + utils.text.pluralize(
                            value, 
                             "file")
                    + ")"
                    + " "
                    + "<%t1%>" + license.toId() + "</%t1%>"
                    + "<%t2%>" + license.toId() + "</%t2%>"
                    + html.br;
        }
        return result;
    }
    
    /**
     * Provides a text array with each license found on the document
     * First field is the percentage, second field is the license type
     * and the last field is the number of occurrences.
     * @return 
     */
    public String getLicenseEvaluationArray() {
        if(languagesWereNotEvaluated){
            evaluateLanguagesAndLicenses();
        }
        
        // where we will store the results
        String result = "";
        
         // create a licensing list sorted according to biggest on top
        Map<LicenseType,Integer> mapLicenses = licenseCounter.sortedMap();
        // how many files do we have in total?
        int totalLicenses = licenseCounter.getOverallCounter();
        // 
        if(mapLicenses.keySet().isEmpty()){
            return null;
        }
        for(LicenseType license : mapLicenses.keySet()){
            int value = licenseCounter.get(license);
            // ignore the empty languages
            if(value == 0){
                continue;
            }
            result += ""
                    + utils.misc.getPercentage(value, totalLicenses)
                    + "|"
                    + license.toId()
                    + "|"
                    + value
                    + "\n"
                    ;
            
        }
        
        // nothing was found here
        if(result.isEmpty()){
            return null;
        }
        
        // remove the last line break
        return result.substring(0, result.length() -1);
    }
    
    /**
     * Runs the code for evaluating the type of languages being used
     * inside the project files
     */
    private void evaluateLanguagesAndLicenses(){
        // the main loop
        for(FileInfo fileInfo : files){
            computeLanguages(fileInfo);
            // also compute the licenses
            licenseCounter.increment(fileInfo.getLicenseInfoInFile());
        }
        
        // now process the languages on the second list
        computeLanguageSecondList();
        
        // set the marker that we have evaluated the languages
        languagesWereNotEvaluated = false;
    }
    
    
    /**
     * Process the files that we are not certain about which
     * type of language is applicable since they are sometimes
     * used by different programming languages
     */
    private void computeLanguageSecondList(){
        // now go through the second list, try to discover where the files
        // applicable to multiple languages belong
        
        // iterate through all these files
        for(FileInfo fileInfo : secondList){
           // get the respective extension
//            FileExtension extension = fileInfo.getExtensionObject();
           // let's do some ranking
            int highestCount = 0;
            FileLanguage top = null;
            // go through each indexed language
            for(FileLanguage thisLang : FileLanguage.values()){
                
                if(languageCounter.get(thisLang)==0){
                    continue;
                }
//                else
                // we only want the possible candidates
//                if(extension.getLanguages().contains(thisLang)==false){
//                    continue;
//                }
                // get the current value
                int thisCount = languageCounter.get(thisLang);
                // if this is a high-value, use it as marker
                if(thisCount > highestCount){
                    // we have a possible value
                    top = thisLang;
                    highestCount = thisCount;
                }
            }
            // now we have the top-ranking candidate
            if(top != null){
                languageCounter.increment(top);
            }
        }
        // now delete the second list elements to save memory
        secondList.clear();
    }
    
    
    /**
     * Outputs a summary of the licenses that were both both concluded as
     * applicable to files inside the project, as the licenses found inside
     * within the source code.
     * @return 
     */
    public String summaryConcludedLicenses() {
         
        // compute the number of licenses declared if not done before
        String result = ""
                + countFilesWithCopyright
                + " files with copyright declared" 
                + html.br
                + countLicensesDeclared
                + " files with declared licenses" 
                + html.br
                + countLicensesConcluded
                + " files with concluded licenses" 
                + html.br
                ;
        
        return result;
    }
     
    
    /**
     * We use this method for doing a single loop that aggregates all
     * the stats that we need about this project.
     */
    private void computeStats(){
        // already done the stats? no need to continue
        if(hasComputedStats){
            return;
        }
        
        // the main loop
        for(FileInfo fileInfo : files){
            computeLicenses(fileInfo);
//            computeLanguages(fileInfo);
        }
        hasComputedStats = true;
        
        
    }

    
    
    /**
     * Calculate the language related statistics.
     * @param fileInfo      the file object being calculated    
     */
    private void computeLanguages(FileInfo fileInfo){
        // get the language object or just "unknown" if not indexed before
        FileLanguage thisLanguage = //core.extensions.getUnknownExtension().getLanguage();
                fileInfo.getExtensionObject().getLanguage();
        
        // we only want files with a specified language
        if(thisLanguage == FileLanguage.UNSORTED){
        }else
        // if the file is used by multiple languages, then we place it
        // on a post-processing list to discover how it is being used.
        if(thisLanguage == FileLanguage.MULTIPLE){
            secondList.add(fileInfo);
            // no need to proceed, skip to next file
        }else
            languageCounter.increment(thisLanguage);
    }
    
    /**
     * During the compute loop, calculate the value for the licenses
     * @param fileInfo  A fileInfo object
     */
    private void computeLicenses(FileInfo fileInfo){
        // get the lines of code and size of file
        countLOC += fileInfo.getFileLOC();
        countSize += fileInfo.getFileSize();
        // have we been through this file to mark licenses?
        if(fileInfo.hasLicenseConcluded()){
            countLicensesConcluded++;
        }
        // where licenses declared?
        if(fileInfo.hasLicenseInfoInFile()){
            countLicensesDeclared++;
        }
        // count the copyright assignments
        final String copyrights = fileInfo.getFileCopyrightText();
        if((copyrights != null)&&(copyrights.isEmpty() == false)){
            countFilesWithCopyright++;
        }
    }
    
    
    public int getCountLicensesDeclared() {
        return countLicensesDeclared;
    }

    public int getCountLicensesConcluded() {
        return countLicensesConcluded;
    }

    public int getCountFilesWithCopyright() {
        return countFilesWithCopyright;
    }

    public int getCountLOC() {
        return countLOC;
    }

    public int getCountSize() {
        return countSize;
    }
    
    /**
     * This method is deprecated. Marked for removal in the future
     * @return 
     */
    public String getCopyrightEvaluation() {
        System.err.println("Missing to implement Copyright evaluation");
        return "";
    }

    public TreeNodeSPDX getNodeFiles() {
        return nodeFiles;
    }

    
    public TreeNodeSPDX getNodeAuthorShip() {
        return nodeAuthorship;
    }
    
    public TreeNodeSPDX getNodeSettings() {
        return nodeSettings;
    }
    
    public TreeNodeSPDX getNodeComponents() {
        return nodeComponents;
    }
    
    
    public boolean hasVersioningFilesPresent() {
        System.err.println("Missing to implement VersioningFilesPresent");
        return false;
    }

    /**
     * Correct small tidybit that are left to process. This avoids the need
     * for IF conditions during processing
     */
    private void postProcessing() {

        // no need to continue if empty
        if(nodeFiles.getChildCount() ==0){
            return;
        }
        
        nodeFiles = (TreeNodeSPDX) nodeFiles.getFirstChild();
        nodeFiles.nodeType = NodeType.sectionFile;
        nodeFiles.id = "./";
        nodeFiles.icon = engine.iconFiles;
        // set the title
        if(fileCounter > 1){
            nodeFiles.setTitle("Files (" + fileCounter + ")");
        }else{
            nodeFiles.setTitle("Files");
        }
        
        // create the authorship node
        nodeAuthorship = createNode("Authorship", "/provenance/authorship.java",
                NodeType.sectionCreator);
        // create the settings node
        nodeSettings = createNode("Settings", "/spdx/settings.java",
                NodeType.sectionSettings);
        // create the node for reporting componentsHTML
        nodeComponents = createNode("Components", "/components/summary.java",
                NodeType.sectionComponents);
        // node for exporting the compliance data
        nodeExport = createNode("Compile", "/components/compile.java",
                NodeType.sectionExport);
        
        // get the stats done
        computeStats();
    }


    /**
     * This method permits to add new features for each SPDX document tree
     * @param title         The title of the node
     * @param scriptPath    Where the script will be executed
     * @param icon          The icon image to display on the tree
     * @param nodeType      The type of node that represents the content
     * @return              A tree Node
     */
    private TreeNodeSPDX createNode(final String title, final String scriptPath, 
            final NodeType nodeType){
        // create the tree node
        final File componentsFile = new File(engine.getPluginsFolder(), scriptPath);
        TreeNodeSPDX node = new TreeNodeSPDX(title);
        node.scriptFile = componentsFile;
        node.scriptFolder = componentsFile.getParentFile();
        node.scriptMethod = "main";
        node.nodeType = nodeType;
        // Set as object the file pointer
        node.setUserObject(this);
        return node;
    }
    
    
    /**
     * This method will get a list of given fileInfo object and write back the
     * changes as needed.
     * @param fileInfoList  A list with fileInfo objects 
     * @param tagId         The tag type that is our target to overwrite
     * @param tagValue      The value for the new (or overwritten) tag 
     * @param overwrite     If true, writes on existing value. Otherwise, 
     * adds another key/value
     */
    public void writeLines(ArrayList<FileInfo> fileInfoList,
            final String tagId, final String tagValue, Boolean overwrite){
        System.out.println("SP434 - Writing in " + file.getName());
        // first we need to sort theses values according to line position    
        Map<FileInfo, Integer> originalList = new HashMap();
        for(FileInfo fileInfo : fileInfoList){
            // we place the items on the array with the line position value
            originalList.put(fileInfo, fileInfo.getLinePosition());
        }
        // With a map we can now we sort them accordingly
        Map<FileInfo, Integer> sortedList = utils.thirdparty.MiscMethods.
                sortByComparatorSmallerFirst(originalList);
       
        // now we end up sorting them again to plain ArrayList
        ArrayList<FileInfo> list = new ArrayList();
        for(FileInfo fileInfo : sortedList.keySet()){
            list.add(fileInfo);
        }
        // now do our magic
        // create an output file in the same folder
        File outputFile = new File(file.getParentFile(), "temp.txt");
        try{
            // where we write the lines
            FileWriter fileWriter = new FileWriter(outputFile);
            BufferedWriter writer = new BufferedWriter(fileWriter, 8192);
            // from where we read the lines
            BufferedReader reader = new BufferedReader(new FileReader(file));
            // where we store the current line
            String line;
            int itemCounter = 0;
            boolean hasMoreToProcess = true;
            boolean skipNextLine = false;
            // get the first key to process
            String id = is.tagFileName + is.space + list.get(itemCounter).getFileName();
            // go trought each line
            line = reader.readLine();
            //while ((line = reader.readLine()) != null) {
            while (line != null) {
                
                if(skipNextLine){
                    skipNextLine = false;
                }else
                // write the line as seen on the original file
                writer.append(line + is.lineBreak);
                // check if should think about adding a line or not
                if(hasMoreToProcess){
                    // verify if this line is what we want to write after
                    if(utils.text.equals(id, line)){
                        
                        // if we should overwrite, we need use special code
                        if(overwrite == true){
                            int maxLines = 20;
                            int lineCounter = 0;
                            ArrayList<String> lines = new ArrayList();
                            // go through the next 20 lines of text
                            while (((line = reader.readLine()) != null)
                                    &&(lineCounter < maxLines)){
                                // if we started into the next entry, stop here
                                if(tagStartsWith(is.tagFileName, line)){
                                    // add the next line (for the next entry)
                                    lines.add(line);
                                    // break the cycle
                                    break;
                                }
                                lines.add(line);
                                lineCounter++;
                            }
                            
                            // now prepare a modified list of strings
                            ArrayList<String> linesModified = new ArrayList();
                            boolean wasOverwritten = false;
                            // iterate through each line
                            for(String thisLine : lines){
                                // do we have a match?
                                if(wasOverwritten ==false && tagStartsWith(tagId, thisLine)){
                                    // overwrite the entry
                                    thisLine = tagId + is.space + tagValue;
                                    // signal that we did changes here
                                    wasOverwritten = true;
                                }
                                // add the modified (or not) line to our list
                                linesModified.add(thisLine);
                            }
                            
                            // have we overwritten this value?
                            if(wasOverwritten == false){
                                // insert our lines after the second entry
                                linesModified.add(1, tagId + is.space + tagValue);
                            }
                            
                            // now write everything back to disk
                            for(String thisLine : linesModified){
                                 writer.append(thisLine + is.lineBreak);
                                 // write back our changes on the main line
                                 line = thisLine;
                            }
                            
                        }
                        // just add a new line if we don't care about overwrite
                        else{
                           // add up the new line
                            writer.append(tagId + is.space + tagValue + is.lineBreak);
                        }
                        
                        
                        // last phase, increase the counter
                        // increase the counter
                        itemCounter++;
                        skipNextLine = true;
                         // did we found all lines already?
                        if(itemCounter == list.size()){
                            // set this flag as false to speed up processing
                            hasMoreToProcess = false;
                        }else{
                            // get the new item
                            id = is.tagFileName + is.space + list.get(itemCounter).getFileName();
                        }
                    }// if the line equals to our id
                } // if we have more to process
                // read the next line
                if(skipNextLine == false){
                    line = reader.readLine();
                }
            }
            // finished reading and writing
            writer.close();
            reader.close();
            // now replace the original file
            boolean fileDeleted = file.delete();
            // was the file really deleted?
            if(fileDeleted){
                 outputFile.renameTo(file);
            }else{
                System.err.println("SP565 - Failed to delete: " + file.getName());
            }
            // delete the generated file
            outputFile.delete();
            System.err.println("SP559 - Finished writing in " + file.getName());
        }catch(IOException e){
            System.err.println("SP562 - Exception occurred " + e.getMessage());
        }    
    }

    public int getFilesAuthored() {
        return filesAuthored;
    }

    public int getFilesExternal() {
        return filesExternal;
    }

    public int getFilesModified() {
        return filesModified;
    }

    public int getFilesAutomated() {
        return filesAutoGenerated;
    }

    public int getFilesAutomixed() {
        return filesAutomixed;
    }

    public int getFilesUnknown() {
        return filesUnknown;
    }

    private void getLicensesIndexed(){
        engine.licenses.find();
    }
    
    public License getPackageLicenseDeclared() {
        if(packageLicenseDeclaredText == null){
            return null;
        } 
        // have we already defined a license?
        if(packageLicenseDeclared != null){
            return packageLicenseDeclared;
        }
        // get it in lowercase
        final String text = packageLicenseDeclaredText.toLowerCase();
        // avoid no assertion statements, count as null
        if(text.isEmpty()){
            return null;
        }else
        if(text.equals("noassertion")){
            return null;
        }
        
        // ok, let's start by indexing our license db (if not done already)
        engine.licenses.find();
        // then try to find a match using this identification
        packageLicenseDeclared = engine.licenses.get(packageLicenseDeclaredText);
        // will return a license if one was found, otherwise the result is null
        return packageLicenseDeclared;
    }
    
    
    
}
